#!/usr/bin/env node
// gen-t0.mjs — regenerate every T0 level-script port, and the index that
// registry.mjs registers them from.
//
// The 49 files below are the T0 tier of docs/NOTES-lua-port.md §1: comments
// stripped, `functions + if + for + while + percent + shuffle + math.random +
// nh.rn2` is zero. That is the mechanical definition, and re-running the
// classifier reproduces exactly this list plus dungeon.lua (ported in S1).
//
// Usage:
//   node tools/lua-port-gen/gen-t0.mjs            # regenerate
//   node tools/lua-port-gen/gen-t0.mjs --check    # verify, change nothing

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkPort, emitModule, fnName, parse } from './lua2des.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DAT = path.join(ROOT, 'nethack-c/recorder/dat');
const OUT = path.join(ROOT, 'js/lua-js/scripts/t0');

/** Grouped the way §7 tells the stage: quest branches, then the rest. */
export const T0 = [
    // The 34 quest levels that are pure call streams. Every role's -goal (the
    // nemesis level) and -loca (the locate level) and, for eight roles, the
    // two -fil filler levels.
    'Arc-goal', 'Arc-loca',
    'Bar-fila', 'Bar-filb', 'Bar-goal', 'Bar-loca',
    'Cav-fila', 'Cav-filb', 'Cav-goal', 'Cav-loca',
    'Hea-fila', 'Hea-filb', 'Hea-goal', 'Hea-loca',
    'Kni-fila', 'Kni-filb', 'Kni-goal', 'Kni-loca',
    'Mon-loca',
    'Pri-loca',
    'Ran-fila', 'Ran-filb', 'Ran-goal', 'Ran-loca',
    'Rog-goal', 'Rog-loca',
    'Sam-fila', 'Sam-filb', 'Sam-loca',
    'Tou-fila', 'Tou-filb',
    'Val-fila', 'Val-filb', 'Val-loca',
    'Wiz-goal',
    // Sokoban: the six levels whose layout is fixed (soko1-1 and soko1-2 have
    // a loop and a math.random, so they are T2 and belong to S4).
    'soko2-1', 'soko2-2', 'soko3-1', 'soko3-2', 'soko4-1', 'soko4-2',
    // The Elemental Planes.
    'air', 'earth', 'fire', 'water',
    // One-offs.
    'baalz',      // Gehennom: Baalzebub's lair
    'minetn-6',   // one of the seven Mine Town variants
    'tower3',     // the top of Vlad's Tower
    'tut-2',      // the second tutorial level
];

function generate(check) {
    fs.mkdirSync(OUT, { recursive: true });
    let bad = 0;
    for (const base of T0) {
        const luaPath = path.join(DAT, `${base}.lua`);
        const outPath = path.join(OUT, `${base}.mjs`);
        const text = emitModule(parse(fs.readFileSync(luaPath, 'utf8')), base);
        if (check) {
            const have = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
            if (have !== text) { process.stderr.write(`gen-t0: STALE ${base}.mjs\n`); bad++; }
        } else {
            fs.writeFileSync(outPath, text);
        }
    }
    return bad;
}

/** The index module registry.mjs registers the whole tier from. */
function index() {
    const lines = [
        '// t0/index.mjs — the 49 pure-declarative level scripts, as one map.',
        '//',
        '// GENERATED by tools/lua-port-gen/gen-t0.mjs alongside the modules it lists.',
        '// Keyed by the filename nhl_loadlua() is handed, which is what',
        '// js/lua-js/registry.mjs matches on.',
        '',
    ];
    for (const b of T0) lines.push(`import ${fnName(b)} from './${b}.mjs';`);
    lines.push('');
    lines.push('/** @type {Map<string, (api: object) => void>} */');
    lines.push('export const T0_PORTS = new Map([');
    for (const b of T0) lines.push(`    ['${b}.lua', ${fnName(b)}],`);
    lines.push(']);');
    lines.push('');
    return lines.join('\n');
}

async function main(argv) {
    const check = argv.includes('--check');
    let bad = generate(check);
    const idxPath = path.join(OUT, 'index.mjs');
    const idx = index();
    if (check) {
        if (!fs.existsSync(idxPath) || fs.readFileSync(idxPath, 'utf8') !== idx) {
            process.stderr.write('gen-t0: STALE index.mjs\n');
            bad++;
        }
    } else {
        fs.writeFileSync(idxPath, idx);
    }
    // Whether it regenerated or verified, prove every module still produces the
    // .lua's call stream.
    for (const base of T0) {
        const d = await checkPort(path.join(DAT, `${base}.lua`), path.join(OUT, `${base}.mjs`));
        if (d) { process.stderr.write(`gen-t0: CALL-STREAM FAIL ${base}: ${d}\n`); bad++; }
    }
    process.stderr.write(`gen-t0: ${T0.length} scripts, ${bad ? `${bad} PROBLEMS` : 'all clean'}\n`);
    process.exit(bad ? 1 : 0);
}

if (import.meta.url === `file://${process.argv[1]}`) await main(process.argv.slice(2));
