#!/usr/bin/env node
// build.mjs — c2js build driver.
//
// Usage: node tools/c2js/build.mjs rnd
//   transpiles nethack-c/recorder/src/rnd.c from the cached AST
//   (.cache/c2js/ast/rnd.ast.json) into js/generated/rnd.js.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { loadAst, mainFileDecls } from './ir.mjs';
import { astPathFor, compileCwdFor } from './ast-dump.mjs';
import { Emitter, loadPrelude } from './emit.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

function main() {
  const name = process.argv[2];
  if (!name) {
    console.error('usage: node tools/c2js/build.mjs <name>   # e.g. rnd');
    process.exit(2);
  }
  const srcFile = path.join(repoRoot, 'nethack-c/recorder/src', `${name}.c`);
  const astPath = astPathFor(srcFile);
  if (!fs.existsSync(srcFile)) { console.error(`no such source: ${srcFile}`); process.exit(1); }
  if (!fs.existsSync(astPath)) { console.error(`no cached AST: ${astPath} (run tools/c2js/ast-dump.mjs first)`); process.exit(1); }

  const source = fs.readFileSync(srcFile, 'utf8');
  const sha = crypto.createHash('sha256').update(source).digest('hex');
  const root = loadAst(astPath);
  const { decls, lineOf } = mainFileDecls(root, srcFile, compileCwdFor(srcFile));

  const emitter = new Emitter({ decls, lineOf, source, fileName: `${name}.c` });
  const chunks = emitter.emitModule();

  const header = [
    '// Generated by tools/c2js — do not edit by hand',
    `// Input: nethack-c/recorder/src/${name}.c`,
    `// Input sha256: ${sha}`,
    '// Transpiler: tools/c2js emit v0',
  ].join('\n');

  const imports = [];
  const bodyText = chunks.map((c) => c.join('\n')).join('\n\n');
  if (/isaac64_/.test(bodyText)) imports.push("import { isaac64_init, isaac64_next_uint64 } from '../isaac64.js';");
  if (emitter.cmachine.size) imports.push(`import { ${[...emitter.cmachine].sort().join(', ')} } from '../cmachine.js';`);

  const out = [header, '', ...imports, '', loadPrelude(), '', bodyText, ''].join('\n');

  const outDir = path.join(repoRoot, 'js/generated');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${name}.js`);
  fs.writeFileSync(outFile, out);
  console.log(`wrote ${path.relative(repoRoot, outFile)} (${out.length} bytes, ${decls.length} main-file decls)`);
}

main();
