#!/usr/bin/env node
// build.mjs — c2js build driver.
//
// Usage:
//   node tools/c2js/build.mjs rnd        # single file -> js/generated/rnd.js
//   node tools/c2js/build.mjs --all      # batch: every NetHack src/*.c, then Lua
//                                        # lib sources; coverage report to
//                                        # .cache/c2js/coverage.txt
//
// Single-file mode uses the file's runtime prelude (tools/c2js/runtime/) when
// one exists and no cross-file imports (preludes provide their own externs).
// Batch mode emits cross-file imports from the global symbol table instead
// (symbols.mjs), and no prelude — it measures emitter coverage, not runnability.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { loadAst, mainFileDecls } from './ir.mjs';
import { astPathFor, compileCwdFor } from './ast-dump.mjs';
import { Emitter, loadPrelude } from './emit.mjs';
import { listTargets, collectFile, buildSymbolMap, loadSlimIr, slimIrPath } from './symbols.mjs';
import { EMIT_VERSION, CONST_NS, CONST_MODULE, JS_RESERVED } from './emit.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const TRANSPILER_VERSION = 'c2js emit v1+batch';

/**
 * Corpus-wide bitfield widths: recordName -> { field: bits }.
 *
 * The slim IR only carries each TU's *main-file* record definitions, so a
 * struct declared in a header (rm, obj, monst, d_flags, ...) reaches the
 * emitter through symbols.mjs's record table, which has no notion of a
 * declared bit width. The emitter needs the widths to truncate bitfield
 * loads to C's semantics, so scan a couple of representative full ASTs —
 * every NetHack TU pulls in hack.h, which transitively declares all 26
 * bitfield-bearing named structs — and key the widths by record name.
 * One 27 MB AST parses in ~100 ms, so this is cheap next to the build.
 */
function collectBitfieldWidths(targets) {
  const byRecord = new Map();
  const seenGroups = new Set();
  for (const t of targets) {
    if (seenGroups.has(t.group)) continue;
    const astPath = astPathFor(t.file);
    if (!fs.existsSync(astPath)) continue;
    seenGroups.add(t.group);
    let ast;
    try { ast = loadAst(astPath); } catch { continue; }
    (function walk(n) {
      if (!n || typeof n !== 'object') return;
      if (n.kind === 'RecordDecl' && n.completeDefinition && n.name) {
        for (const c of n.inner || []) {
          if (c.kind !== 'FieldDecl' || !c.isBitfield || !c.name) continue;
          const w = bitWidthOfField(c);
          if (!w) continue;
          if (!byRecord.has(n.name)) byRecord.set(n.name, {});
          const slot = byRecord.get(n.name);
          if (slot[c.name] === undefined) slot[c.name] = w;
        }
      }
      for (const c of n.inner || []) walk(c);
    })(ast);
  }
  return byRecord;
}

/** declared width of a bitfield FieldDecl (clang puts it in a ConstantExpr child) */
function bitWidthOfField(fieldNode) {
  let w;
  (function deep(x) {
    if (!x || typeof x !== 'object' || w !== undefined) return;
    if ((x.kind === 'ConstantExpr' || x.kind === 'IntegerLiteral') && x.value !== undefined) {
      const n = Number(x.value);
      if (Number.isFinite(n) && n > 0) w = n;
      return;
    }
    for (const c of x.inner || []) deep(c);
  })(fieldNode);
  return w;
}

/**
 * Merge every TU's enum constants into js/generated/nhconst.js and return the
 * set of names it exports.
 *
 * NetHack's enum constants live in shared headers, so the same name means the
 * same value in every TU that sees it; a name that maps to two different
 * values (a genuinely file-local enum reusing a name) cannot be given one
 * global binding, so it is dropped here and keeps inlining as a literal.
 * The file is sorted by name: a stable order keeps the 5.1 re-transpile's
 * renumbering diff readable, and it is the whole point of the module — the
 * renumbering churn lands here instead of in 172 generated files.
 */
function writeConstModule(perFile) {
  const values = new Map(); // name -> value
  const conflicted = new Map(); // name -> Set of values
  for (const pf of perFile) {
    if (pf.parseError) continue;
    for (const [name, v] of pf.enumValues || []) {
      if (!values.has(name)) { values.set(name, v); continue; }
      if (values.get(name) === v) continue;
      if (!conflicted.has(name)) conflicted.set(name, new Set([values.get(name)]));
      conflicted.get(name).add(v);
    }
  }
  const names = [...values.keys()].filter((n) => !conflicted.has(n)
    && /^[A-Za-z_][A-Za-z0-9_]*$/.test(n) && !JS_RESERVED.has(n)
    && Number.isInteger(values.get(n))).sort();
  const lines = [
    '// Generated by tools/c2js — do not edit by hand',
    '// C enum constants, merged across every translation unit.',
    `// Transpiler: tools/c2js ${TRANSPILER_VERSION}`,
    '//',
    '// Generated modules reference these through a namespace import',
    `// (\`import * as ${CONST_NS} from '${CONST_MODULE}'\`): C permits a local or a`,
    '// parameter to shadow an enum constant name, and a namespace prefix is',
    '// immune to that by construction.',
    '',
    ...names.map((n) => `export const ${n} = ${values.get(n)};`),
    '',
  ];
  const outDir = path.join(repoRoot, 'js/generated');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, path.basename(CONST_MODULE)), lines.join('\n'));
  if (conflicted.size) {
    console.log(`nhconst: ${conflicted.size} name(s) with conflicting values stay inlined: ` +
      [...conflicted.keys()].slice(0, 20).join(', '));
  }
  console.log(`nhconst: ${names.length} constants exported (${values.size} distinct names seen)`);
  return new Set(names);
}

/** assemble a generated module from emitter output (+ optional prelude/imports) */
function assemble({ name, srcRel, sha, emitter, chunks, prelude, crossImports }) {
  const header = [
    '// Generated by tools/c2js — do not edit by hand',
    `// Input: ${srcRel}`,
    `// Input sha256: ${sha}`,
    `// Transpiler: tools/c2js ${TRANSPILER_VERSION}`,
  ].join('\n');

  const bodyText = chunks.map((c) => c.join('\n')).join('\n\n');

  const imports = [];
  if (/isaac64_/.test(bodyText)) imports.push("import { isaac64_init, isaac64_next_uint64 } from '../isaac64.js';");
  if (emitter.cmachine.size) imports.push(`import { ${[...emitter.cmachine].sort().join(', ')} } from '../cmachine.js';`);
  if (emitter.usesCptr || emitter.stringList.length || (prelude && /\bcptr\./.test(prelude))) {
    imports.push("import * as cptr from '../cptr.js';");
  }
  if (emitter.usesCjmp || (prelude && /\bcjmp\./.test(prelude))) {
    imports.push("import * as cjmp from '../cjmp.js';");
  }
  if (emitter.usesConsts) {
    // collision guard for the namespace prefix: a C local/param named NHC
    // would shadow the import inside its function, so any bare NHC token in
    // the body (i.e. one not written as a `NHC.` qualifier) is a hard error.
    const bare = (bodyText + (prelude || '')).match(new RegExp(`\\b${CONST_NS}\\b(?!\\.)`, 'g'));
    if (bare) throw new Error(`named-constant prefix ${CONST_NS} collides with an emitted identifier in ${name}.c`);
    imports.push(`import * as ${CONST_NS} from '${CONST_MODULE}';`);
  }
  for (const [file, names] of crossImports || []) {
    imports.push(`import { ${names.sort().join(', ')} } from './${file}.js';`);
  }

  const stringTable = emitter.stringList.length
    ? ['// string literals (C char* uses decay to CPtr into these static buffers)',
      ...emitter.stringList.map((raw, i) => `const __sl${i} = cptr.lit(${raw});`)].join('\n')
    : null;

  return [header, '', ...imports, '', ...(prelude ? [prelude, ''] : []), ...(stringTable ? [stringTable, ''] : []), bodyText, ''].join('\n');
}

function emitOneFile(name, srcFile, { prelude, crossImports } = {}) {
  const source = fs.readFileSync(srcFile, 'utf8');
  const sha = crypto.createHash('sha256').update(source).digest('hex');
  const root = loadAst(astPathFor(srcFile));
  const { decls, lineOf } = mainFileDecls(root, srcFile, compileCwdFor(srcFile));
  const emitter = new Emitter({ decls, lineOf, source, fileName: `${name}.c`, compileCwd: compileCwdFor(srcFile) });
  const chunks = emitter.emitModule();
  const srcRel = path.relative(repoRoot, srcFile);
  return assemble({ name, srcRel, sha, emitter, chunks, prelude, crossImports });
}

function writeOut(name, out) {
  const outDir = path.join(repoRoot, 'js/generated');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${name}.js`);
  fs.writeFileSync(outFile, out);
  return outFile;
}

function buildSingle(name) {
  let srcFile = path.join(repoRoot, 'nethack-c/recorder/src', `${name}.c`);
  if (!fs.existsSync(srcFile)) srcFile = path.join(repoRoot, 'tools/c2js/fixtures', `${name}.c`);
  if (!fs.existsSync(srcFile)) { console.error(`no such source: ${name}.c (looked in src/ and fixtures/)`); process.exit(1); }
  const astPath = astPathFor(srcFile);
  if (!fs.existsSync(astPath)) { console.error(`no cached AST: ${astPath} (run tools/c2js/ast-dump.mjs first)`); process.exit(1); }
  const out = emitOneFile(name, srcFile, { prelude: loadPrelude(name) });
  const outFile = writeOut(name, out);
  console.log(`wrote ${path.relative(repoRoot, outFile)} (${out.length} bytes)`);
}

// ---- batch ----

/** normalize an emitter error into a rankable cause */
function causeOf(err) {
  const m = String(err.message || err).split('\n')[0];
  let mm;
  if ((mm = m.match(/unsupported node kind (\w+)/))) return `node kind: ${mm[1]}`;
  if ((mm = m.match(/unsupported top-level decl (\w+)/))) return `top-level decl: ${mm[1]}`;
  if ((mm = m.match(/unsupported implicit cast (\w+)/))) return `implicit cast: ${mm[1]}`;
  if ((mm = m.match(/unsupported (unary|binary) op (\S+)/))) return `operator: ${mm[2]}`;
  if ((mm = m.match(/ForStmt with (\d+) parts/))) return `ForStmt shape: ${mm[1]} parts`;
  if ((mm = m.match(/^(loadFrom|storeTo): unsupported access type "([^"]+)"/))) return `${mm[1]}: ${mm[2]}`;
  if ((mm = m.match(/^layout: unknown struct (.+)$/))) return `layout: unknown struct ${mm[1]}`;
  if ((mm = m.match(/^(sizeof|sizeAlign): [^"]*"([^"]*)"/))) return `${mm[1]}: ${mm[2]}`;
  if ((mm = m.match(/^(MemberExpr \.\w+ on rep \w+)/))) return mm[1];
  if ((mm = m.match(/^(emitLValue: unsupported \w+)/))) return mm[1];
  if ((mm = m.match(/^(compound assign \S+ on [^ ]+ [^ ]+ [^ ]+)/))) return mm[1];
  return m.length > 90 ? m.slice(0, 90) + '…' : m;
}

function buildAll() {
  const force = process.argv.includes('--force');
  const targets = listTargets();
  const withPrelude = new Set(fs.readdirSync(path.join(repoRoot, 'tools/c2js/runtime'))
    .filter((f) => f.endsWith('-prelude.js')).map((f) => f.replace(/-prelude\.js$/, '')));

  // pass 1: load slim IRs (rebuilding stale ones from the full AST dumps)
  const perFile = [];
  let t0 = Date.now();
  let rebuilt = 0;
  for (const t of targets) {
    const astPath = astPathFor(t.file);
    if (!fs.existsSync(astPath)) { perFile.push({ ...t, parseError: 'no cached AST' }); continue; }
    try {
      const fresh = fs.existsSync(slimIrPath(t)) && fs.statSync(slimIrPath(t)).mtimeMs >= fs.statSync(astPath).mtimeMs;
      if (!fresh) rebuilt++;
      perFile.push(loadSlimIr(t));
    } catch (err) {
      perFile.push({ ...t, parseError: String(err.message || err) });
    }
  }
  const bitfieldWidths = collectBitfieldWidths(targets);
  const { symbols, conflicts } = buildSymbolMap(perFile.filter((p) => !p.parseError));
  // globals whose address is taken anywhere in the program must be boxed at
  // their definition (cross-file &uarm etc.)
  const externBoxed = new Set();
  for (const pf of perFile) for (const nm of pf.addressTaken || []) externBoxed.add(nm);
  // globals written from a TU that does not define them must also be boxed
  // (ES module bindings are immutable to importers)
  const varDefTUs = new Map(); // name -> Set of TU names defining a variable
  for (const pf of perFile) {
    if (pf.parseError) continue;
    for (const d of pf.defs) {
      if (d.kind !== 'variable') continue;
      if (!varDefTUs.has(d.name)) varDefTUs.set(d.name, new Set());
      varDefTUs.get(d.name).add(pf.name);
    }
  }
  for (const pf of perFile) {
    if (pf.parseError) continue;
    for (const nm of pf.writtenNames || []) {
      const defTUs = varDefTUs.get(nm);
      if (!defTUs || !defTUs.has(pf.name)) externBoxed.add(nm);
    }
  }
  // record-typed globals/arrays are byte-packed cptr.alloc storage in their
  // defining TU; every referencing TU must use byte-offset access as well
  const recordGlobals = new Set(), recordArrays = new Set();
  for (const pf of perFile) {
    for (const nm of pf.recordGlobals || []) recordGlobals.add(nm);
    for (const nm of pf.recordArrays || []) recordArrays.add(nm);
  }
  const constNames = writeConstModule(perFile);
  console.log(`pass 1: ${perFile.length} slim IRs (${rebuilt} rebuilt) in ${((Date.now() - t0) / 1000).toFixed(1)}s; ` +
    `${symbols.size} importable symbols, ${conflicts.size} conflicts`);

  // incremental emission state: skip files whose IR + emitter are unchanged
  const statePath = path.join(repoRoot, '.cache/c2js/emit-state.json');
  const emitMtime = fs.statSync(new URL('file://' + path.join(repoRoot, 'tools/c2js/emit.mjs')).pathname).mtimeMs;
  let state = { emitVersion: -1, emitMtime: 0, files: {} };
  try { state = JSON.parse(fs.readFileSync(statePath, 'utf8')); } catch {}
  const stateFresh = state.emitVersion === EMIT_VERSION && state.emitMtime === emitMtime;
  const newState = { emitVersion: EMIT_VERSION, emitMtime, files: {} };

  // pass 2: emit each file
  const results = [];
  const causes = new Map(); // cause -> [file names]
  t0 = Date.now();
  for (const pf of perFile) {
    if (pf.parseError) {
      results.push({ name: pf.name, ok: false, cause: `AST: ${pf.parseError}` });
      continue;
    }
    if (withPrelude.has(pf.name)) {
      // prelude-proven files: still refresh their generated module with the
      // current emitter (prelude included, no cross imports) — the batch
      // import graph reads them from disk, so a stale emission breaks parity
      try {
        const emitter = new Emitter({ decls: pf.decls, lineOf: pf.lineOf, source: fs.readFileSync(pf.file, 'utf8'), fileName: `${pf.name}.c`, extraRecords: pf.recordDefs, compileCwd: compileCwdFor(pf.file), anonByLoc: pf.anonByLoc, externBoxed, enumValues: pf.enumValues, constNames, recordGlobals, recordArrays, bitfieldWidths });
        const chunks = emitter.emitModule();
        const sha = crypto.createHash('sha256').update(fs.readFileSync(pf.file)).digest('hex');
        const out = assemble({ name: pf.name, srcRel: path.relative(repoRoot, pf.file), sha, emitter, chunks, prelude: loadPrelude(pf.name), crossImports: null });
        const outFile = writeOut(pf.name, out);
        let parses = true;
        try { execFileSync('node', ['--check', outFile]); } catch { parses = false; }
        results.push({ name: pf.name, ok: 'skipped', cause: `has dedicated prelude (refreshed${parses ? '' : ', PARSE FAIL'})` });
      } catch (err) {
        results.push({ name: pf.name, ok: false, cause: causeOf(err), detail: String(err.message || err).split('\n')[0] });
      }
      continue;
    }
    try {
      const emitter = new Emitter({ decls: pf.decls, lineOf: pf.lineOf, source: fs.readFileSync(pf.file, 'utf8'), fileName: `${pf.name}.c`, extraRecords: pf.recordDefs, compileCwd: compileCwdFor(pf.file), anonByLoc: pf.anonByLoc, externBoxed, enumValues: pf.enumValues, constNames, recordGlobals, recordArrays, bitfieldWidths });
      const chunks = emitter.emitModule();
      // cross-file imports: referenced but not declared here. decl.js must
      // stay a leaf (it is the globals hub in a giant import cycle); its one
      // import is resolved via globalThis at call time instead.
      const IMPORT_SKIP = { decl: new Set(['raw_printf']) };
      const skip = IMPORT_SKIP[pf.name];
      const byFile = new Map();
      for (const [refName] of emitter.refs) {
        if (emitter.declared.has(refName)) continue;
        if (skip && skip.has(refName)) continue;
        const sym = symbols.get(refName);
        if (!sym || sym.file === pf.name) continue;
        if (!byFile.has(sym.file)) byFile.set(sym.file, []);
        byFile.get(sym.file).push(refName);
      }
      const sha = crypto.createHash('sha256').update(fs.readFileSync(pf.file)).digest('hex');
      const out = assemble({ name: pf.name, srcRel: path.relative(repoRoot, pf.file), sha, emitter, chunks, prelude: null, crossImports: byFile });
      const outFile = writeOut(pf.name, out);
      // syntax check
      let parses = true;
      try { execFileSync('node', ['--check', outFile]); } catch { parses = false; }
      results.push({ name: pf.name, ok: true, parses, bytes: out.length, decls: pf.decls.length, imports: [...byFile.keys()].length });
    } catch (err) {
      const cause = causeOf(err);
      results.push({ name: pf.name, ok: false, cause, detail: String(err.message || err).split('\n')[0] });
      if (!causes.has(cause)) causes.set(cause, []);
      causes.get(cause).push(pf.name);
    }
  }

  const ok = results.filter((r) => r.ok === true);
  const skipped = results.filter((r) => r.ok === 'skipped');
  const failed = results.filter((r) => r.ok === false);
  const ranked = [...causes.entries()].sort((a, b) => b[1].length - a[1].length);
  const totalDecls = perFile.reduce((a, p) => a + (p.decls ? p.decls.length : 0), 0);
  const okDecls = ok.reduce((a, r) => a + r.decls, 0);
  const totalFns = perFile.reduce((a, p) => a + (p.defs ? p.defs.filter((d) => d.kind === 'function').length : 0), 0);
  const okFnSet = new Set(ok.map((r) => r.name));
  const okFns = perFile.filter((p) => okFnSet.has(p.name)).reduce((a, p) => a + p.defs.filter((d) => d.kind === 'function').length, 0);
  const parseFails = ok.filter((r) => !r.parses);

  const lines = [];
  lines.push(`c2js batch coverage — ${new Date().toISOString()}`);
  lines.push(`files: ${results.length} total, ${ok.length} transpiled, ${failed.length} failed, ${skipped.length} skipped (prelude-proven)`);
  lines.push(`decls covered: ${okDecls}/${totalDecls}; functions covered: ${okFns}/${totalFns}`);
  lines.push(`parse check failures among emitted: ${parseFails.length}${parseFails.length ? ' — ' + parseFails.map((r) => r.name).join(', ') : ''}`);
  lines.push('');
  lines.push('failure causes ranked by file count:');
  for (const [cause, files] of ranked) {
    lines.push(`  ${String(files.length).padStart(4)}  ${cause}    (e.g. ${files.slice(0, 4).join(', ')}${files.length > 4 ? '…' : ''})`);
  }
  lines.push('');
  lines.push('transpiled clean:');
  for (const r of ok) lines.push(`  ${r.name.padEnd(24)} ${String(r.bytes).padStart(8)} bytes  ${String(r.decls).padStart(4)} decls  ${r.imports} imports  parse:${r.parses ? 'ok' : 'FAIL'}`);
  lines.push('');
  lines.push('failures (file: cause — detail):');
  for (const r of failed) lines.push(`  ${r.name}: ${r.cause} — ${r.detail || ''}`);
  const report = lines.join('\n') + '\n';
  const reportPath = path.join(repoRoot, '.cache/c2js/coverage.txt');
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, report);
  // punted goto shapes (Rule 3): recorded for later decision
  const punted = failed.filter((r) => /^goto/.test(r.cause)).map((r) => `${r.name}: ${r.detail || r.cause}`);
  fs.writeFileSync(path.join(repoRoot, '.cache/c2js/punted.txt'),
    `# goto shapes that loud-threw in the latest batch (${new Date().toISOString()})\n` + punted.join('\n') + (punted.length ? '\n' : ''));
  fs.writeFileSync(statePath, JSON.stringify(newState));

  console.log(`pass 2: emit in ${((Date.now() - t0) / 1000).toFixed(0)}s — ${ok.length} ok, ${failed.length} failed, ${skipped.length} skipped`);
  console.log(`decls ${okDecls}/${totalDecls}, functions ${okFns}/${totalFns}, parse-failures ${parseFails.length}`);
  console.log('\ntop failure causes:');
  for (const [cause, files] of ranked.slice(0, 15)) {
    console.log(`  ${String(files.length).padStart(4)}  ${cause}    (e.g. ${files.slice(0, 3).join(', ')}${files.length > 3 ? '…' : ''})`);
  }
  console.log(`\nfull report: ${path.relative(repoRoot, reportPath)}`);
}

if (process.argv[2] === '--all') buildAll();
else buildSingle(process.argv[2]);
