// nhlib-fns.mjs — port of hell_tweaks() from dat/nhlib.lua.
//
// GENERATED by tools/lua-port-gen/lua2des.mjs. Regenerate rather than
// hand-edit; the call stream is re-checked against the .lua by
// test/lua-port-scripts.test.mjs on every run.
//
// WHY THIS IS NOT A LEVEL SCRIPT PORT. nhlib.lua is loaded into every
// lua_State nhl_init() builds, so its functions are in scope for every
// script. hell_tweaks() is the one a *ported* script still has to be able to
// call: seven Gehennom levels end with it, and it is 60 lines of selection
// algebra with its own percent() and math.random() draws. Porting it once
// here is what lets those seven be ports at all.
//
// The api arrives as a parameter rather than a destructured signature
// because the function has the .lua's own parameters to carry too.

/** @param {object} api @returns {void} */
export default function hell_tweaks(api, protected_area) {
    const { des, selection, percent, math, u, nhc } = api;

    const liquid = 'L';
    const ground = '.';
    const n_prot = selection.numpoints(protected_area);
    const prot = selection.negate(protected_area);

    // random pools
    if (percent(20 + u.depth)) {
        let pools = selection.new();
        const maxpools = 5 + math.random(u.depth);
        for (let i = 1; i <= maxpools; i++) {
            selection.set(pools);
        }
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'west'));
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'north'));
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'random'));

        pools = selection.band(pools, prot);

        if (percent(80)) {
            const poolground = selection.band(selection.grow(selection.clone(pools), 'all'), prot);
            const pval = math.random(1, 8) * 10;
            des.terrain(selection.percentage(poolground, pval), ground);
        }
        des.terrain(pools, liquid);
    }

    // river
    if (percent(50)) {
        let allrivers = selection.new();
        const reqpts = ((nhc.COLNO * nhc.ROWNO) - n_prot) / 12;
        // # of lava pools required
        let rpts = 0;
        let rivertries = 0;

        do {
            const floor = selection.match(ground);
            const a = selection.rndcoord(floor);
            const b = selection.rndcoord(floor);
            let lavariver = selection.randline(selection.new(), a.x, a.y, b.x, b.y, 10);

            if (percent(50)) {
                lavariver = selection.grow(lavariver, 'north');
            }
            if (percent(50)) {
                lavariver = selection.grow(lavariver, 'west');
            }
            allrivers = selection.bor(allrivers, lavariver);
            allrivers = selection.band(allrivers, prot);

            rpts = selection.numpoints(allrivers);
            rivertries = rivertries + 1;
        } while (!((rpts > reqpts) || (rivertries > 7)));

        if (percent(60)) {
            const prc = 10 * math.random(1, 6);
            let riverbanks = selection.grow(allrivers);
            riverbanks = selection.band(riverbanks, prot);
            des.terrain(selection.percentage(riverbanks, prc), ground);
        }

        des.terrain(allrivers, liquid);
    }

    // replacing some walls with boulders
    if (percent(20)) {
        const amount = 3 * math.random(1, 8);
        let bwalls = selection.bor(
            selection.percentage(selection.match(`.w.`), amount),
            selection.percentage(selection.match('.\nw\n.'), amount)
        );
        bwalls = selection.band(bwalls, prot);
        selection.iterate(bwalls, (x, y) => {
            des.terrain(x, y, '.');
            des.object('boulder', x, y);
        });
    }

    // replacing some walls with iron bars
    if (percent(20)) {
        const amount = 3 * math.random(1, 8);
        let fwalls = selection.bor(
            selection.percentage(selection.match(`.w.`), amount),
            selection.percentage(selection.match('.\nw\n.'), amount)
        );
        fwalls = selection.band(selection.band(selection.grow(fwalls), selection.match('w')), prot);
        des.terrain(fwalls, 'F');
    }
}
