// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/end.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/end.c
// Input sha256: 9190178742d65ea579645cfa365573a1c3f59cff7a5504856631c42a0c169296
// Transpiler: tools/c2js c2js emit v1+batch

import { i16, schar, uchar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import * as FLD from './nhfield.js';
import { Is_container, SchroedingersBox, canspotmon, has_ebones, has_mgivenname, has_oname, is_vampshifter, ismnum, min } from './nhmacrofn.js';
import { d_at, rn2_at } from './nhrng.js';
import { Blind, Hallucination, Lifesaved, Sick, Ugender, Upolyd, clear_nhwindow, create_nhwindow, destroy_nhwindow, discover, display_nhwindow, exit_nhwindows, mark_synch, outrip, putstr, raw_print, tutorial_dnum, wait_synch, wizard } from './nhprop.js';
import { WIN_INVEN, WIN_MAP, WIN_MESSAGE, WIN_STATUS, disclosure_options, disp, flags, ga, gb, gd, gg, gh, gi, gk, gm, gn, gt, gu, gv, gy, iflags, program_state, svc, svd, svk, svl, svm, svp, u, uamul, uchain, urealtime, ynchars, ynqchars } from './decl.js';
import { dump_close_log, dump_forward_putstr, dump_open_log, windowprocs } from './windows.js';
import { canseemon, curs_on_u, sensemon } from './display.js';
import { money_cnt, nomul } from './hack.js';
import { cmdq_add_ec, isok, paranoid_query, yn_function } from './cmd.js';
import { schedule_goto } from './do.js';
import { soundprocs } from './sounds.js';
import { sethanguphandler } from './unixmain.js';
import { mons } from './monst.js';
import { You, You_feel, Your, impossible, livelog_printf, pline, pline_The, raw_printf } from './pline.js';
import { monhealthdescr } from './pager.js';
import { eos, strstri, upstart } from './hacklib.js';
import { Mgender, Monnam, free_oname, m_monnam, mon_nam, pmname } from './do_name.js';
import { an, doname_with_price, the, the_unique_obj, the_unique_pm, thesimpleoname, xname } from './objnam.js';
import { shkname, shkname_is_pname } from './shknam.js';
import { unstuck, zombie_maker } from './mon.js';
import { sysopt } from './sys.js';
import { clearlocks, debugcore, paniclog, set_error_savefile } from './files.js';
import { dosave0, freedynamicdata } from './save.js';
import { carrying, currency, display_inventory, free_pickinv_cache, perm_invent_toggled, set_cknown_lknown, sortloot, stackobj, unsortloot, update_inventory, useup } from './invent.js';
import { count_achievements, enlightenment, list_genocided, list_vanquished, record_achievement, show_conduct } from './insight.js';
import { In_quest, deepest_lev_reached, depth, dunlev, on_level, show_overview, single_level_branch } from './dungeon.js';
import { acurr, adjattrib, minuhpmax, setuhpmax } from './attrib.js';
import { init_uhunger } from './eat.js';
import { make_sick, peffects, set_itimeout } from './potion.js';
import { force_launch_placement, launch_in_progress, reset_utrap } from './trap.js';
import { endmultishot } from './dothrow.js';
import { expels } from './mhitu.js';
import { sticks } from './mondata.js';
import { inven_inuse } from './restore.js';
import { accessible } from './monmove.js';
import { bless, mk_named_object, mksobj, place_object } from './mkobj.js';
import { lift_covet_and_placebc } from './ball.js';
import { arti_cost, artiname } from './artifact.js';
import { discover_object } from './o_init.js';
import { obj_descr, objects } from './objects.js';
import { finish_paybill, obfree, paybill } from './shk.js';
import { wiz_makemap } from './wizcmds.js';
import { bot } from './botl.js';
import { formatkiller, topten } from './topten.js';
import { getnow, midnight, night } from './calendar.js';
import { timet_delta } from './allmain.js';
import { can_make_bones, savebones } from './bones.js';
import { hidden_gold, paygd } from './vault.js';
import { clearpriests } from './priest.js';
import { observe_quantum_cat } from './pickup.js';
import { keepdogs } from './dog.js';
import { Strlen_ } from './strutil.js';
import { make_grave } from './engrave.js';
import { Goodbye } from './role.js';
import { adj_lev } from './makemon.js';
import { nomux_capture_write_input_boundary } from './termcap.js';
import { l_nhcore_call, l_nhcore_done } from './nhlua.js';
import { alloc } from './alloc.js';
import { sfi_kinfo, sfo_kinfo } from './sfbase.js';
import { NH_panictrace_gdb, NH_panictrace_libc, panictrace_setsignals, submit_web_report } from './report.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $NHFILE_mode = FLD.NHFILE_mode, $Race_mnum = FLD.Race_mnum, $Race_mummynum = FLD.Race_mummynum,
    $Race_zombienum = FLD.Race_zombienum, $RoleName_f = FLD.RoleName_f, $Role_mnum = FLD.Role_mnum,
    $context_info_mon_moving = FLD.context_info_mon_moving, $context_info_move = FLD.context_info_move,
    $d_level_dlevel = FLD.d_level_dlevel, $dgn_topology_d_astral_level = FLD.dgn_topology_d_astral_level,
    $dgn_topology_d_tutorial_dnum = FLD.dgn_topology_d_tutorial_dnum,
    $display_hints_botlx = FLD.display_hints_botlx, $display_hints_time_botl = FLD.display_hints_time_botl,
    $flag_beginner = FLD.flag_beginner, $flag_debug = FLD.flag_debug,
    $flag_end_disclose = FLD.flag_end_disclose, $flag_explore = FLD.flag_explore,
    $flag_female = FLD.flag_female, $flag_ignintr = FLD.flag_ignintr,
    $flag_paranoia_bits = FLD.flag_paranoia_bits, $flag_sortloot = FLD.flag_sortloot,
    $flag_sortpack = FLD.flag_sortpack, $flag_tombstone = FLD.flag_tombstone,
    $instance_flags_at_midnight = FLD.instance_flags_at_midnight,
    $instance_flags_at_night = FLD.instance_flags_at_night,
    $instance_flags_debug_fuzzer = FLD.instance_flags_debug_fuzzer,
    $instance_flags_force_invmenu = FLD.instance_flags_force_invmenu,
    $instance_flags_in_dumplog = FLD.instance_flags_in_dumplog,
    $instance_flags_last_msg = FLD.instance_flags_last_msg,
    $instance_flags_perm_invent = FLD.instance_flags_perm_invent,
    $instance_flags_toptenwin = FLD.instance_flags_toptenwin,
    $instance_flags_vision_inited = FLD.instance_flags_vision_inited,
    $instance_flags_window_inited = FLD.instance_flags_window_inited,
    $instance_globals_a_amulets = FLD.instance_globals_a_amulets,
    $instance_globals_b_bot_disabled = FLD.instance_globals_b_bot_disabled,
    $instance_globals_d_done_money = FLD.instance_globals_d_done_money,
    $instance_globals_d_done_seq = FLD.instance_globals_d_done_seq,
    $instance_globals_g_gems = FLD.instance_globals_g_gems,
    $instance_globals_h_hero_seq = FLD.instance_globals_h_hero_seq,
    $instance_globals_i_invent = FLD.instance_globals_i_invent,
    $instance_globals_k_kickedobj = FLD.instance_globals_k_kickedobj,
    $instance_globals_m_multi = FLD.instance_globals_m_multi,
    $instance_globals_m_multi_reason = FLD.instance_globals_m_multi_reason,
    $instance_globals_m_multireasonbuf = FLD.instance_globals_m_multireasonbuf,
    $instance_globals_m_mydogs = FLD.instance_globals_m_mydogs,
    $instance_globals_n_nomovemsg = FLD.instance_globals_n_nomovemsg,
    $instance_globals_saved_d_dungeon_topology = FLD.instance_globals_saved_d_dungeon_topology,
    $instance_globals_saved_l_level = FLD.instance_globals_saved_l_level,
    $instance_globals_saved_m_moves = FLD.instance_globals_saved_m_moves,
    $instance_globals_saved_m_mvitals = FLD.instance_globals_saved_m_mvitals,
    $instance_globals_t_thrownobj = FLD.instance_globals_t_thrownobj,
    $instance_globals_u_urace = FLD.instance_globals_u_urace,
    $instance_globals_u_urole = FLD.instance_globals_u_urole,
    $instance_globals_v_valuables = FLD.instance_globals_v_valuables,
    $instance_globals_v_viz_array = FLD.instance_globals_v_viz_array,
    $instance_globals_y_youmonst = FLD.instance_globals_y_youmonst, $kinfo_format = FLD.kinfo_format,
    $kinfo_id = FLD.kinfo_id, $kinfo_name = FLD.kinfo_name, $mextra_ebones = FLD.mextra_ebones,
    $monst_cham = FLD.monst_cham, $monst_data = FLD.monst_data, $monst_female = FLD.monst_female,
    $monst_isminion = FLD.monst_isminion, $monst_ispriest = FLD.monst_ispriest,
    $monst_isshk = FLD.monst_isshk, $monst_m_ap_type = FLD.monst_m_ap_type, $monst_m_id = FLD.monst_m_id,
    $monst_mappearance = FLD.monst_mappearance, $monst_mextra = FLD.monst_mextra, $monst_mhp = FLD.monst_mhp,
    $monst_minvis = FLD.monst_minvis, $monst_mtame = FLD.monst_mtame, $mvitals_mvflags = FLD.mvitals_mvflags,
    $obj_bknown = FLD.obj_bknown, $obj_cknown = FLD.obj_cknown, $obj_cobj = FLD.obj_cobj,
    $obj_dknown = FLD.obj_dknown, $obj_known = FLD.obj_known, $obj_lknown = FLD.obj_lknown,
    $obj_oartifact = FLD.obj_oartifact, $obj_oclass = FLD.obj_oclass, $obj_oextra = FLD.obj_oextra,
    $obj_otyp = FLD.obj_otyp, $obj_quan = FLD.obj_quan, $obj_rknown = FLD.obj_rknown, $obj_spe = FLD.obj_spe,
    $obj_where = FLD.obj_where, $objclass_oc_class = FLD.objclass_oc_class,
    $objclass_oc_cost = FLD.objclass_oc_cost, $permonst_geno = FLD.permonst_geno,
    $permonst_mflags2 = FLD.permonst_mflags2, $permonst_mlet = FLD.permonst_mlet,
    $prop_blocked = FLD.prop_blocked, $prop_intrinsic = FLD.prop_intrinsic, $rm_flags = FLD.rm_flags,
    $rm_typ = FLD.rm_typ, $sinfo_done_hup = FLD.sinfo_done_hup, $sinfo_exiting = FLD.sinfo_exiting,
    $sinfo_in_moveloop = FLD.sinfo_in_moveloop, $sinfo_panicking = FLD.sinfo_panicking,
    $sinfo_something_worth_saving = FLD.sinfo_something_worth_saving, $sinfo_stopprint = FLD.sinfo_stopprint,
    $sizeof_dungeon = FLD.sizeof_dungeon, $sizeof_mvitals = FLD.sizeof_mvitals,
    $sizeof_objclass = FLD.sizeof_objclass, $sizeof_objdescr = FLD.sizeof_objdescr,
    $sizeof_permonst = FLD.sizeof_permonst, $sizeof_prop = FLD.sizeof_prop, $sizeof_rm = FLD.sizeof_rm,
    $sizeof_rm_x21 = FLD.sizeof_rm_x21, $sizeof_valuable_data = FLD.sizeof_valuable_data,
    $sound_procs_sound_exit_nhsound = FLD.sound_procs_sound_exit_nhsound,
    $sysopt_s_fmtd_wizard_list = FLD.sysopt_s_fmtd_wizard_list,
    $sysopt_s_panictrace_gdb = FLD.sysopt_s_panictrace_gdb,
    $sysopt_s_panictrace_libc = FLD.sysopt_s_panictrace_libc, $sysopt_s_recover = FLD.sysopt_s_recover,
    $u_realtime_finish_time = FLD.u_realtime_finish_time,
    $u_realtime_start_timing = FLD.u_realtime_start_timing, $u_roleplay_nudist = FLD.u_roleplay_nudist,
    $val_list_size = FLD.val_list_size, $valuable_data_typ = FLD.valuable_data_typ,
    $window_procs_win_clear_nhwindow = FLD.window_procs_win_clear_nhwindow,
    $window_procs_win_create_nhwindow = FLD.window_procs_win_create_nhwindow,
    $window_procs_win_destroy_nhwindow = FLD.window_procs_win_destroy_nhwindow,
    $window_procs_win_display_nhwindow = FLD.window_procs_win_display_nhwindow,
    $window_procs_win_exit_nhwindows = FLD.window_procs_win_exit_nhwindows,
    $window_procs_win_mark_synch = FLD.window_procs_win_mark_synch,
    $window_procs_win_outrip = FLD.window_procs_win_outrip,
    $window_procs_win_putstr = FLD.window_procs_win_putstr,
    $window_procs_win_raw_print = FLD.window_procs_win_raw_print,
    $window_procs_win_wait_synch = FLD.window_procs_win_wait_synch, $you_dx = FLD.you_dx,
    $you_dy = FLD.you_dy, $you_mfemale = FLD.you_mfemale, $you_mh = FLD.you_mh, $you_mhmax = FLD.you_mhmax,
    $you_uachieved = FLD.you_uachieved, $you_ualign = FLD.you_ualign, $you_ualignbase = FLD.you_ualignbase,
    $you_ucamefrom = FLD.you_ucamefrom, $you_ugrave_arise = FLD.you_ugrave_arise, $you_uhave = FLD.you_uhave,
    $you_uhp = FLD.you_uhp, $you_uhpmax = FLD.you_uhpmax, $you_uhunger = FLD.you_uhunger,
    $you_uinvulnerable = FLD.you_uinvulnerable, $you_ulevel = FLD.you_ulevel, $you_ulycn = FLD.you_ulycn,
    $you_umoney0 = FLD.you_umoney0, $you_umonnum = FLD.you_umonnum, $you_umonster = FLD.you_umonster,
    $you_umortality = FLD.you_umortality, $you_uprops = FLD.you_uprops, $you_urexp = FLD.you_urexp,
    $you_uroleplay = FLD.you_uroleplay, $you_usleep = FLD.you_usleep, $you_ustuck = FLD.you_ustuck,
    $you_uswallow = FLD.you_uswallow, $you_utrap = FLD.you_utrap, $you_utraptype = FLD.you_utraptype,
    $you_uy = FLD.you_uy, $you_uz = FLD.you_uz;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_died = cptr.lit("died");
const __s_choked = cptr.lit("choked");
const __s_poisoned = cptr.lit("poisoned");
const __s_starvation = cptr.lit("starvation");
const __s_drowning = cptr.lit("drowning");
const __s_burning = cptr.lit("burning");
const __s_dissolving_under_the_heat_and_pressure = cptr.lit("dissolving under the heat and pressure");
const __s_crushed = cptr.lit("crushed");
const __s_turned_to_stone = cptr.lit("turned to stone");
const __s_turned_into_slime = cptr.lit("turned into slime");
const __s_genocided = cptr.lit("genocided");
const __s_panic = cptr.lit("panic");
const __s_trickery = cptr.lit("trickery");
const __s_quit = cptr.lit("quit");
const __s_escaped = cptr.lit("escaped");
const __s_ascended = cptr.lit("ascended");
const __s_were_poisoned = cptr.lit("were poisoned");
const __s_starved = cptr.lit("starved");
const __s_drowned = cptr.lit("drowned");
const __s_burned = cptr.lit("burned");
const __s_dissolved_in_the_lava = cptr.lit("dissolved in the lava");
const __s_were_crushed = cptr.lit("were crushed");
const __s_were_genocided = cptr.lit("were genocided");
const __s_panicked = cptr.lit("panicked");
const __s_were_tricked = cptr.lit("were tricked");
const __s_switch_from_the_tutorial_back_to = cptr.lit("Switch from the tutorial back to regular play?");
const __s_really_quit_without_saving = cptr.lit("Really quit without saving?");
const __s_resuming_regular_play = cptr.lit("Resuming regular play.");
const __s_dump_core = cptr.lit("Dump core?");
const __s_done2 = cptr.lit("done2");
const __s_turn_to_stone = cptr.lit("turn to stone...");
const __s_die = cptr.lit("die...");
const __s_the = cptr.lit("the ");
const __s_invisible = cptr.lit("invisible ");
const __s_hallucinogen_distorted = cptr.lit("hallucinogen-distorted ");
const __s_vampire = cptr.lit("vampire");
const __s_vampire_bat = cptr.lit("vampire bat");
const __s_bat = cptr.lit("bat");
const __s_the_s = cptr.lit("the %s");
const __s_s_in_s_form = cptr.lit("%s in %s form");
const __s_s_disguised_as_s = cptr.lit("%s disguised as %s");
const __s_s_imitating_s = cptr.lit("%s imitating %s");
const __s_ghost = cptr.lit("ghost");
const __s_of_s = cptr.lit(" of %s");
const __s_empty = cptr.lit("");
const __s_ms = cptr.lit("Ms. ");
const __s_mr = cptr.lit("Mr. ");
const __s_s_s_the_shopkeeper = cptr.lit("%s%s, the shopkeeper");
const __s_s_s = cptr.lit(" %s %s");
const __s_of = cptr.lit("of");
const __s_called = cptr.lit("called");
const __s_u_c = cptr.lit("%u:%c");
const __s_getting_stoned = cptr.lit("getting stoned");
const __s_fainted_from_lack_of_food = cptr.lit("fainted from lack of food");
const __s_fainted = cptr.lit("fainted");
const __s_oops = cptr.lit("\r\nOops...");
const __s_postgame_wrapup_disrupted = cptr.lit("Postgame wrapup disrupted.");
const __s_program_initialization_has_failed = cptr.lit("Program initialization has failed.");
const __s_suddenly_the_dungeon_collapses = cptr.lit("Suddenly, the dungeon collapses.");
const __s_dot = cptr.lit(".");
const __s_and_it_may_be_possible_to_rebuild = cptr.lit("\nand it may be possible to rebuild.");
const __s_to_report_this_error_s_s = cptr.lit("To report this error, %s%s");
const __s_to_report_this_error_contact_s_s = cptr.lit("To report this error, contact %s%s");
const __s_report_error_to_s_s = cptr.lit("Report error to \"%s\"%s");
const __s_wizard = cptr.lit("wizard");
const __s_pct_s = cptr.lit("%s");
const __s_should_query_disclose_option_bad = cptr.lit("should_query_disclose_option: bad disclosure index %d %c");
const __s_should_query_disclose_option_bad__2 = cptr.lit("should_query_disclose_option: bad category %c");
const __s_do_you_want_to_see_what_you_had_when = cptr.lit("Do you want to see what you had when you %s?");
const __s_do_you_want_your_possessions_identified = cptr.lit("Do you want your possessions identified?");
const __s_do_you_want_to_see_your_attributes = cptr.lit("Do you want to see your attributes?");
const __s_do_you_want_to_see_your_conduct_s = cptr.lit("Do you want to see your conduct%s?");
const __s_and_achievements = cptr.lit(" and achievements");
const __s_do_you_want_to_see_the_dungeon_overview = cptr.lit("Do you want to see the dungeon overview?");
const __s_you_survived_that_attempt_on_your_life = cptr.lit("You survived that attempt on your life.");
const __s_being_toyed_with_by_fate = cptr.lit("being toyed with by Fate");
const __s_attempting_to_cheat_death = cptr.lit("attempting to cheat Death");
const __s_release_s = cptr.lit("release %s.");
const __s_s_releases_you = cptr.lit("%s releases you.");
const __s_s_s_worth_ld_s_and_ld_points = cptr.lit("%s%s (worth %ld %s and %ld points)");
const __s_the__2 = cptr.lit("The ");
const __s_end_c = cptr.lit("end.c");
const __s_fuzzer_savelife = cptr.lit("fuzzer_savelife");
const __s_but_wait = cptr.lit("But wait...");
const __s_medallion_s = cptr.lit("medallion %s!");
const __s_begins_to_glow = cptr.lit("begins to glow");
const __s_feels_warm = cptr.lit("feels warm");
const __s_vomit = cptr.lit("vomit ...");
const __s_much_better = cptr.lit("much better!");
const __s_medallion_crumbles_to_dust = cptr.lit("medallion crumbles to dust!");
const __s_unfortunately_you_are_still_genocided = cptr.lit("Unfortunately you are still genocided...");
const __s_averted_death_s = cptr.lit("averted death (%s)");
const __s_die__2 = cptr.lit("Die?");
const __s_ok_so_you_don_t_s = cptr.lit("OK, so you don't %s.");
const __s_choke = cptr.lit("choke");
const __s_die__3 = cptr.lit("die");
const __s_do_not_pass_go_do_not_collect_200_s = cptr.lit("Do not pass Go.  Do not collect 200 %s.");
const __s_quit_while_already_on_charon_s_boat = cptr.lit("quit while already on Charon's boat");
const __s_none = cptr.lit("none");
const __s_pct_s_comma_sp = cptr.lit("%s, ");
const __s_really_done = cptr.lit("really_done");
const __s_s_as_s = cptr.lit("%s as %s...");
const __s_body_rises_from_the_dead = cptr.lit("body rises from the dead");
const __s_revenant_persists = cptr.lit("revenant persists");
const __s_save_bones = cptr.lit("Save bones?");
const __s_with_the_amulet = cptr.lit(" (with the Amulet)");
const __s_in_celestial_disgrace = cptr.lit(" (in celestial disgrace)");
const __s_with_a_fake_amulet = cptr.lit(" (with a fake Amulet)");
const __s_s_s_the_s = cptr.lit("%s %s the %s...");
const __s_demigoddess = cptr.lit("Demigoddess");
const __s_demigod = cptr.lit("Demigod");
const __s_you = cptr.lit("You");
const __s_and_s = cptr.lit(" and %s");
const __s_and_schroedinger_s_cat = cptr.lit(" and Schroedinger's cat");
const __s_sp = cptr.lit(" ");
const __s_s_with_ld_point_s = cptr.lit("%s with %ld point%s,");
const __s_went_to_your_reward = cptr.lit("went to your reward");
const __s_escaped_from_the_dungeon = cptr.lit("escaped from the dungeon");
const __s_s = cptr.lit("s");
const __s_8ld_s_worth_ld_s = cptr.lit("%8ld %s (worth %ld %s),");
const __s_8ld_worthless_piece_s_of_colored_glass = cptr.lit("%8ld worthless piece%s of colored glass,");
const __s_you_s_beyond_the_confines_of_the_dungeon = cptr.lit("You %s beyond the confines of the dungeon");
const __s_passed_away = cptr.lit("passed away");
const __s_the_astral_plane = cptr.lit("The Astral Plane");
const __s_you_s_in_s = cptr.lit("You %s in %s");
const __s_on_dungeon_level_d = cptr.lit(" on dungeon level %d");
const __s_with_ld_point_s = cptr.lit(" with %ld point%s,");
const __s_and_ld_piece_s_of_gold_after_ld_move_s = cptr.lit("and %ld piece%s of gold, after %ld move%s.");
const __s_you_were_level_d_with_a_maximum_of_d = cptr.lit("You were level %d with a maximum of %d hit point%s when you %s.");
const __s_contents_of_s = cptr.lit("Contents of %s:");
const __s_schroedinger_s_cat = cptr.lit("Schroedinger's cat!");
const __s_s_is_empty = cptr.lit("%s is empty.");
const __s_dealloc_killer_d_not_on_list = cptr.lit("dealloc_killer (#%d) not on list");
const __s_freed_delayed_killer_d = cptr.lit("freed delayed killer #%d");
const __s_kinfo = cptr.lit("kinfo");
const __s_no_words_in_list = cptr.lit("no words in list");
const __s_comma_sp = cptr.lit(", ");
const __s_or = cptr.lit("or ");
const __s_panic__2 = cptr.lit("Panic");

/** C ref: end.c:45 — char *[16] */
const deaths = cptr.alloc(16 * 8);
cptr.stPtro(deaths, 0, __s_died);
cptr.stPtro(deaths, 8, __s_choked);
cptr.stPtro(deaths, 16, __s_poisoned);
cptr.stPtro(deaths, 24, __s_starvation);
cptr.stPtro(deaths, 32, __s_drowning);
cptr.stPtro(deaths, 40, __s_burning);
cptr.stPtro(deaths, 48, __s_dissolving_under_the_heat_and_pressure);
cptr.stPtro(deaths, 56, __s_crushed);
cptr.stPtro(deaths, 64, __s_turned_to_stone);
cptr.stPtro(deaths, 72, __s_turned_into_slime);
cptr.stPtro(deaths, 80, __s_genocided);
cptr.stPtro(deaths, 88, __s_panic);
cptr.stPtro(deaths, 96, __s_trickery);
cptr.stPtro(deaths, 104, __s_quit);
cptr.stPtro(deaths, 112, __s_escaped);
cptr.stPtro(deaths, 120, __s_ascended);

/** C ref: end.c:53 — char *[16] */
const ends = cptr.alloc(16 * 8);
cptr.stPtro(ends, 0, __s_died);
cptr.stPtro(ends, 8, __s_choked);
cptr.stPtro(ends, 16, __s_were_poisoned);
cptr.stPtro(ends, 24, __s_starved);
cptr.stPtro(ends, 32, __s_drowned);
cptr.stPtro(ends, 40, __s_burned);
cptr.stPtro(ends, 48, __s_dissolved_in_the_lava);
cptr.stPtro(ends, 56, __s_were_crushed);
cptr.stPtro(ends, 64, __s_turned_to_stone);
cptr.stPtro(ends, 72, __s_turned_into_slime);
cptr.stPtro(ends, 80, __s_were_genocided);
cptr.stPtro(ends, 88, __s_panicked);
cptr.stPtro(ends, 96, __s_were_tricked);
cptr.stPtro(ends, 104, __s_quit);
cptr.stPtro(ends, 112, __s_escaped);
cptr.stPtro(ends, 120, __s_ascended);

/** C ref: end.c:64 — signed char */
let Schroedingers_cat = 0;

/** C ref: end.c:69 — @param {CInt} sig_unused */
export function* done1(sig_unused) {
    void signal(2, 1);
    cptr.st1o(iflags, $instance_flags_debug_fuzzer, NHC.fuzzer_off);
    if (cptr.ld1so(flags, $flag_ignintr)) {
        void signal(2, done1);
        (yield* Y.icall(clear_nhwindow()(WIN_MESSAGE.v)));
        (yield* curs_on_u());
        (yield* Y.icall(wait_synch()()));
        if (cptr.ldI64o(gm, $instance_globals_m_multi) > 0n)
            nomul(0);
    } else {
        void (yield* done2());
    }
}

/** C ref: end.c:91 @returns {CInt} */
export function* done2() {
    let abandon_tutorial = 0;
    if ((cptr.ldI16((cptr.add(u, $you_uz))) == tutorial_dnum()) && (yield* yn_function(__s_switch_from_the_tutorial_back_to, cptr.decay(ynchars), 110, 1)) == 121)
        abandon_tutorial = 1;
    if (abandon_tutorial || !(yield* paranoid_query(schar((((cptr.ldI32o(flags, $flag_paranoia_bits) & NHM.PARANOID_QUIT) >>> 0) != 0)), __s_really_quit_without_saving))) {
        void signal(2, done1);
        (yield* Y.icall(clear_nhwindow()(WIN_MESSAGE.v)));
        (yield* curs_on_u());
        (yield* Y.icall(wait_synch()()));
        if (cptr.ldI64o(gm, $instance_globals_m_multi) > 0n)
            nomul(0);
        if (cptr.ldI64o(gm, $instance_globals_m_multi) == 0n) {
            cptr.stI32o(u, $you_uinvulnerable, 0);
            cptr.stI64o(u, $you_usleep, 0n);
        }
        if (abandon_tutorial)
            (yield* schedule_goto(cptr.add(u, $you_ucamefrom), NHC.UTOTYPE_ATSTAIRS, __s_resuming_regular_play, null));
        return NHM.ECMD_OK;
    }
    if (wizard()) {
        let c;
        c = (yield* yn_function(__s_dump_core, cptr.decay(ynqchars), 113, 1));
        if (c == 121) {
            void signal(2, done1);
            if (cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))
                (yield* Y.icall((cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))(__s_done2)));
            (yield* Y.icall(exit_nhwindows()(null)));
            (yield* NH_abort(null));
        } else if (c == 113)
            (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    }
    (yield* done(NHC.QUIT));
    return NHM.ECMD_OK;
}

/** C ref: end.c:155 — @param {CInt} sig_unused */
function done_intr(sig_unused) {
    (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    void signal(2, 1);
    void signal(3, 1);
    return;
}

/** C ref: end.c:170 — @param {CInt} sig */
function done_hangup(sig) {
    (cptr.stI32o(program_state, $sinfo_done_hup, cptr.ldI32o(program_state, $sinfo_done_hup) + 1)) - (1);
    sethanguphandler(1);
    done_intr(sig);
    return;
}

/** C ref: end.c:186 — @param {CPtr<struct monst>} mtmp @param {CInt} how */
export function* done_in_by(mtmp, how) {
    let buf = new Uint8Array(256);
    let mptr = cptr.ldPtro(mtmp, $monst_data);
    let champtr = ismnum(cptr.ldI16o(mtmp, $monst_cham)) ? cptr.add(mons, cptr.ldI16o(mtmp, $monst_cham), $sizeof_permonst) : mptr;
    let distorted = schar((Hallucination() && canspotmon(mtmp) ? 1 : 0));
    let mimicker = schar(((cptr.ld1uo((mtmp), $monst_m_ap_type) & NHM.M_AP_TYPMASK) == NHC.M_AP_MONSTER));
    let imitator = schar((!cptr.eq(mptr, champtr) || mimicker ? 1 : 0));
    (yield* You((how == NHC.STONING) ? __s_turn_to_stone : __s_die));
    (yield* Y.icall(mark_synch()()));
    cptr.st1o(cptr.decay(buf), 0, 0, 1);
    cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY_AN);
    if ((cptr.ldU16o(mptr, $permonst_geno) & NHM.G_UNIQ) != 0 && !(imitator && !mimicker) && !(cptr.eq(mptr, cptr.add(mons, NHC.PM_HIGH_CLERIC, $sizeof_permonst)) && !(cptr.ldI32o(mtmp, $monst_ispriest) & 1))) {
        if (!((cptr.ldU64o((mptr), $permonst_mflags2) & 524288n) != 0n))
            void cptr.strcat(cptr.decay(buf), __s_the);
        cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY);
    }
    if (cptr.eq(mptr, cptr.add(mons, NHC.PM_GHOST, $sizeof_permonst)) && has_mgivenname(mtmp)) {
        void cptr.strcat(cptr.decay(buf), __s_the);
        cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY);
    }
    void monhealthdescr(mtmp, 1, eos(cptr.decay(buf)));
    if ((cptr.ldI32o(mtmp, $monst_minvis) & 1))
        void cptr.strcat(cptr.decay(buf), __s_invisible);
    if (distorted)
        void cptr.strcat(cptr.decay(buf), __s_hallucinogen_distorted);
    if (imitator) {
        let shape = new Uint8Array(256);
        let realnm = pmname(champtr, Mgender(mtmp));
        let fakenm = pmname(mptr, Mgender(mtmp));
        let alt = schar(is_vampshifter(mtmp));
        if (mimicker) {
            mptr = cptr.add(mons, cptr.ldI32o(mtmp, $monst_mappearance), $sizeof_permonst);
            fakenm = pmname(mptr, Mgender(mtmp));
        } else if (alt && (yield* strstri(realnm, __s_vampire)) && !strcmp(fakenm, __s_vampire_bat)) {
            fakenm = __s_bat;
        }
        if (alt || ((cptr.ldU64o((mptr), $permonst_mflags2) & 524288n) != 0n))
            void cptr.strcpy(cptr.decay(shape), fakenm);
        else if (the_unique_pm(mptr))
            void cptr.sprintf(cptr.decay(shape), __s_the_s, fakenm);
        else
            void cptr.strcpy(cptr.decay(shape), (yield* an(fakenm)));
        void cptr.sprintf(eos(cptr.decay(buf)), alt ? __s_s_in_s_form : (mimicker ? __s_s_disguised_as_s : __s_s_imitating_s), realnm, cptr.decay(shape));
        mptr = cptr.ldPtro(mtmp, $monst_data);
    } else if (cptr.eq(mptr, cptr.add(mons, NHC.PM_GHOST, $sizeof_permonst))) {
        void cptr.strcat(cptr.decay(buf), __s_ghost);
        if (has_mgivenname(mtmp))
            void cptr.sprintf(eos(cptr.decay(buf)), __s_of_s, (cptr.ldPtr(cptr.ldPtro((mtmp), $monst_mextra))));
    } else if ((cptr.ldI32o(mtmp, $monst_isshk) & 1)) {
        let shknm = (yield* shkname(mtmp));
        let honorific = shkname_is_pname(mtmp) ? __s_empty : ((cptr.ldI32o(mtmp, $monst_female) & 1) | 0 ? __s_ms : __s_mr);
        void cptr.sprintf(eos(cptr.decay(buf)), __s_s_s_the_shopkeeper, honorific, shknm);
        cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY);
    } else if ((cptr.ldI32o(mtmp, $monst_ispriest) & 1) | 0 || (cptr.ldI32o(mtmp, $monst_isminion) & 1) | 0) {
        void cptr.strcat(cptr.decay(buf), (yield* m_monnam(mtmp)));
    } else {
        void cptr.strcat(cptr.decay(buf), pmname(mptr, Mgender(mtmp)));
        if (has_mgivenname(mtmp)) {
            void cptr.sprintf(eos(cptr.decay(buf)), __s_s_s, has_ebones(mtmp) ? __s_of : __s_called, (cptr.ldPtr(cptr.ldPtro((mtmp), $monst_mextra))));
        }
    }
    void cptr.strcpy(cptr.add(svk, $kinfo_name), cptr.decay(buf));
    if (cptr.ldPtro(gm, $instance_globals_m_multi_reason) && cptr.cmp(cptr.ldPtro(gm, $instance_globals_m_multi_reason), cptr.add(gm, $instance_globals_m_multireasonbuf)) > 0 && cptr.cmp(cptr.ldPtro(gm, $instance_globals_m_multi_reason), cptr.add(cptr.add(cptr.add(gm, $instance_globals_m_multireasonbuf), 128n), -(1))) < 0) {
        let reasondummy = cptr.box(0);
        let p;
        let reasonmid = cptr.box(0);
        if (sscanf(cptr.add(gm, $instance_globals_m_multireasonbuf), __s_u_c, reasonmid, reasondummy) == 2 && cptr.ldI32o(mtmp, $monst_m_id) == reasonmid.v) {
            if ((p = cptr.strchr(cptr.add(gm, $instance_globals_m_multireasonbuf), 32)) !== null)
                cptr.st1(p, 0);
        }
    }
    if (cptr.ld1so(mptr, $permonst_mlet) == NHC.S_WRAITH)
        cptr.stI32o(u, $you_ugrave_arise, NHC.PM_WRAITH);
    else if (cptr.ld1so(mptr, $permonst_mlet) == NHC.S_MUMMY && cptr.ldI16o(gu, $instance_globals_u_urace + $Race_mummynum) != NHC.NON_PM)
        cptr.stI32o(u, $you_ugrave_arise, cptr.ldI16o(gu, $instance_globals_u_urace + $Race_mummynum));
    else if (zombie_maker(mtmp) && cptr.ldI16o(gu, $instance_globals_u_urace + $Race_zombienum) != NHC.NON_PM)
        cptr.stI32o(u, $you_ugrave_arise, cptr.ldI16o(gu, $instance_globals_u_urace + $Race_zombienum));
    else if (cptr.ld1so(mptr, $permonst_mlet) == NHC.S_VAMPIRE && (cptr.ldI16o(gu, $instance_globals_u_urace + $Race_mnum) == NHC.PM_HUMAN))
        cptr.stI32o(u, $you_ugrave_arise, NHC.PM_VAMPIRE);
    else if (cptr.eq(mptr, cptr.add(mons, NHC.PM_GHOUL, $sizeof_permonst)))
        cptr.stI32o(u, $you_ugrave_arise, NHC.PM_GHOUL);
    if (cptr.ldI32o(u, $you_ugrave_arise) >= NHC.LOW_PM && (cptr.ld1uo2(svm, cptr.ldI32o(u, $you_ugrave_arise), $sizeof_mvitals, $instance_globals_saved_m_mvitals + $mvitals_mvflags) & NHM.G_GENOD))
        cptr.stI32o(u, $you_ugrave_arise, NHC.NON_PM);
    (yield* done(how));
    return;
}

/** C ref: end.c:350 — struct undefined {  } (memory model v0.5) */

/** C ref: end.c:353 — struct (unnamed struct at end.c:350:14)[2] */
const death_fixups = cptr.alloc(2 * 24);
cptr.stI32o(death_fixups, 0, NHC.STONING);
cptr.stI32o(death_fixups, 4, 1);
cptr.stPtro(death_fixups, 8, __s_getting_stoned);
cptr.stPtro(death_fixups, 16, null);
cptr.stI32o(death_fixups, 24, NHC.STARVING);
cptr.stI32o(death_fixups, 28, 0);
cptr.stPtro(death_fixups, 32, __s_fainted_from_lack_of_food);
cptr.stPtro(death_fixups, 40, __s_fainted);

/** C ref: end.c:367 — @param {CInt} how */
function fixup_death(how) {
    let i;
    if (cptr.ldPtro(gm, $instance_globals_m_multi_reason)) {
        for (i = 0; i < 2; ++i)
            if (cptr.ldI32o(death_fixups, i, 24) == how && !strcmp(cptr.ldPtro2(death_fixups, i, 24, 8), cptr.ldPtro(gm, $instance_globals_m_multi_reason))) {
                if (cptr.ldPtro2(death_fixups, i, 24, 16))
                    cptr.stPtro(gm, $instance_globals_m_multi_reason, cptr.ldPtro2(death_fixups, i, 24, 16));
                else
                    cptr.stPtro(gm, $instance_globals_m_multi_reason, null);
                cptr.st1o2(gm, 0, 1, $instance_globals_m_multireasonbuf, 0);
                if (cptr.ldI32o2(death_fixups, i, 24, 4))
                    cptr.stI64o(gm, $instance_globals_m_multi, 0n);
                break;
            }
    }
}

/** C ref: end.c:395 — @param {CPtr<char>} str */
export function* panic(str, ...__va) {
    let the_args;
    {
        let buf = new Uint8Array(256);
        the_args = cptr.vaList(__va);
        ;
        if ((cptr.stI32o(program_state, $sinfo_panicking, cptr.ldI32o(program_state, $sinfo_panicking) + 1)) - (1))
            (yield* NH_abort(null));
        cptr.st1o(gb, $instance_globals_b_bot_disabled, 1);
        if (cptr.ld1so(iflags, $instance_flags_window_inited)) {
            (yield* Y.icall(raw_print()(__s_oops)));
            (yield* Y.icall(wait_synch()()));
            if (cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))
                (yield* Y.icall((cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))(__s_panic)));
            (yield* Y.icall(exit_nhwindows()(null)));
            cptr.st1o(iflags, $instance_flags_window_inited, 0);
        }
        (yield* Y.icall(raw_print()(cptr.ldI32(program_state) ? __s_postgame_wrapup_disrupted : (!cptr.ldI32o(program_state, $sinfo_something_worth_saving) ? __s_program_initialization_has_failed : __s_suddenly_the_dungeon_collapses))));
        if (!wizard()) {
            let maybe_rebuild = !cptr.ldI32o(program_state, $sinfo_something_worth_saving) ? __s_dot : __s_and_it_may_be_possible_to_rebuild;
            if (cptr.ldPtr(sysopt))
                (yield* raw_printf(__s_to_report_this_error_s_s, cptr.ldPtr(sysopt), maybe_rebuild));
            else if (cptr.ldPtro(sysopt, $sysopt_s_fmtd_wizard_list))
                (yield* raw_printf(__s_to_report_this_error_contact_s_s, cptr.ldPtro(sysopt, $sysopt_s_fmtd_wizard_list), maybe_rebuild));
            else
                (yield* raw_printf(__s_report_error_to_s_s, __s_wizard, maybe_rebuild));
        }
        if (cptr.ldI32o(program_state, $sinfo_something_worth_saving) && !cptr.ld1so(iflags, $instance_flags_debug_fuzzer)) {
            set_error_savefile();
            if ((yield* dosave0())) {
                if (cptr.ldPtro(sysopt, $sysopt_s_recover))
                    (yield* raw_printf(__s_pct_s, cptr.ldPtro(sysopt, $sysopt_s_recover)));
            }
        }
        void cptr.vsnprintf(cptr.decay(buf), 256n, str, the_args);
        (yield* Y.icall(raw_print()(cptr.decay(buf))));
        (yield* paniclog(__s_panic, cptr.decay(buf)));
        (yield* NH_abort(cptr.decay(buf)));
        the_args = null;
    }
    ;
    (yield* really_done(NHC.PANICKED));
}

/** C ref: end.c:477 — @param {CInt} category @param {CPtr<char>} defquery @returns {CInt} */
function* should_query_disclose_option(category, defquery) {
    let idx;
    let disclose;
    let dop;
    cptr.st1(defquery, 110);
    if ((dop = cptr.strchr(cptr.decay(disclosure_options), category)) !== null) {
        idx = Number(BigInt.asIntN(32, (cptr.diff(dop, cptr.decay(disclosure_options)))));
        if (idx < 0 || idx >= NHM.NUM_DISCLOSURE_OPTIONS) {
            (yield* impossible(__s_should_query_disclose_option_bad, idx, category));
            cptr.st1(defquery, 121);
            return 1;
        }
        disclose = cptr.ld1so2(flags, idx, 1, $flag_end_disclose);
        if (disclose == 43) {
            cptr.st1(defquery, 121);
            return 0;
        } else if (disclose == 35) {
            cptr.st1(defquery, 97);
            return 0;
        } else if (disclose == 45) {
            cptr.st1(defquery, 110);
            return 0;
        } else if (disclose == 121) {
            cptr.st1(defquery, 121);
            return 1;
        } else if (disclose == 63) {
            cptr.st1(defquery, 97);
            return 1;
        } else {
            cptr.st1(defquery, 110);
            return 1;
        }
    }
    (yield* impossible(__s_should_query_disclose_option_bad__2, category));
    return 1;
}

/** C ref: end.c:543 — @param {CInt} how @param {CLongLong} when */
function dump_everything(how, when) {
    (void (how));
    (void (when));
}

/** C ref: end.c:620 — @param {CInt} how @param {CInt} taken */
function* disclose(how, taken) {
    let c = 0;
    let defquery = cptr.box(0);
    let qbuf = new Uint8Array(128);
    let ask = 0;
    if (cptr.ldPtro(gi, $instance_globals_i_invent) && !cptr.ldI32o(program_state, $sinfo_stopprint)) {
        if (taken)
            void cptr.sprintf(cptr.decay(qbuf), __s_do_you_want_to_see_what_you_had_when, (how == NHC.QUIT) ? __s_quit : __s_died);
        else
            void cptr.strcpy(cptr.decay(qbuf), __s_do_you_want_your_possessions_identified);
        ask = (yield* should_query_disclose_option(105, defquery));
        c = schar((ask ? (yield* yn_function(cptr.decay(qbuf), cptr.decay(ynqchars), defquery.v, 1)) : defquery.v));
        if (c == 121) {
            cptr.st1o(iflags, $instance_flags_force_invmenu, 0);
            void (yield* display_inventory(null, 1));
            (yield* container_contents(cptr.ldPtro(gi, $instance_globals_i_invent), 1, 1, 0));
        }
        if (c == 113)
            (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    }
    if (!cptr.ldI32o(program_state, $sinfo_stopprint)) {
        ask = (yield* should_query_disclose_option(97, defquery));
        c = schar((ask ? (yield* yn_function(__s_do_you_want_to_see_your_attributes, cptr.decay(ynqchars), defquery.v, 1)) : defquery.v));
        if (c == 121)
            (yield* enlightenment(3, (how >= NHC.PANICKED) ? NHM.ENL_GAMEOVERALIVE : NHM.ENL_GAMEOVERDEAD));
        if (c == 113)
            (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    }
    if (!cptr.ldI32o(program_state, $sinfo_stopprint)) {
        ask = (yield* should_query_disclose_option(118, defquery));
        (yield* list_vanquished(defquery.v, ask));
    }
    if (!cptr.ldI32o(program_state, $sinfo_stopprint)) {
        ask = (yield* should_query_disclose_option(103, defquery));
        (yield* list_genocided(defquery.v, ask));
    }
    if (!cptr.ldI32o(program_state, $sinfo_stopprint)) {
        if ((yield* should_query_disclose_option(99, defquery))) {
            let acnt = count_achievements();
            void cptr.sprintf(cptr.decay(qbuf), __s_do_you_want_to_see_your_conduct_s, (acnt > 0) ? __s_and_achievements : __s_empty);
            c = (yield* yn_function(cptr.decay(qbuf), cptr.decay(ynqchars), defquery.v, 1));
        } else {
            c = defquery.v;
        }
        if (c == 121)
            (yield* show_conduct((how >= NHC.PANICKED) ? 1 : 2));
        if (c == 113)
            (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    }
    if (!cptr.ldI32o(program_state, $sinfo_stopprint)) {
        ask = (yield* should_query_disclose_option(111, defquery));
        c = schar((ask ? (yield* yn_function(__s_do_you_want_to_see_the_dungeon_overview, cptr.decay(ynqchars), defquery.v, 1)) : defquery.v));
        if (c == 121)
            (yield* show_overview((how >= NHC.PANICKED) ? 1 : 2, how));
        if (c == 113)
            (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    }
}

/** C ref: end.c:705 — @param {CInt} how */
function* savelife(how) {
    let uhpmin;
    let givehp = (50 + Math.imul(10, (((acurr(NHC.A_CON)) / 2) | 0))) | 0;
    if (cptr.ldI32o(u, $you_ulevel) < 1)
        cptr.stI32o(u, $you_ulevel, 1);
    uhpmin = minuhpmax(10);
    if (cptr.ldI32o(u, $you_uhpmax) < uhpmin)
        setuhpmax(uhpmin, 1);
    cptr.stI32o(u, $you_uhp, min(cptr.ldI32o(u, $you_uhpmax), givehp));
    if (Upolyd())
        cptr.stI32o(u, $you_mh, min(cptr.ldI32o(u, $you_mhmax), givehp));
    if (cptr.ldI32o(u, $you_uhunger) < 500 || how == NHC.CHOKING) {
        (yield* init_uhunger());
    }
    if ((Sick() & 16777215n) == 1n) {
        (yield* make_sick(0n, null, 0, NHM.SICK_ALL));
    }
    cptr.stPtro(gn, $instance_globals_n_nomovemsg, __s_you_survived_that_attempt_on_your_life);
    cptr.st1o(svc, $context_info_move, 0);
    cptr.stI64o(gm, $instance_globals_m_multi, -1n);
    cptr.stPtro(gm, $instance_globals_m_multi_reason, (cptr.ldI16o(gu, $instance_globals_u_urole + $Role_mnum) == NHC.PM_TOURIST) ? __s_being_toyed_with_by_fate : __s_attempting_to_cheat_death);
    if (cptr.ldI32o(u, $you_utrap) && cptr.ldI32o(u, $you_utraptype) == NHC.TT_LAVA)
        (yield* reset_utrap(0));
    cptr.st1(disp, 1);
    cptr.stI32o(u, $you_ugrave_arise, NHC.NON_PM);
    cptr.stI64o2(u, NHC.UNCHANGING, $sizeof_prop, $you_uprops + $prop_intrinsic, 0n);
    (yield* curs_on_u());
    if (!cptr.ld1so(svc, $context_info_mon_moving))
        (yield* endmultishot(0));
    if ((cptr.ldI32o(u, $you_uswallow) & 1)) {
        (yield* expels(cptr.ldPtro(u, $you_ustuck), cptr.ldPtro(cptr.ldPtro(u, $you_ustuck), $monst_data), 1));
    } else if (cptr.ldPtro(u, $you_ustuck)) {
        if (Upolyd() && sticks(cptr.ldPtro(gy, $instance_globals_y_youmonst + $monst_data)))
            (yield* You(__s_release_s, (yield* mon_nam(cptr.ldPtro(u, $you_ustuck)))));
        else
            (yield* pline(__s_s_releases_you, (yield* Monnam(cptr.ldPtro(u, $you_ustuck)))));
        (yield* unstuck(cptr.ldPtro(u, $you_ustuck)));
    }
}

/** C ref: end.c:764 — @param {CPtr<struct obj>} list */
function get_valuables(list) {
    let obj;
    let i;
    for (obj = list; obj; obj = cptr.ldPtr(obj))
        if ((cptr.ldPtro((obj), $obj_cobj) !== null)) {
            get_valuables(cptr.ldPtro(obj, $obj_cobj));
        } else if (cptr.ld1so(obj, $obj_oartifact)) {
            continue;
        } else if (cptr.ld1so(obj, $obj_oclass) == NHC.AMULET_CLASS) {
            i = (cptr.ldI16o(obj, $obj_otyp) - NHC.FIRST_AMULET) | 0;
            if (!cptr.ldI64o2(ga, i, $sizeof_valuable_data, $instance_globals_a_amulets)) {
                cptr.stI64o2(ga, i, $sizeof_valuable_data, $instance_globals_a_amulets, cptr.ldI64o(obj, $obj_quan));
                cptr.stI32o2(ga, i, $sizeof_valuable_data, $instance_globals_a_amulets + $valuable_data_typ, cptr.ldI16o(obj, $obj_otyp));
            } else
                cptr.stI64o2(ga, i, $sizeof_valuable_data, $instance_globals_a_amulets, cptr.ldI64o2(ga, i, $sizeof_valuable_data, $instance_globals_a_amulets) + cptr.ldI64o(obj, $obj_quan));
        } else if (cptr.ld1so(obj, $obj_oclass) == NHC.GEM_CLASS && cptr.ldI16o(obj, $obj_otyp) <= NHC.LAST_GLASS_GEM) {
            i = (((cptr.ldI16o(obj, $obj_otyp)) < ((NHC.LAST_REAL_GEM + 1) | 0) ? (cptr.ldI16o(obj, $obj_otyp)) : ((NHC.LAST_REAL_GEM + 1) | 0)) - NHC.FIRST_REAL_GEM) | 0;
            if (!cptr.ldI64o2(gg, i, $sizeof_valuable_data, $instance_globals_g_gems)) {
                cptr.stI64o2(gg, i, $sizeof_valuable_data, $instance_globals_g_gems, cptr.ldI64o(obj, $obj_quan));
                cptr.stI32o2(gg, i, $sizeof_valuable_data, $instance_globals_g_gems + $valuable_data_typ, cptr.ldI16o(obj, $obj_otyp));
            } else
                cptr.stI64o2(gg, i, $sizeof_valuable_data, $instance_globals_g_gems, cptr.ldI64o2(gg, i, $sizeof_valuable_data, $instance_globals_g_gems) + cptr.ldI64o(obj, $obj_quan));
        }
    return;
}

/** C ref: end.c:799 — @param {CPtr<struct valuable_data>} list @param {CInt} size */
function sort_valuables(list, size) {
    let i;
    let j;
    let ltmp = cptr.alloc(16);
    for (i = 1; i < size; i++) {
        if (cptr.ldI64o(list, i, $sizeof_valuable_data) == 0n)
            continue;
        cptr.memcpy(ltmp, cptr.add(list, i, $sizeof_valuable_data), 16);
        for (j = i; j > 0; --j) {
            if (cptr.ldI64o(list, (j - 1) | 0, $sizeof_valuable_data) >= cptr.ldI64(ltmp))
                break;
            cptr.memcpy(cptr.add(list, j, $sizeof_valuable_data), cptr.add(list, (j - 1) | 0, $sizeof_valuable_data), 16);
        }
        cptr.memcpy(cptr.add(list, j, $sizeof_valuable_data), ltmp, 16);
    }
    return;
}

/** C ref: end.c:852 */
export function* done_object_cleanup() {
    let ox;
    let oy;
    (yield* inven_inuse(1));
    ox = (cptr.ldI16(u) + cptr.ldI32o(u, $you_dx)) | 0, oy = (cptr.ldI16o(u, $you_uy) + cptr.ldI32o(u, $you_dy)) | 0;
    if (!isok(i16(ox), i16(oy)) || !accessible(i16(ox), i16(oy)))
        ox = cptr.ldI16(u), oy = cptr.ldI16o(u, $you_uy);
    if (cptr.ldPtro(gt, $instance_globals_t_thrownobj) && cptr.ld1so(cptr.ldPtro(gt, $instance_globals_t_thrownobj), $obj_where) == NHM.OBJ_FREE) {
        (yield* place_object(cptr.ldPtro(gt, $instance_globals_t_thrownobj), i16(ox), i16(oy)));
        (yield* stackobj(cptr.ldPtro(gt, $instance_globals_t_thrownobj))), cptr.stPtro(gt, $instance_globals_t_thrownobj, null);
    }
    if (cptr.ldPtro(gk, $instance_globals_k_kickedobj) && cptr.ld1so(cptr.ldPtro(gk, $instance_globals_k_kickedobj), $obj_where) == NHM.OBJ_FREE) {
        (yield* place_object(cptr.ldPtro(gk, $instance_globals_k_kickedobj), i16(ox), i16(oy)));
        (yield* stackobj(cptr.ldPtro(gk, $instance_globals_k_kickedobj))), cptr.stPtro(gk, $instance_globals_k_kickedobj, null);
    }
    if (uchain.v && cptr.ld1so(uchain.v, $obj_where) == NHM.OBJ_FREE) {
        (yield* lift_covet_and_placebc(NHC.override_restriction));
    }
    if (cptr.ld1so(iflags, $instance_flags_perm_invent)) {
        cptr.st1o(iflags, $instance_flags_perm_invent, 0);
        (yield* perm_invent_toggled(1));
    }
    return;
}

/** C ref: end.c:908 — @param {CPtr<struct obj>} list @param {CInt} counting @param {CInt} endwin */
function* artifact_score(list, counting, endwin) {
    let pbuf = new Uint8Array(256);
    let otmp;
    let value;
    let points;
    for (otmp = list; otmp; otmp = cptr.ldPtr(otmp)) {
        if (cptr.ld1so(otmp, $obj_oartifact) || cptr.ldI16o(otmp, $obj_otyp) == NHC.BELL_OF_OPENING || cptr.ldI16o(otmp, $obj_otyp) == NHC.SPE_BOOK_OF_THE_DEAD || cptr.ldI16o(otmp, $obj_otyp) == NHC.CANDELABRUM_OF_INVOCATION) {
            value = arti_cost(otmp);
            points = BigInt.asIntN(64, value * 5n) / 2n;
            if (counting) {
                cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - (points))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + (points))) : 9223372036854775807n));
            } else {
                (yield* discover_object(cptr.ldI16o(otmp, $obj_otyp), 1, 1, 0));
                cptr.stI32o(otmp, $obj_known, cptr.stI32o(otmp, $obj_dknown, cptr.stI32o(otmp, $obj_bknown, cptr.stI32o(otmp, $obj_rknown, 1))));
                void cptr.sprintf(cptr.decay(pbuf), __s_s_s_worth_ld_s_and_ld_points, the_unique_obj(otmp) ? __s_the__2 : __s_empty, cptr.ld1so(otmp, $obj_oartifact) ? artiname(cptr.ld1so(otmp, $obj_oartifact)) : (cptr.ldPtro(obj_descr, cptr.ldI16((cptr.add(objects, cptr.ldI16o(otmp, $obj_otyp), $sizeof_objclass))), $sizeof_objdescr)), value, (yield* currency(value)), points);
                (yield* Y.icall(putstr()(endwin, 0, cptr.decay(pbuf))));
            }
        }
        if ((cptr.ldPtro((otmp), $obj_cobj) !== null))
            (yield* artifact_score(cptr.ldPtro(otmp, $obj_cobj), counting, endwin));
    }
}

/** C ref: end.c:946 — @param {CInt} how @returns {CInt} */
function* fuzzer_savelife(how) {
    if (!cptr.ldI32o(program_state, $sinfo_panicking) && how != NHC.PANICKED && how != NHC.TRICKED) {
        (yield* savelife(how));
        if (!rn2_at(__s_end_c, 959, __s_fuzzer_savelife, (cptr.ldI64o(gd, $instance_globals_d_done_seq) > BigInt.asIntN(64, cptr.ldI64o(gh, $instance_globals_h_hero_seq) + 2n)) ? 2 : 10)) {
            let potion;
            let propidx;
            let proptim;
            let remedies = 0;
            if (ismnum(cptr.ldI32o(u, $you_ulycn)) && !rn2_at(__s_end_c, 965, __s_fuzzer_savelife, 3)) {
                potion = (yield* mksobj(NHC.POT_WATER, 1, 0));
                (yield* bless(potion));
                void (yield* peffects(potion));
                (yield* obfree(potion, null));
                ++remedies;
            }
            if (!remedies || rn2_at(__s_end_c, 972, __s_fuzzer_savelife, 3)) {
                potion = (yield* mksobj(NHC.POT_RESTORE_ABILITY, 1, 0));
                (yield* bless(potion));
                void (yield* peffects(potion));
                (yield* obfree(potion, null));
                ++remedies;
            }
            if (!rn2_at(__s_end_c, 979, __s_fuzzer_savelife, (3 + Math.imul(3, remedies)) | 0)) {
                for (propidx = 1; propidx <= 8; ++propidx) {
                    if (!cptr.ldI64o2(u, propidx, $sizeof_prop, $you_uprops + $prop_intrinsic) && !cptr.ldI64o2(u, propidx, $sizeof_prop, $you_uprops) && (proptim = rn2_at(__s_end_c, 985, __s_fuzzer_savelife, 3)) > 0)
                        set_itimeout(cptr.add(cptr.add(cptr.add(u, $you_uprops), propidx, $sizeof_prop), $prop_intrinsic), BigInt(((Math.imul(2, proptim) + 1) | 0)));
                }
                ++remedies;
            }
            if (!rn2_at(__s_end_c, 991, __s_fuzzer_savelife, (5 + Math.imul(5, remedies)) | 0)) {
                ;
            }
        }
        cptr.st1o2(svk, 0, 1, $kinfo_name, 0);
        cptr.stI32o(svk, $kinfo_format, 0);
        if ((cptr.stI64o(gd, $instance_globals_d_done_seq, cptr.ldI64o(gd, $instance_globals_d_done_seq) + 1n)) - (1n) > BigInt.asIntN(64, cptr.ldI64o(gh, $instance_globals_h_hero_seq) + 100n)) {
            if (!wizard())
                return 0;
            (yield* cmdq_add_ec(NHC.CQ_CANNED, wiz_makemap));
        }
        return 1;
    }
    return 0;
}

/** C ref: end.c:1021 — @param {CInt} how */
export function* done(how) {
    let survive = 0;
    if (how == NHC.TRICKED) {
        if (cptr.ld1so2(svk, 0, 1, $kinfo_name)) {
            (yield* paniclog(__s_trickery, cptr.add(svk, $kinfo_name)));
            cptr.st1o2(svk, 0, 1, $kinfo_name, 0);
        }
        if (wizard()) {
            cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY_AN);
            return;
        }
    }
    if (cptr.ldI32o(program_state, $sinfo_panicking) || cptr.ldI32o(program_state, $sinfo_done_hup) || (how == NHC.QUIT && cptr.ldI32o(program_state, $sinfo_stopprint))) {
        cptr.st1(disp, cptr.st1o(disp, $display_hints_botlx, cptr.st1o(disp, $display_hints_time_botl, 0)));
    } else {
        cptr.st1o(disp, $display_hints_botlx, 1);
        (yield* bot());
    }
    if (cptr.ldI64o(gd, $instance_globals_d_done_seq) < cptr.ldI64o(gh, $instance_globals_h_hero_seq))
        cptr.stI64o(gd, $instance_globals_d_done_seq, cptr.ldI64o(gh, $instance_globals_h_hero_seq));
    if (cptr.ld1so(iflags, $instance_flags_debug_fuzzer)) {
        if ((yield* fuzzer_savelife(how)))
            return;
    }
    if (how == NHC.ASCENDED || (!cptr.ld1so2(svk, 0, 1, $kinfo_name) && how == NHC.GENOCIDED))
        cptr.stI32o(svk, $kinfo_format, NHM.NO_KILLER_PREFIX);
    if (!cptr.ld1so2(svk, 0, 1, $kinfo_name) && (how == NHC.STARVING || how == NHC.BURNING))
        cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY);
    if (!cptr.ld1so2(svk, 0, 1, $kinfo_name) || how >= NHC.PANICKED)
        void cptr.strcpy(cptr.add(svk, $kinfo_name), cptr.ldPtro(deaths, how, 8));
    if (how < NHC.PANICKED) {
        (cptr.stI32o(u, $you_umortality, cptr.ldI32o(u, $you_umortality) + 1)) - (1);
        if (cptr.ldI32o(u, $you_uhp) != 0 || (Upolyd() && cptr.ldI32o(u, $you_mh) != 0)) {
            cptr.stI32o(u, $you_uhp, cptr.stI32o(u, $you_mh, 0));
            cptr.st1(disp, 1);
        }
    }
    if (Lifesaved() && (how <= NHC.GENOCIDED)) {
        (yield* pline(__s_but_wait));
        (yield* discover_object(NHC.AMULET_OF_LIFE_SAVING, 1, 1, 1));
        (yield* Your(__s_medallion_s, !Blind() ? __s_begins_to_glow : __s_feels_warm));
        if (how == NHC.CHOKING)
            (yield* You(__s_vomit));
        (yield* You_feel(__s_much_better));
        (yield* pline_The(__s_medallion_crumbles_to_dust));
        if (uamul.v)
            (yield* useup(uamul.v));
        void (yield* adjattrib(NHC.A_CON, -1, 1));
        (yield* savelife(how));
        if (how == NHC.GENOCIDED) {
            (yield* pline(__s_unfortunately_you_are_still_genocided));
        } else {
            let killbuf = new Uint8Array(256);
            (yield* formatkiller(cptr.decay(killbuf), NHM.BUFSZ, how, 0));
            (yield* livelog_printf(16n, __s_averted_death_s, cptr.decay(killbuf)));
            survive = 1;
        }
    }
    if (!survive && (wizard() || discover()) && how <= NHC.GENOCIDED && !(cptr.ldI32o(program_state, $sinfo_done_hup) && (cptr.stI64o(gd, $instance_globals_d_done_seq, cptr.ldI64o(gd, $instance_globals_d_done_seq) + 1n)) - (1n) == cptr.ldI64o(gh, $instance_globals_h_hero_seq)) && !(yield* paranoid_query(schar((((cptr.ldI32o(flags, $flag_paranoia_bits) & NHM.PARANOID_DIE) >>> 0) != 0)), __s_die__2))) {
        (yield* pline(__s_ok_so_you_don_t_s, (how == NHC.CHOKING) ? __s_choke : __s_die__3));
        cptr.stI32o(iflags, $instance_flags_last_msg, NHC.PLNMSG_OK_DONT_DIE);
        (yield* savelife(how));
        survive = 1;
    }
    if (survive) {
        cptr.st1o2(svk, 0, 1, $kinfo_name, 0);
        cptr.stI32o(svk, $kinfo_format, NHM.KILLED_BY_AN);
        return;
    }
    (yield* really_done(how));
}

/** C ref: end.c:1132 — @param {CInt} how */
function* really_done(how) {
    let taken;
    let pbuf = new Uint8Array(256);
    let endwin = -1;
    let bones_ok;
    let have_windows = cptr.ld1so(iflags, $instance_flags_window_inited);
    let corpse = null;
    let endtime;
    let umoney;
    let tmp;
    cptr.stI32(program_state, 1);
    cptr.stI32o(program_state, $sinfo_something_worth_saving, 0);
    if (cptr.ldI32o(program_state, $sinfo_done_hup))
        (cptr.stI32o(program_state, $sinfo_stopprint, cptr.ldI32o(program_state, $sinfo_stopprint) + 1)) - (1);
    cptr.st1o(iflags, $instance_flags_vision_inited, 0);
    if (!cptr.ldI32o(program_state, $sinfo_panicking))
        (yield* done_object_cleanup());
    cptr.st1o(iflags, $instance_flags_perm_invent, 0);
    cptr.stI64o(urealtime, $u_realtime_finish_time, endtime = (yield* getnow()));
    cptr.stI64(urealtime, cptr.ldI64(urealtime) + timet_delta(endtime, cptr.ldI64o(urealtime, $u_realtime_start_timing)));
    cptr.stI32o(iflags, $instance_flags_at_night, (yield* night()));
    cptr.stI32o(iflags, $instance_flags_at_midnight, (yield* midnight()));
    if (cptr.ld1so2(u, 0, 1, $you_uachieved) || !cptr.ld1so(flags, $flag_beginner)) {
        if (cptr.ld1so(u, $you_uroleplay))
            (yield* record_achievement(NHC.ACH_BLND));
        if (cptr.ld1so(u, $you_uroleplay + $u_roleplay_nudist))
            (yield* record_achievement(NHC.ACH_NUDE));
    }
    if (how == NHC.ASCENDED)
        (yield* record_achievement(NHC.ACH_UWIN));
    dump_open_log(endtime);
    if (cptr.ldI64o(svm, $instance_globals_saved_m_moves) <= 1n && how < NHC.PANICKED && !cptr.ldI32o(program_state, $sinfo_stopprint))
        (yield* pline(__s_do_not_pass_go_do_not_collect_200_s, (yield* currency(200n))));
    if (have_windows)
        (yield* Y.icall(wait_synch()()));
    void signal(2, done_intr);
    void signal(3, done_intr);
    sethanguphandler(done_hangup);
    bones_ok = schar(((how < NHC.GENOCIDED) && can_make_bones() ? 1 : 0));
    if (bones_ok && launch_in_progress())
        (yield* force_launch_placement());
    if (how == NHC.PANICKED)
        cptr.stI32o(u, $you_ugrave_arise, ((NHC.NON_PM - 3) | 0));
    else if (how == NHC.BURNING || how == NHC.DISSOLVED)
        cptr.stI32o(u, $you_ugrave_arise, ((NHC.NON_PM - 2) | 0));
    else if (how == NHC.STONING)
        cptr.stI32o(u, $you_ugrave_arise, NHC.LEAVESTATUE);
    else if (how == NHC.TURNED_SLIME && !(cptr.ld1uo2(svm, NHC.PM_GREEN_SLIME, $sizeof_mvitals, $instance_globals_saved_m_mvitals + $mvitals_mvflags) & NHM.G_GENOD))
        cptr.stI32o(u, $you_ugrave_arise, NHC.PM_GREEN_SLIME);
    if (how == NHC.QUIT) {
        cptr.stI32o(svk, $kinfo_format, NHM.NO_KILLER_PREFIX);
        if (cptr.ldI32o(u, $you_uhp) < 1) {
            how = NHC.DIED;
            (cptr.stI32o(u, $you_umortality, cptr.ldI32o(u, $you_umortality) + 1)) - (1);
            void cptr.strcpy(cptr.add(svk, $kinfo_name), __s_quit_while_already_on_charon_s_boat);
        }
    }
    if (how == NHC.ESCAPED || how == NHC.PANICKED)
        cptr.stI32o(svk, $kinfo_format, NHM.NO_KILLER_PREFIX);
    fixup_death(how);
    if (how != NHC.PANICKED) {
        let silently = schar((cptr.ldI32o(program_state, $sinfo_stopprint) ? 1 : 0));
        taken = (yield* paybill((how == NHC.ESCAPED) ? -1 : (how != NHC.QUIT), silently));
        (yield* paygd(silently));
        (yield* clearpriests());
    } else
        taken = 0;
    clearlocks();
    if (have_windows)
        (yield* Y.icall(display_nhwindow()(WIN_MESSAGE.v, 0)));
    if (how != NHC.PANICKED) {
        let obj;
        let nextobj;
        for (obj = cptr.ldPtro(gi, $instance_globals_i_invent); obj; obj = nextobj) {
            nextobj = cptr.ldPtr(obj);
            (yield* discover_object(cptr.ldI16o(obj, $obj_otyp), 1, 1, 0));
            cptr.stI32o(obj, $obj_known, cptr.stI32o(obj, $obj_bknown, cptr.stI32o(obj, $obj_dknown, cptr.stI32o(obj, $obj_rknown, 1))));
            set_cknown_lknown(obj);
            if (SchroedingersBox(obj)) {
                if (!Schroedingers_cat) {
                    (yield* observe_quantum_cat(obj, 0, 0));
                    if (SchroedingersBox(obj))
                        Schroedingers_cat = 1;
                } else
                    cptr.st1o(obj, $obj_spe, 0);
            }
        }
        if (strcmp(cptr.add(flags, $flag_end_disclose), __s_none))
            (yield* disclose(how, taken));
        (yield* formatkiller(cptr.decay(pbuf), 256, how, 1));
        if (!cptr.ld1s(cptr.decay(pbuf)))
            void cptr.strcpy(cptr.decay(pbuf), cptr.ldPtro(deaths, how, 8));
        (yield* livelog_printf(16384n, __s_pct_s, cptr.decay(pbuf)));
        dump_everything(how, endtime);
    }
    if (how == NHC.ESCAPED || how == NHC.ASCENDED)
        (yield* keepdogs(1));
    if (bones_ok && taken)
        (yield* finish_paybill());
    if (bones_ok && cptr.ldI32o(u, $you_ugrave_arise) == NHC.NON_PM && !(cptr.ld1uo2(svm, cptr.ldI32o(u, $you_umonnum), $sizeof_mvitals, $instance_globals_saved_m_mvitals + $mvitals_mvflags) & NHM.G_NOCORPSE)) {
        let mnum = !Upolyd() ? cptr.ldI16o(gu, $instance_globals_u_urace + $Race_mnum) : cptr.ldI32o(u, $you_umonnum);
        let was_already_grave = ((cptr.ld1so3(svl, cptr.ldI16(u), $sizeof_rm_x21, cptr.ldI16o(u, $you_uy), $sizeof_rm, $instance_globals_saved_l_level + $rm_typ)) == NHC.GRAVE);
        corpse = (yield* mk_named_object(NHC.CORPSE, cptr.add(mons, mnum, $sizeof_permonst), cptr.ldI16(u), cptr.ldI16o(u, $you_uy), svp));
        void cptr.sprintf(cptr.decay(pbuf), __s_pct_s_comma_sp, svp);
        (yield* formatkiller(eos(cptr.decay(pbuf)), Number(BigInt.asUintN(32, BigInt.asUintN(64, 256n - BigInt((yield* Strlen_(cptr.decay(pbuf), __s_really_done, 1317)) >>> 0)))), how, 1));
        (yield* make_grave(cptr.ldI16(u), cptr.ldI16o(u, $you_uy), cptr.decay(pbuf)));
        if (((cptr.ld1so3(svl, cptr.ldI16(u), $sizeof_rm_x21, cptr.ldI16o(u, $you_uy), $sizeof_rm, $instance_globals_saved_l_level + $rm_typ)) == NHC.GRAVE) && !was_already_grave)
            cptr.stI32o3(svl, cptr.ldI16(u), $sizeof_rm_x21, cptr.ldI16o(u, $you_uy), $sizeof_rm, $instance_globals_saved_l_level + $rm_flags, 1);
    }
    cptr.st1o(cptr.decay(pbuf), 0, 0, 1);
    {
        let deepest = deepest_lev_reached(0);
        umoney = money_cnt(cptr.ldPtro(gi, $instance_globals_i_invent));
        tmp = cptr.ldI64o(u, $you_umoney0);
        umoney += hidden_gold(1);
        tmp = BigInt.asIntN(64, umoney - tmp);
        if (tmp < 0n)
            tmp = 0n;
        if (how < NHC.PANICKED)
            tmp -= tmp / 10n;
        tmp += BigInt.asIntN(64, 50n * BigInt(((deepest - 1) | 0)));
        if (deepest > 20)
            tmp += BigInt.asIntN(64, 1000n * BigInt(((deepest > 30) ? 10 : (deepest - 20) | 0)));
        cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - (tmp))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + (tmp))) : 9223372036854775807n));
        if (how == NHC.ASCENDED && cptr.ld1so(u, $you_ualign) == cptr.ld1so2(u, NHM.A_ORIGINAL, 1, $you_ualignbase)) {
            tmp = (cptr.ld1so2(u, NHM.A_CURRENT, 1, $you_ualignbase) == cptr.ld1so2(u, NHM.A_ORIGINAL, 1, $you_ualignbase)) ? cptr.ldI64o(u, $you_urexp) : (cptr.ldI64o(u, $you_urexp) / 2n);
            cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - (tmp))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + (tmp))) : 9223372036854775807n));
        }
    }
    if (ismnum(cptr.ldI32o(u, $you_ugrave_arise)) && !cptr.ldI32o(program_state, $sinfo_stopprint)) {
        (yield* Your(__s_s_as_s, (cptr.ldI32o(u, $you_ugrave_arise) != NHC.PM_GREEN_SLIME) ? __s_body_rises_from_the_dead : __s_revenant_persists, (yield* an(pmname(cptr.add(mons, cptr.ldI32o(u, $you_ugrave_arise), $sizeof_permonst), Ugender())))));
        (yield* Y.icall(display_nhwindow()(WIN_MESSAGE.v, 0)));
    }
    if (bones_ok) {
        if (!wizard() || (yield* paranoid_query(schar((((cptr.ldI32o(flags, $flag_paranoia_bits) & NHM.PARANOID_BONES) >>> 0) != 0)), __s_save_bones)))
            (yield* savebones(how, endtime, corpse));
        corpse = null;
    }
    cptr.stI64o(gd, $instance_globals_d_done_money, umoney);
    if (have_windows) {
        (yield* Y.icall(wait_synch()()));
        (yield* free_pickinv_cache());
        if (WIN_INVEN.v != -1) {
            (yield* Y.icall(destroy_nhwindow()(WIN_INVEN.v))), WIN_INVEN.v = -1;
            cptr.st1o(iflags, $instance_flags_perm_invent, 0);
        }
        (yield* Y.icall(display_nhwindow()(WIN_MESSAGE.v, 1)));
        (yield* Y.icall(destroy_nhwindow()(WIN_MAP.v))), WIN_MAP.v = -1;
        if (WIN_STATUS.v != -1)
            (yield* Y.icall(destroy_nhwindow()(WIN_STATUS.v))), WIN_STATUS.v = -1;
        (yield* Y.icall(destroy_nhwindow()(WIN_MESSAGE.v))), WIN_MESSAGE.v = -1;
        if (!cptr.ldI32o(program_state, $sinfo_stopprint) || cptr.ld1so(flags, $flag_tombstone))
            endwin = (yield* Y.icall(create_nhwindow()(NHM.NHW_TEXT)));
        if (how < NHC.GENOCIDED && cptr.ld1so(flags, $flag_tombstone) && endwin != -1)
            (yield* Y.icall(outrip()(endwin, how, endtime)));
    } else
        cptr.stI32o(program_state, $sinfo_stopprint, 1);
    if ((cptr.ldI32o(u, $you_uhave) & 1)) {
        void cptr.strcat(cptr.add(svk, $kinfo_name), __s_with_the_amulet);
    } else if (how == NHC.ESCAPED) {
        if ((((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))))
            void cptr.strcat(cptr.add(svk, $kinfo_name), __s_in_celestial_disgrace);
        else if (carrying(NHC.FAKE_AMULET_OF_YENDOR))
            void cptr.strcat(cptr.add(svk, $kinfo_name), __s_with_a_fake_amulet);
    }
    void cptr.sprintf(cptr.decay(pbuf), __s_s_s_the_s, Goodbye(), svp, (how != NHC.ASCENDED) ? ((cptr.ld1so(flags, $flag_female) && cptr.ldPtro(gu, $instance_globals_u_urole + $RoleName_f)) ? cptr.ldPtro(gu, $instance_globals_u_urole + $RoleName_f) : cptr.ldPtro(gu, $instance_globals_u_urole)) : (cptr.ld1so(flags, $flag_female) ? __s_demigoddess : __s_demigod));
    (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
    (yield* dump_forward_putstr(endwin, 0, __s_empty, cptr.ldI32o(program_state, $sinfo_stopprint)));
    if (how == NHC.ESCAPED || how == NHC.ASCENDED) {
        let mtmp;
        let otmp;
        let val;
        let i;
        for (val = cptr.add(gv, $instance_globals_v_valuables); cptr.ldPtr(val); val = cptr.add(val, 1, 16))
            for (i = 0; i < cptr.ldI32o(val, $val_list_size); i++) {
                cptr.stI64o(cptr.ldPtr(val), i, 0n, $sizeof_valuable_data);
            }
        get_valuables(cptr.ldPtro(gi, $instance_globals_i_invent));
        for (val = cptr.add(gv, $instance_globals_v_valuables); cptr.ldPtr(val); val = cptr.add(val, 1, 16))
            for (i = 0; i < cptr.ldI32o(val, $val_list_size); i++)
                if (cptr.ldI64o(cptr.ldPtr(val), i, $sizeof_valuable_data) != 0n) {
                    tmp = BigInt.asIntN(64, cptr.ldI64o(cptr.ldPtr(val), i, $sizeof_valuable_data) * BigInt(cptr.ldI16o2(objects, cptr.ldI32o2(cptr.ldPtr(val), i, $sizeof_valuable_data, $valuable_data_typ), $sizeof_objclass, $objclass_oc_cost)));
                    cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - (tmp))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + (tmp))) : 9223372036854775807n));
                }
        (yield* artifact_score(cptr.ldPtro(gi, $instance_globals_i_invent), 1, endwin));
        cptr.st1o(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), 0, 8), 0, cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), 0, 8), 0) | NHM.IN_SIGHT);
        mtmp = cptr.ldPtro(gm, $instance_globals_m_mydogs);
        void cptr.strcpy(cptr.decay(pbuf), __s_you);
        if (mtmp || Schroedingers_cat) {
            while (mtmp) {
                void cptr.sprintf(eos(cptr.decay(pbuf)), __s_and_s, (yield* mon_nam(mtmp)));
                if (cptr.ld1so(mtmp, $monst_mtame))
                    cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - BigInt((cptr.ldI32o(mtmp, $monst_mhp))))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + BigInt((cptr.ldI32o(mtmp, $monst_mhp))))) : 9223372036854775807n));
                mtmp = cptr.ldPtr(mtmp);
            }
            if (Schroedingers_cat) {
                let mhp;
                let m_lev = (yield* adj_lev(cptr.add(mons, NHC.PM_HOUSECAT, $sizeof_permonst)));
                mhp = d_at(__s_end_c, 1468, __s_really_done, (m_lev), 8);
                cptr.stI64o(u, $you_urexp, ((cptr.ldI64o(u, $you_urexp)) <= (BigInt.asIntN(64, 9223372036854775807n - BigInt((mhp)))) ? (BigInt.asIntN(64, (cptr.ldI64o(u, $you_urexp)) + BigInt((mhp)))) : 9223372036854775807n));
                void cptr.strcat(eos(cptr.decay(pbuf)), __s_and_schroedinger_s_cat);
            }
            (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
            cptr.st1o(cptr.decay(pbuf), 0, 0, 1);
        } else {
            void cptr.strcat(cptr.decay(pbuf), __s_sp);
        }
        void cptr.sprintf(eos(cptr.decay(pbuf)), __s_s_with_ld_point_s, (how == NHC.ASCENDED) ? __s_went_to_your_reward : __s_escaped_from_the_dungeon, cptr.ldI64o(u, $you_urexp), (((cptr.ldI64o(u, $you_urexp)) == 1n) ? __s_empty : __s_s));
        (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
        if (!cptr.ldI32o(program_state, $sinfo_stopprint))
            (yield* artifact_score(cptr.ldPtro(gi, $instance_globals_i_invent), 0, endwin));
        for (val = cptr.add(gv, $instance_globals_v_valuables); cptr.ldPtr(val); val = cptr.add(val, 1, 16)) {
            sort_valuables(cptr.ldPtr(val), cptr.ldI32o(val, $val_list_size));
            for (i = 0; i < cptr.ldI32o(val, $val_list_size) && !cptr.ldI32o(program_state, $sinfo_stopprint); i++) {
                let typ = cptr.ldI32o2(cptr.ldPtr(val), i, $sizeof_valuable_data, $valuable_data_typ);
                let count = cptr.ldI64o(cptr.ldPtr(val), i, $sizeof_valuable_data);
                if (count == 0n)
                    continue;
                if (cptr.ld1so2(objects, typ, $sizeof_objclass, $objclass_oc_class) != NHC.GEM_CLASS || typ <= NHC.LAST_REAL_GEM) {
                    otmp = (yield* mksobj(typ, 0, 0));
                    (yield* discover_object(cptr.ldI16o(otmp, $obj_otyp), 1, 1, 0));
                    cptr.stI32o(otmp, $obj_dknown, 1);
                    cptr.stI32o(otmp, $obj_known, 1);
                    if (has_oname(otmp))
                        free_oname(otmp);
                    cptr.stI64o(otmp, $obj_quan, count);
                    void cptr.sprintf(cptr.decay(pbuf), __s_8ld_s_worth_ld_s, count, (yield* xname(otmp)), BigInt.asIntN(64, count * BigInt(cptr.ldI16o2(objects, typ, $sizeof_objclass, $objclass_oc_cost))), (yield* currency(2n)));
                    (yield* obfree(otmp, null));
                } else {
                    void cptr.sprintf(cptr.decay(pbuf), __s_8ld_worthless_piece_s_of_colored_glass, count, (((count) == 1n) ? __s_empty : __s_s));
                }
                (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), 0));
            }
        }
    } else {
        if (cptr.ldI16o(u, $you_uz) == 0 && cptr.ldI16o(u, $you_uz + $d_level_dlevel) <= 0) {
            void cptr.sprintf(cptr.decay(pbuf), __s_you_s_beyond_the_confines_of_the_dungeon, (cptr.ldI16o(u, $you_uz + $d_level_dlevel) < 0) ? __s_passed_away : cptr.ldPtro(ends, how, 8));
        } else {
            let where = cptr.add(svd, cptr.ldI16o(u, $you_uz), $sizeof_dungeon);
            if ((((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))))
                where = __s_the_astral_plane;
            void cptr.sprintf(cptr.decay(pbuf), __s_you_s_in_s, cptr.ldPtro(ends, how, 8), where);
            if (!(cptr.ldI16((cptr.add(u, $you_uz))) == cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))) && !single_level_branch(cptr.add(u, $you_uz)))
                void cptr.sprintf(eos(cptr.decay(pbuf)), __s_on_dungeon_level_d, In_quest(cptr.add(u, $you_uz)) ? dunlev(cptr.add(u, $you_uz)) : depth(cptr.add(u, $you_uz)));
        }
        void cptr.sprintf(eos(cptr.decay(pbuf)), __s_with_ld_point_s, cptr.ldI64o(u, $you_urexp), (((cptr.ldI64o(u, $you_urexp)) == 1n) ? __s_empty : __s_s));
        (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
    }
    void cptr.sprintf(cptr.decay(pbuf), __s_and_ld_piece_s_of_gold_after_ld_move_s, umoney, (((umoney) == 1n) ? __s_empty : __s_s), cptr.ldI64o(svm, $instance_globals_saved_m_moves), (((cptr.ldI64o(svm, $instance_globals_saved_m_moves)) == 1n) ? __s_empty : __s_s));
    (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
    void cptr.sprintf(cptr.decay(pbuf), __s_you_were_level_d_with_a_maximum_of_d, cptr.ldI32o(u, $you_ulevel), cptr.ldI32o(u, $you_uhpmax), (((cptr.ldI32o(u, $you_uhpmax)) == 1) ? __s_empty : __s_s), cptr.ldPtro(ends, how, 8));
    (yield* dump_forward_putstr(endwin, 0, cptr.decay(pbuf), cptr.ldI32o(program_state, $sinfo_stopprint)));
    (yield* dump_forward_putstr(endwin, 0, __s_empty, cptr.ldI32o(program_state, $sinfo_stopprint)));
    if (!cptr.ldI32o(program_state, $sinfo_stopprint))
        (yield* Y.icall(display_nhwindow()(endwin, 1)));
    if (endwin != -1)
        (yield* Y.icall(destroy_nhwindow()(endwin)));
    dump_close_log();
    if (cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))
        (yield* Y.icall((cptr.ldPtro(soundprocs, $sound_procs_sound_exit_nhsound))(__s_really_done)));
    if (have_windows && !cptr.ld1so(iflags, $instance_flags_toptenwin))
        (yield* Y.icall(exit_nhwindows()(null))), have_windows = 0;
    (yield* topten(how, endtime));
    if (have_windows)
        (yield* Y.icall(exit_nhwindows()(null)));
    if (cptr.ldI32o(program_state, $sinfo_stopprint)) {
        (yield* Y.icall(raw_print()(__s_empty)));
        (yield* Y.icall(raw_print()(__s_empty)));
    }
    (yield* nh_terminate(0));
}

/** C ref: end.c:1596 — @param {CPtr<struct obj>} list @param {CInt} identified @param {CInt} all_containers @param {CInt} reportempty */
export function* container_contents(list, identified, all_containers, reportempty) {
    let box;
    let obj;
    let buf = new Uint8Array(256);
    let cat;
    let dumping = cptr.ld1so(iflags, $instance_flags_in_dumplog);
    for (box = list; box; box = cptr.ldPtr(box)) {
        if (Is_container(box) || cptr.ldI16o(box, $obj_otyp) == NHC.STATUE) {
            if (!(cptr.ldI32o(box, $obj_cknown) & 1) || (identified && !(cptr.ldI32o(box, $obj_lknown) & 1))) {
                cptr.stI32o(box, $obj_cknown, 1);
                if (identified)
                    cptr.stI32o(box, $obj_lknown, 1);
                (yield* update_inventory());
            }
            if (cptr.ldI16o(box, $obj_otyp) == NHC.BAG_OF_TRICKS) {
                continue;
            } else if (cptr.ldPtro(box, $obj_cobj)) {
                let tmpwin = (yield* Y.icall(create_nhwindow()(NHM.NHW_MENU)));
                let sortedcobj = cptr.box(0);
                let srtc;
                let sortflags;
                cat = schar(SchroedingersBox(box));
                void cptr.sprintf(cptr.decay(buf), __s_contents_of_s, (yield* the((yield* xname(box)))));
                (yield* Y.icall(putstr()(tmpwin, 0, cptr.decay(buf))));
                if (!dumping)
                    (yield* Y.icall(putstr()(tmpwin, 0, __s_empty)));
                cptr.st1o(cptr.decay(buf), 0, cptr.st1o(cptr.decay(buf), 1, 32, 1), 1);
                if (cptr.ldPtro(box, $obj_cobj) && !cat) {
                    sortflags = (((cptr.ld1so(flags, $flag_sortloot) == 108 || cptr.ld1so(flags, $flag_sortloot) == 102) ? NHM.SORTLOOT_LOOT : 0) | (cptr.ld1so(flags, $flag_sortpack) ? NHM.SORTLOOT_PACK : 0)) >>> 0;
                    sortedcobj.v = (yield* sortloot(cptr.add(box, $obj_cobj), sortflags, 0, null));
                    for (srtc = sortedcobj.v; (obj = cptr.ldPtr(srtc)) !== null; srtc = cptr.add(srtc, 1, 24)) {
                        if (identified) {
                            (yield* discover_object(cptr.ldI16o(obj, $obj_otyp), 1, 1, 0));
                            cptr.stI32o(obj, $obj_dknown, 1);
                            cptr.stI32o(obj, $obj_known, cptr.stI32o(obj, $obj_bknown, cptr.stI32o(obj, $obj_rknown, 1)));
                            if (Is_container(obj) || cptr.ldI16o(obj, $obj_otyp) == NHC.STATUE)
                                cptr.stI32o(obj, $obj_cknown, cptr.stI32o(obj, $obj_lknown, 1));
                        }
                        void cptr.strcpy(cptr.add(cptr.decay(buf), 2, 1), (yield* doname_with_price(obj)));
                        (yield* Y.icall(putstr()(tmpwin, 0, cptr.decay(buf))));
                    }
                    unsortloot(sortedcobj);
                } else if (cat) {
                    void cptr.strcpy(cptr.add(cptr.decay(buf), 2, 1), __s_schroedinger_s_cat);
                    (yield* Y.icall(putstr()(tmpwin, 0, cptr.decay(buf))));
                }
                if (dumping)
                    (yield* Y.icall(putstr()(0, 0, __s_empty)));
                (yield* Y.icall(display_nhwindow()(tmpwin, 1)));
                (yield* Y.icall(destroy_nhwindow()(tmpwin)));
                if (all_containers)
                    (yield* container_contents(cptr.ldPtro(box, $obj_cobj), identified, 1, reportempty));
            } else if (reportempty) {
                (yield* pline(__s_s_is_empty, upstart((yield* thesimpleoname(box)))));
                (yield* Y.icall(display_nhwindow()(WIN_MESSAGE.v, 0)));
            }
        }
        if (!all_containers)
            break;
    }
}

/** C ref: end.c:1676 — @param {CInt} status */
export function* nh_terminate(status) {
    cptr.stI32o(program_state, $sinfo_in_moveloop, 0);
    (yield* nomux_capture_write_input_boundary());
    (yield* l_nhcore_call(NHC.NHCORE_GAME_EXIT));
    if (!cptr.ldI32o(program_state, $sinfo_panicking)) {
        (yield* freedynamicdata());
        ;
        (yield* l_nhcore_done());
    }
    cptr.stI32o(program_state, $sinfo_exiting, 1);
    exit(status);
}

/** C ref: end.c:1721 — @param {CInt} id @param {CInt} format @param {CPtr<char>} killername */
export function* delayed_killer(id, format, killername) {
    let k = find_delayed_killer(id);
    if (!k) {
        k = (yield* alloc(272));
        void __builtin___memset_chk(k, 0, 272n, __builtin_object_size(k, 0));
        cptr.stI32o(k, $kinfo_id, id);
        cptr.stPtr(k, cptr.ldPtr(svk));
        cptr.stPtr(svk, k);
    }
    cptr.stI32o(k, $kinfo_format, format);
    void cptr.strcpy(cptr.add(k, $kinfo_name), killername ? killername : __s_empty);
    cptr.st1o2(svk, 0, 1, $kinfo_name, 0);
}

/** C ref: end.c:1740 — @param {CInt} id @returns {CPtr<struct kinfo>} */
export function find_delayed_killer(id) {
    let k;
    for (k = cptr.ldPtr(svk); k !== null; k = cptr.ldPtr(k)) {
        if (cptr.ldI32o(k, $kinfo_id) == id)
            break;
    }
    return k;
}

/** C ref: end.c:1752 — @param {CPtr<struct kinfo>} kptr */
export function* dealloc_killer(kptr) {
    let prev = svk;
    let k;
    if (kptr === null)
        return;
    for (k = cptr.ldPtr(svk); k !== null; k = cptr.ldPtr(k)) {
        if (cptr.eq(k, kptr))
            break;
        prev = k;
    }
    if (k === null) {
        (yield* impossible(__s_dealloc_killer_d_not_on_list, cptr.ldI32o(kptr, $kinfo_id)));
    } else {
        cptr.stPtr(prev, cptr.ldPtr(k));
        cptr.free(k);
        {
            if ((yield* debugcore(__s_end_c, 1))) {
                let save_plnmsg = cptr.ldI32o(iflags, $instance_flags_last_msg);
                (yield* pline(__s_freed_delayed_killer_d, cptr.ldI32o(kptr, $kinfo_id)));
                cptr.stI32o(iflags, $instance_flags_last_msg, save_plnmsg);
            }
        }
    }
}

/** C ref: end.c:1774 — @param {CPtr<NHFILE>} nhfp */
export function* save_killers(nhfp) {
    let kptr;
    if ((cptr.ldI32o((nhfp), $NHFILE_mode) & 3)) {
        for (kptr = svk; kptr; kptr = cptr.ldPtr(kptr)) {
            (yield* sfo_kinfo(nhfp, kptr, __s_kinfo));
        }
    }
    if ((cptr.ldI32o((nhfp), $NHFILE_mode) & NHM.FREEING)) {
        while (cptr.ldPtr(svk)) {
            kptr = cptr.ldPtr(cptr.ldPtr(svk));
            cptr.free(cptr.ldPtr(svk));
            cptr.stPtr(svk, kptr);
        }
    }
}

/** C ref: end.c:1794 — @param {CPtr<NHFILE>} nhfp */
export function* restore_killers(nhfp) {
    let kptr;
    for (kptr = svk; kptr !== null; kptr = cptr.ldPtr(kptr)) {
        (yield* sfi_kinfo(nhfp, kptr, __s_kinfo));
        if (cptr.ldPtr(kptr)) {
            cptr.stPtr(kptr, (yield* alloc(272)));
        }
    }
}

/** C ref: end.c:1807 — @param {CPtr<char>} p @returns {CInt} */
function wordcount(p) {
    let words = 0;
    while (cptr.ld1s(p)) {
        while (cptr.ld1s(p) && isspace(uchar(cptr.ld1s(p))))
            p = cptr.add(p, 1);
        if (cptr.ld1s(p))
            words++;
        while (cptr.ld1s(p) && !isspace(uchar(cptr.ld1s(p))))
            p = cptr.add(p, 1);
    }
    return words;
}

/** C ref: end.c:1823 — @param {CPtr<char *>} inp @param {CPtr<char>} out */
function* bel_copy1(inp, out) {
    let in$ = cptr.ldPtr(inp);
    out = cptr.add(out, cptr.strlen(out));
    while (cptr.ld1s(in$) && isspace(uchar(cptr.ld1s(in$))))
        in$ = cptr.add(in$, 1);
    while (cptr.ld1s(in$) && !isspace(uchar(cptr.ld1s(in$))))
        cptr.st1(cptr.postinc(() => out, (v) => { out = v; }), cptr.ld1s(cptr.postinc(() => in$, (v) => { in$ = v; })));
    cptr.st1(out, 0);
    cptr.stPtr(inp, in$);
}

/** C ref: end.c:1837 — @param {CPtr<char>} in @returns {CPtr<char>} */
export function* build_english_list(in$) {
    let out;
    let p = cptr.box(in$);
    let len = Number(BigInt.asIntN(32, cptr.strlen(p.v)));
    let words = wordcount(p.v);
    if (words > 1)
        len = (len + ((3 + ((words - 1) | 0)) | 0)) | 0;
    out = (yield* alloc(((len + 1) | 0) >>> 0));
    cptr.st1(out, 0);
    switch (words) {
        case 0:
        (yield* impossible(__s_no_words_in_list));
        break;
        case 1:
        (yield* bel_copy1(p, out));
        break;
        default:
        if (words == 2) {
            (yield* bel_copy1(p, out));
            void cptr.strcat(out, __s_sp);
        } else {
            do {
                (yield* bel_copy1(p, out));
                void cptr.strcat(out, __s_comma_sp);
            } while (--words > 1);
        }
        void cptr.strcat(out, __s_or);
        (yield* bel_copy1(p, out));
        break;
    }
    return out;
}

let __static_NH_abort_aborting = 0; /** C ref: end.c:1916 — signed char (function-static) */

/** C ref: end.c:1910 — @param {CPtr<char>} why */
export function* NH_abort(why) {
    let gdb_prio = cptr.ldI32o(sysopt, $sysopt_s_panictrace_gdb);
    let libc_prio = cptr.ldI32o(sysopt, $sysopt_s_panictrace_libc);
    if (__static_NH_abort_aborting)
        return;
    __static_NH_abort_aborting = 1;
    if (!(yield* submit_web_report(1, __s_panic__2, why))) {
        if (gdb_prio == libc_prio && gdb_prio > 0)
            gdb_prio++;
        if (gdb_prio > libc_prio) {
            void ((yield* NH_panictrace_gdb()) || (libc_prio && (yield* NH_panictrace_libc())) ? 1 : 0);
        } else {
            void ((yield* NH_panictrace_libc()) || (gdb_prio && (yield* NH_panictrace_gdb())) ? 1 : 0);
        }
    }
    panictrace_setsignals(0);
    abort();
}

// --- BEGIN c2js reset block (tools/c2js/resetify.mjs) — do not edit ---
// 5 bindings: 0 rebound+refilled, 2 rebound, 3 refilled.
// S/P are supplied by js/generated-y/__reset.js so this module needs no new import.
let __c2js_rs = null;
export function __captureState(S) { __c2js_rs = [S(deaths), S(ends), S(Schroedingers_cat), S(death_fixups), S(__static_NH_abort_aborting)]; }
export function __resetState(P) {
    const r = __c2js_rs;
    if (r === null) throw new Error("end.js: __resetState before __captureState");
    P(r[0]);
    P(r[1]);
    Schroedingers_cat = P(r[2]);
    P(r[3]);
    __static_NH_abort_aborting = P(r[4]);
}
// --- END c2js reset block ---
