// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/ioctl.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/sys/share/ioctl.c
// Input sha256: fdbffc60327dfcf3d1ed4c1673a9e85829b9d7996e3615413219cd76862a2142
// Transpiler: tools/c2js c2js emit v1+batch

import * as cptr from '../cptr.js';
import * as FLD from './nhfield.js';
import { gt } from './decl.js';
import { sysopt } from './sys.js';
import { check_user_string } from './unixmain.js';
import { Norep, pline } from './pline.js';
import { windowprocs } from './windows.js';

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("Suspend command not available.");
const __sl1 = cptr.lit("I don't think your shell has job control.");

/** C ref: ioctl.c:43 — struct termios */
export let termio = cptr.alloc(72);

/** C ref: ioctl.c:96 */
export function getwindowsz() {
    let ttsz = cptr.alloc(8);
    if (ioctl(fileno(__stdinp), 1074295912n, ttsz) != -1) {
        if (cptr.ldU16(ttsz))
            cptr.stI32o(gt, FLD.instance_globals_t_tc_gbl_data + FLD.tc_gbl_data_tc_LI, cptr.ldU16(ttsz));
        if (cptr.ldU16o(ttsz, FLD.winsize_ws_col))
            cptr.stI32o(gt, FLD.instance_globals_t_tc_gbl_data + FLD.tc_gbl_data_tc_CO, cptr.ldU16o(ttsz, FLD.winsize_ws_col));
    }
}

/** C ref: ioctl.c:119 */
export function getioctls() {
    void tcgetattr(fileno(__stdinp), termio);
    getwindowsz();
}

/** C ref: ioctl.c:142 */
export function setioctls() {
    void tcsetattr(fileno(__stdinp), 1, termio);
}

/** C ref: ioctl.c:161 @returns {CInt} */
export function* dosuspend() {
    if (!cptr.ldPtro(sysopt, FLD.sysopt_s_shellers) || !cptr.ld1so(cptr.ldPtro(sysopt, FLD.sysopt_s_shellers), 0) || !check_user_string(cptr.ldPtro(sysopt, FLD.sysopt_s_shellers))) {
        (yield* Norep(__sl0));
        return 0;
    }
    if (signal(18, 1) === null) {
        (yield* Y.icall((cptr.ldPtro(windowprocs, FLD.window_procs_win_suspend_nhwindows))(null)));
        void signal(18, null);
        void kill(0, 18);
        (yield* Y.icall((cptr.ldPtro(windowprocs, FLD.window_procs_win_resume_nhwindows))()));
    } else {
        (yield* pline(__sl1));
    }
    return 0;
}

// --- BEGIN c2js reset block (tools/c2js/resetify.mjs) — do not edit ---
// 1 bindings: 1 rebound+refilled, 0 rebound, 0 refilled.
// S/P are supplied by js/generated-y/__reset.js so this module needs no new import.
let __c2js_rs = null;
export function __captureState(S) { __c2js_rs = [S(termio)]; }
export function __resetState(P) {
    const r = __c2js_rs;
    if (r === null) throw new Error("ioctl.js: __resetState before __captureState");
    termio = P(r[0]);
}
// --- END c2js reset block ---
