// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/ldump.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/lib/lua-5.4.8/src/ldump.c
// Input sha256: 3c05402c5e282e06c2218f2469b1f38e1b84c783b9387aec7740c60b287d82c9
// Transpiler: tools/c2js c2js emit v1+batch

import { uchar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as FLD from './nhfield.js';

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("\x1bLua");
const __sl1 = cptr.lit("\x19\x93\r\n\x1a\n");

/** C ref: ldump.c:23 — struct undefined {  } (memory model v0.5) */

/** C ref: ldump.c:29 — typedef DumpState (type alias only, no runtime output) */

/** C ref: ldump.c:41 — @param {CPtr} D @param {CPtr} b @param {CLongLong} size */
function* dumpBlock(D, b, size) {
    if (cptr.ldI32o(D, FLD.DumpState_status) == 0 && size > 0n) {
        (void 0);
        cptr.stI32o(D, FLD.DumpState_status, (yield* Y.icall((cptr.ldPtro(D, FLD.DumpState_writer))(cptr.ldPtr(D), b, size, cptr.ldPtro(D, FLD.DumpState_data)))));
        (void 0);
    }
}

/** C ref: ldump.c:53 — @param {CPtr} D @param {CInt} y */
function* dumpByte(D, y) {
    let x = cptr.box(uchar(y));
    (yield* dumpBlock(D, x, 1n));
}

/** C ref: ldump.c:65 — @param {CPtr} D @param {CLongLong} x */
function* dumpSize(D, x) {
    let buff = new Uint8Array(10);
    let n = 0;
    do {
        cptr.st1o(cptr.decay(buff), BigInt.asUintN(64, 10n - BigInt.asUintN(64, BigInt((++n)))), Number(BigInt.asUintN(8, (x & 127n))), 1);
        x >>= 7n;
    } while (x != 0n);
    cptr.st1o(cptr.decay(buff), 9n, cptr.ld1uo(cptr.decay(buff), 9n, 1) | 128, 1);
    (yield* dumpBlock(D, cptr.add(cptr.add(cptr.decay(buff), 10n), -(n)), BigInt.asUintN(64, BigInt.asUintN(64, BigInt((n))) * 1n)));
}

/** C ref: ldump.c:77 — @param {CPtr} D @param {CInt} x */
function* dumpInt(D, x) {
    (yield* dumpSize(D, BigInt.asUintN(64, BigInt(x))));
}

/** C ref: ldump.c:82 — @param {CPtr} D @param {CDouble} x */
function* dumpNumber(D, x) {
    x = cptr.box(x);
    (yield* dumpBlock(D, x, 8n));
}

/** C ref: ldump.c:87 — @param {CPtr} D @param {CLongLong} x */
function* dumpInteger(D, x) {
    x = cptr.box(x);
    (yield* dumpBlock(D, x, 8n));
}

/** C ref: ldump.c:92 — @param {CPtr} D @param {CPtr} s */
function* dumpString(D, s) {
    if (cptr.eq(s, (null)))
        (yield* dumpSize(D, 0n));
    else {
        let size = (cptr.ld1uo((s), FLD.TString_shrlen) != 255 ? BigInt(cptr.ld1uo((s), FLD.TString_shrlen) >>> 0) : cptr.ldU64o((s), FLD.TString_u));
        let str = (cptr.add((s), FLD.TString_contents));
        (yield* dumpSize(D, BigInt.asUintN(64, size + 1n)));
        (yield* dumpBlock(D, str, BigInt.asUintN(64, (size) * 1n)));
    }
}

/** C ref: ldump.c:104 — @param {CPtr} D @param {CPtr} f */
function* dumpCode(D, f) {
    (yield* dumpInt(D, cptr.ldI32o(f, FLD.Proto_sizecode)));
    (yield* dumpBlock(D, cptr.ldPtro(f, FLD.Proto_code), BigInt.asUintN(64, BigInt.asUintN(64, BigInt((cptr.ldI32o(f, FLD.Proto_sizecode)))) * 4n)));
}

/** C ref: ldump.c:112 — @param {CPtr} D @param {CPtr} f */
function* dumpConstants(D, f) {
    let i;
    let n = cptr.ldI32o(f, FLD.Proto_sizek);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++) {
        let o = cptr.add(cptr.ldPtro(f, FLD.Proto_k), i, 16);
        let tt = (((cptr.ld1uo((o), FLD.TValue_tt_))) & 63);
        (yield* dumpByte(D, tt));
        switch (tt) {
            case 19:
            (yield* dumpNumber(D, (cptr.ldF64(((o))))));
            break;
            case 3:
            (yield* dumpInteger(D, (cptr.ldI64(((o))))));
            break;
            case 4:
            case 20:
            (yield* dumpString(D, ((((((cptr.ldPtr(((o)))))))))));
            break;
            default:
            (void 0);
        }
    }
}

/** C ref: ldump.c:138 — @param {CPtr} D @param {CPtr} f */
function* dumpProtos(D, f) {
    let i;
    let n = cptr.ldI32o(f, FLD.Proto_sizep);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++)
        (yield* dumpFunction(D, cptr.ldPtro(cptr.ldPtro(f, FLD.Proto_p), i, 8), cptr.ldPtro(f, FLD.Proto_source)));
}

/** C ref: ldump.c:147 — @param {CPtr} D @param {CPtr} f */
function* dumpUpvalues(D, f) {
    let i;
    let n = cptr.ldI32o(f, FLD.Proto_sizeupvalues);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++) {
        (yield* dumpByte(D, cptr.ld1uo2(cptr.ldPtro(f, FLD.Proto_upvalues), i, 16, FLD.Upvaldesc_instack)));
        (yield* dumpByte(D, cptr.ld1uo2(cptr.ldPtro(f, FLD.Proto_upvalues), i, 16, FLD.Upvaldesc_idx)));
        (yield* dumpByte(D, cptr.ld1uo2(cptr.ldPtro(f, FLD.Proto_upvalues), i, 16, FLD.Upvaldesc_kind)));
    }
}

/** C ref: ldump.c:158 — @param {CPtr} D @param {CPtr} f */
function* dumpDebug(D, f) {
    let i;
    let n;
    n = (cptr.ldI32o(D, FLD.DumpState_strip)) ? 0 : cptr.ldI32o(f, FLD.Proto_sizelineinfo);
    (yield* dumpInt(D, n));
    (yield* dumpBlock(D, cptr.ldPtro(f, FLD.Proto_lineinfo), BigInt.asUintN(64, BigInt.asUintN(64, BigInt((n))) * 1n)));
    n = (cptr.ldI32o(D, FLD.DumpState_strip)) ? 0 : cptr.ldI32o(f, FLD.Proto_sizeabslineinfo);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++) {
        (yield* dumpInt(D, cptr.ldI32o(cptr.ldPtro(f, FLD.Proto_abslineinfo), i, 8)));
        (yield* dumpInt(D, cptr.ldI32o2(cptr.ldPtro(f, FLD.Proto_abslineinfo), i, 8, FLD.AbsLineInfo_line)));
    }
    n = (cptr.ldI32o(D, FLD.DumpState_strip)) ? 0 : cptr.ldI32o(f, FLD.Proto_sizelocvars);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++) {
        (yield* dumpString(D, cptr.ldPtro(cptr.ldPtro(f, FLD.Proto_locvars), i, 16)));
        (yield* dumpInt(D, cptr.ldI32o2(cptr.ldPtro(f, FLD.Proto_locvars), i, 16, FLD.LocVar_startpc)));
        (yield* dumpInt(D, cptr.ldI32o2(cptr.ldPtro(f, FLD.Proto_locvars), i, 16, FLD.LocVar_endpc)));
    }
    n = (cptr.ldI32o(D, FLD.DumpState_strip)) ? 0 : cptr.ldI32o(f, FLD.Proto_sizeupvalues);
    (yield* dumpInt(D, n));
    for (i = 0; i < n; i++)
        (yield* dumpString(D, cptr.ldPtro(cptr.ldPtro(f, FLD.Proto_upvalues), i, 16)));
}

/** C ref: ldump.c:183 — @param {CPtr} D @param {CPtr} f @param {CPtr} psource */
function* dumpFunction(D, f, psource) {
    if (cptr.ldI32o(D, FLD.DumpState_strip) || cptr.eq(cptr.ldPtro(f, FLD.Proto_source), psource))
        (yield* dumpString(D, null));
    else
        (yield* dumpString(D, cptr.ldPtro(f, FLD.Proto_source)));
    (yield* dumpInt(D, cptr.ldI32o(f, FLD.Proto_linedefined)));
    (yield* dumpInt(D, cptr.ldI32o(f, FLD.Proto_lastlinedefined)));
    (yield* dumpByte(D, cptr.ld1uo(f, FLD.Proto_numparams)));
    (yield* dumpByte(D, cptr.ld1uo(f, FLD.Proto_is_vararg)));
    (yield* dumpByte(D, cptr.ld1uo(f, FLD.Proto_maxstacksize)));
    (yield* dumpCode(D, f));
    (yield* dumpConstants(D, f));
    (yield* dumpUpvalues(D, f));
    (yield* dumpProtos(D, f));
    (yield* dumpDebug(D, f));
}

/** C ref: ldump.c:201 — @param {CPtr} D */
function* dumpHeader(D) {
    (yield* dumpBlock(D, __sl0, 4n));
    (yield* dumpByte(D, 84));
    (yield* dumpByte(D, 0));
    (yield* dumpBlock(D, __sl1, 6n));
    (yield* dumpByte(D, 4));
    (yield* dumpByte(D, 8));
    (yield* dumpByte(D, 8));
    (yield* dumpInteger(D, 22136n));
    (yield* dumpNumber(D, (((370.5)))));
}

/** C ref: ldump.c:217 — @param {CPtr} L @param {CPtr} f @param {CPtr} w @param {CPtr} data @param {CInt} strip @returns {CInt} */
export function* luaU_dump(L, f, w, data, strip) {
    let D = cptr.alloc(32);
    cptr.stPtr(D, L);
    cptr.stPtro(D, FLD.DumpState_writer, w);
    cptr.stPtro(D, FLD.DumpState_data, data);
    cptr.stI32o(D, FLD.DumpState_strip, strip);
    cptr.stI32o(D, FLD.DumpState_status, 0);
    (yield* dumpHeader(D));
    (yield* dumpByte(D, cptr.ldI32o(f, FLD.Proto_sizeupvalues)));
    (yield* dumpFunction(D, f, null));
    return cptr.ldI32o(D, FLD.DumpState_status);
}
