// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/loadlib.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/lib/lua-5.4.8/src/loadlib.c
// Input sha256: f21cafa3258669d6f8c4f09195c654a4a588ab402f5e976c731918658b747a5b
// Transpiler: tools/c2js c2js emit v1+batch

import * as cptr from '../cptr.js';
import * as FLD from './nhfield.js';
import { lua_callk, lua_copy, lua_createtable, lua_getfield, lua_isstring, lua_pushboolean, lua_pushcclosure, lua_pushfstring, lua_pushlightuserdata, lua_pushlstring, lua_pushnil, lua_pushstring, lua_pushvalue, lua_rawgeti, lua_rawseti, lua_rotate, lua_setfield, lua_setmetatable, lua_settop, lua_toboolean, lua_tolstring, lua_touserdata, lua_type } from './lapi.js';
import { luaL_addgsub, luaL_addlstring, luaL_addstring, luaL_addvalue, luaL_buffinit, luaL_checklstring, luaL_checkversion_, luaL_error, luaL_getsubtable, luaL_gsub, luaL_len, luaL_loadfilex, luaL_optlstring, luaL_prepbuffsize, luaL_pushresult, luaL_setfuncs } from './lauxlib.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $luaL_Buffer_n = FLD.luaL_Buffer_n, $luaL_Buffer_size = FLD.luaL_Buffer_size,
    $luaL_Reg_func = FLD.luaL_Reg_func, $sizeof_luaL_Reg = FLD.sizeof_luaL_Reg;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_clibs = cptr.lit("_CLIBS");
const __s_lua_noenv = cptr.lit("LUA_NOENV");
const __s_s_s = cptr.lit("%s%s");
const __s_5_4 = cptr.lit("_5_4");
const __s_semi2 = cptr.lit(";;");
const __s_semi = cptr.lit(";");
const __s_open = cptr.lit("open");
const __s_init = cptr.lit("init");
const __s_r = cptr.lit("r");
const __s_no_file = cptr.lit("no file '");
const __s_no_file__2 = cptr.lit("'\n\tno file '");
const __s_apos = cptr.lit("'");
const __s_query = cptr.lit("?");
const __s_dot = cptr.lit(".");
const __s_slash = cptr.lit("/");
const __s_package_s_must_be_a_string = cptr.lit("'package.%s' must be a string");
const __s_error_loading_module_s_from_file_s_s = cptr.lit("error loading module '%s' from file '%s':\n\t%s");
const __s_path = cptr.lit("path");
const __s_us = cptr.lit("_");
const __s_dash = cptr.lit("-");
const __s_luaopen_s = cptr.lit("luaopen_%s");
const __s_cpath = cptr.lit("cpath");
const __s_no_module_s_in_file_s = cptr.lit("no module '%s' in file '%s'");
const __s_preload = cptr.lit("_PRELOAD");
const __s_no_field_package_preload_s = cptr.lit("no field package.preload['%s']");
const __s_preload__2 = cptr.lit(":preload:");
const __s_searchers = cptr.lit("searchers");
const __s_package_searchers_must_be_a_table = cptr.lit("'package.searchers' must be a table");
const __s_nl_tab = cptr.lit("\n\t");
const __s_module_s_not_found_s = cptr.lit("module '%s' not found:%s");
const __s_loaded = cptr.lit("_LOADED");
const __s_loadlib = cptr.lit("loadlib");
const __s_searchpath = cptr.lit("searchpath");
const __s_preload__3 = cptr.lit("preload");
const __s_loaded__2 = cptr.lit("loaded");
const __s_require = cptr.lit("require");
const __s_gc = cptr.lit("__gc");
const __s_lua_path = cptr.lit("LUA_PATH");
const __s_usr_local_share_lua_5_4_lua_usr_local = cptr.lit("/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua");
const __s_lua_cpath = cptr.lit("LUA_CPATH");
const __s_usr_local_lib_lua_5_4_so_usr_local_lib = cptr.lit("/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so;./?.so");
const __s_slash_nl_semi_nl_query_nl_bang_nl_dash = cptr.lit("/\n;\n?\n!\n-\n");
const __s_config = cptr.lit("config");

/** C ref: loadlib.c:53 — char * */
let CLIBS = __s_clibs;

/** C ref: loadlib.c:65 — typedef voidf (type alias only, no runtime output) */

/** C ref: loadlib.c:119 — @param {CPtr<void>} lib */
function lsys_unloadlib(lib) {
    dlclose(lib);
}

/** C ref: loadlib.c:124 — @param {CPtr<lua_State>} L @param {CPtr<char>} path @param {CInt} seeglb @returns {CPtr<void>} */
function* lsys_load(L, path, seeglb) {
    let lib = dlopen(path, 2 | (seeglb ? 8 : 4));
    if ((__builtin_expect(BigInt(((cptr.eq(lib, (null))) != 0)), 0n)))
        (yield* lua_pushstring(L, dlerror()));
    return lib;
}

/** C ref: loadlib.c:132 — @param {CPtr<lua_State>} L @param {CPtr<void>} lib @param {CPtr<char>} sym @returns {*} */
function* lsys_sym(L, lib, sym) {
    let f = ((dlsym(lib, sym)));
    if ((__builtin_expect(BigInt(((f === (null)) != 0)), 0n)))
        (yield* lua_pushstring(L, dlerror()));
    return f;
}

/** C ref: loadlib.c:276 — @param {CPtr<lua_State>} L @returns {CInt} */
function* noenv(L) {
    let b;
    (yield* lua_getfield(L, -1001000, __s_lua_noenv));
    b = lua_toboolean(L, -1);
    (yield* lua_settop(L, -2));
    return b;
}

/** C ref: loadlib.c:288 — @param {CPtr<lua_State>} L @param {CPtr<char>} fieldname @param {CPtr<char>} envname @param {CPtr<char>} dft */
function* setpath(L, fieldname, envname, dft) {
    let dftmark;
    let nver = (yield* lua_pushfstring(L, __s_s_s, envname, __s_5_4));
    let path = getenv(nver);
    if (cptr.eq(path, (null)))
        path = getenv(envname);
    if (cptr.eq(path, (null)) || (yield* noenv(L)))
        (yield* lua_pushstring(L, dft));
    else if (cptr.eq((dftmark = cptr.strstr(path, __s_semi2)), (null)))
        (yield* lua_pushstring(L, path));
    else {
        let len = cptr.strlen(path);
        let b = cptr.alloc(1056);
        (yield* luaL_buffinit(L, b));
        if (cptr.cmp(path, dftmark) < 0) {
            (yield* luaL_addlstring(b, path, BigInt.asUintN(64, cptr.diff(dftmark, path))));
            (void (cptr.ldU64o((b), $luaL_Buffer_n) < cptr.ldU64o((b), $luaL_Buffer_size) || (yield* luaL_prepbuffsize((b), 1n)) ? 1 : 0), (cptr.st1o(cptr.ldPtr((b)), (cptr.stU64o((b), $luaL_Buffer_n, cptr.ldU64o((b), $luaL_Buffer_n) + 1n)) - (1n), (cptr.ld1s(__s_semi)))));
        }
        (yield* luaL_addstring(b, dft));
        if (cptr.cmp(dftmark, cptr.add(cptr.add(path, len), -(2))) < 0) {
            (void (cptr.ldU64o((b), $luaL_Buffer_n) < cptr.ldU64o((b), $luaL_Buffer_size) || (yield* luaL_prepbuffsize((b), 1n)) ? 1 : 0), (cptr.st1o(cptr.ldPtr((b)), (cptr.stU64o((b), $luaL_Buffer_n, cptr.ldU64o((b), $luaL_Buffer_n) + 1n)) - (1n), (cptr.ld1s(__s_semi)))));
            (yield* luaL_addlstring(b, cptr.add(dftmark, 2), BigInt.asUintN(64, cptr.diff((cptr.add(cptr.add(path, len), -(2))), dftmark))));
        }
        (yield* luaL_pushresult(b));
    }
    (void 0);
    (yield* lua_setfield(L, -3, fieldname));
    (yield* lua_settop(L, -2));
}

/** C ref: loadlib.c:326 — @param {CPtr<lua_State>} L @param {CPtr<char>} path @returns {CPtr<void>} */
function* checkclib(L, path) {
    let plib;
    (yield* lua_getfield(L, -1001000, CLIBS));
    (yield* lua_getfield(L, -1, path));
    plib = lua_touserdata(L, -1);
    (yield* lua_settop(L, -3));
    return plib;
}

/** C ref: loadlib.c:340 — @param {CPtr<lua_State>} L @param {CPtr<char>} path @param {CPtr<void>} plib */
function* addtoclib(L, path, plib) {
    (yield* lua_getfield(L, -1001000, CLIBS));
    (yield* lua_pushlightuserdata(L, plib));
    (yield* lua_pushvalue(L, -1));
    (yield* lua_setfield(L, -3, path));
    (yield* lua_rawseti(L, -2, BigInt.asIntN(64, (yield* luaL_len(L, -2)) + 1n)));
    (yield* lua_settop(L, -2));
}

/** C ref: loadlib.c:354 — @param {CPtr<lua_State>} L @returns {CInt} */
function* gctm(L) {
    let n = (yield* luaL_len(L, 1));
    for (; n >= 1n; n--) {
        (yield* lua_rawgeti(L, 1, n));
        lsys_unloadlib(lua_touserdata(L, -1));
        (yield* lua_settop(L, -2));
    }
    return 0;
}

/** C ref: loadlib.c:381 — @param {CPtr<lua_State>} L @param {CPtr<char>} path @param {CPtr<char>} sym @returns {CInt} */
function* lookforfunc(L, path, sym) {
    let reg = (yield* checkclib(L, path));
    if (cptr.eq(reg, (null))) {
        reg = (yield* lsys_load(L, path, cptr.ld1s(sym) == 42));
        if (cptr.eq(reg, (null)))
            return 1;
        (yield* addtoclib(L, path, reg));
    }
    if (cptr.ld1s(sym) == 42) {
        (yield* lua_pushboolean(L, 1));
        return 0;
    } else {
        let f = (yield* lsys_sym(L, reg, sym));
        if (f === (null))
            return 2;
        (yield* lua_pushcclosure(L, (f), 0));
        return 0;
    }
}

/** C ref: loadlib.c:402 — @param {CPtr<lua_State>} L @returns {CInt} */
function* ll_loadlib(L) {
    let path = ((yield* luaL_checklstring(L, 1, null)));
    let init = ((yield* luaL_checklstring(L, 2, null)));
    let stat = (yield* lookforfunc(L, path, init));
    if ((__builtin_expect(BigInt(((stat == 0) != 0)), 1n)))
        return 1;
    else {
        (yield* lua_pushnil(L));
        lua_rotate(L, -2, 1);
        (yield* lua_pushstring(L, (stat == 1) ? __s_open : __s_init));
        return 3;
    }
}

/** C ref: loadlib.c:425 — @param {CPtr<char>} filename @returns {CInt} */
function readable(filename) {
    let f = fopen(filename, __s_r);
    if (cptr.eq(f, (null)))
        return 0;
    fclose(f);
    return 1;
}

/** C ref: loadlib.c:438 — @param {CPtr<char *>} path @param {CPtr<char>} end @returns {CPtr<char>} */
function getnextfilename(path, end) {
    let sep;
    let name = cptr.ldPtr(path);
    if (cptr.eq(name, end))
        return null;
    else if (cptr.ld1s(name) == 0) {
        cptr.st1(name, cptr.ld1s(__s_semi));
        name = cptr.add(name, 1);
    }
    sep = cptr.strchr(name, cptr.ld1s(__s_semi));
    if (cptr.eq(sep, (null)))
        sep = end;
    cptr.st1(sep, 0);
    cptr.stPtr(path, sep);
    return name;
}

/** C ref: loadlib.c:462 — @param {CPtr<lua_State>} L @param {CPtr<char>} path */
function* pusherrornotfound(L, path) {
    let b = cptr.alloc(1056);
    (yield* luaL_buffinit(L, b));
    (yield* luaL_addstring(b, __s_no_file));
    (yield* luaL_addgsub(b, path, __s_semi, __s_no_file__2));
    (yield* luaL_addstring(b, __s_apos));
    (yield* luaL_pushresult(b));
}

/** C ref: loadlib.c:472 — @param {CPtr<lua_State>} L @param {CPtr<char>} name @param {CPtr<char>} path @param {CPtr<char>} sep @param {CPtr<char>} dirsep @returns {CPtr<char>} */
function* searchpath(L, name, path, sep, dirsep) {
    let buff = cptr.alloc(1056);
    let pathname = cptr.box(0);
    let endpathname;
    let filename;
    if (cptr.ld1s(sep) != 0 && !cptr.eq(cptr.strchr(name, cptr.ld1s(sep)), (null)))
        name = (yield* luaL_gsub(L, name, sep, dirsep));
    (yield* luaL_buffinit(L, buff));
    (yield* luaL_addgsub(buff, path, __s_query, name));
    (void (cptr.ldU64o((buff), $luaL_Buffer_n) < cptr.ldU64o((buff), $luaL_Buffer_size) || (yield* luaL_prepbuffsize((buff), 1n)) ? 1 : 0), (cptr.st1o(cptr.ldPtr((buff)), (cptr.stU64o((buff), $luaL_Buffer_n, cptr.ldU64o((buff), $luaL_Buffer_n) + 1n)) - (1n), 0)));
    pathname.v = (cptr.ldPtr((buff)));
    endpathname = cptr.add(cptr.add(pathname.v, (cptr.ldU64o((buff), $luaL_Buffer_n))), -(1));
    while (!cptr.eq((filename = getnextfilename(pathname, endpathname)), (null))) {
        if (readable(filename))
            return (yield* lua_pushstring(L, filename));
    }
    (yield* luaL_pushresult(buff));
    (yield* pusherrornotfound(L, (yield* lua_tolstring(L, -1, null))));
    return null;
}

/** C ref: loadlib.c:499 — @param {CPtr<lua_State>} L @returns {CInt} */
function* ll_searchpath(L) {
    let f = (yield* searchpath(L, ((yield* luaL_checklstring(L, 1, null))), ((yield* luaL_checklstring(L, 2, null))), ((yield* luaL_optlstring(L, 3, (__s_dot), null))), ((yield* luaL_optlstring(L, 4, (__s_slash), null)))));
    if (!cptr.eq(f, (null)))
        return 1;
    else {
        (yield* lua_pushnil(L));
        lua_rotate(L, -2, 1);
        return 2;
    }
}

/** C ref: loadlib.c:513 — @param {CPtr<lua_State>} L @param {CPtr<char>} name @param {CPtr<char>} pname @param {CPtr<char>} dirsep @returns {CPtr<char>} */
function* findfile(L, name, pname, dirsep) {
    let path;
    (yield* lua_getfield(L, -1001001, pname));
    path = (yield* lua_tolstring(L, -1, null));
    if ((__builtin_expect(BigInt(((cptr.eq(path, (null))) != 0)), 0n)))
        (yield* luaL_error(L, __s_package_s_must_be_a_string, pname));
    return (yield* searchpath(L, name, path, __s_dot, dirsep));
}

/** C ref: loadlib.c:525 — @param {CPtr<lua_State>} L @param {CInt} stat @param {CPtr<char>} filename @returns {CInt} */
function* checkload(L, stat, filename) {
    if ((__builtin_expect(BigInt(((stat) != 0)), 1n))) {
        (yield* lua_pushstring(L, filename));
        return 2;
    } else
        return (yield* luaL_error(L, __s_error_loading_module_s_from_file_s_s, (yield* lua_tolstring(L, 1, null)), filename, (yield* lua_tolstring(L, -1, null))));
}

/** C ref: loadlib.c:536 — @param {CPtr<lua_State>} L @returns {CInt} */
function* searcher_Lua(L) {
    let filename;
    let name = ((yield* luaL_checklstring(L, 1, null)));
    filename = (yield* findfile(L, name, __s_path, __s_slash));
    if (cptr.eq(filename, (null)))
        return 1;
    return (yield* checkload(L, ((yield* luaL_loadfilex(L, filename, null)) == 0), filename));
}

/** C ref: loadlib.c:553 — @param {CPtr<lua_State>} L @param {CPtr<char>} filename @param {CPtr<char>} modname @returns {CInt} */
function* loadfunc(L, filename, modname) {
    let openfunc;
    let mark;
    modname = (yield* luaL_gsub(L, modname, __s_dot, __s_us));
    mark = cptr.strchr(modname, cptr.ld1s(__s_dash));
    if (mark) {
        let stat;
        openfunc = (yield* lua_pushlstring(L, modname, BigInt.asUintN(64, cptr.diff(mark, modname))));
        openfunc = (yield* lua_pushfstring(L, __s_luaopen_s, openfunc));
        stat = (yield* lookforfunc(L, filename, openfunc));
        if (stat != 2)
            return stat;
        modname = cptr.add(mark, 1);
    }
    openfunc = (yield* lua_pushfstring(L, __s_luaopen_s, modname));
    return (yield* lookforfunc(L, filename, openfunc));
}

/** C ref: loadlib.c:571 — @param {CPtr<lua_State>} L @returns {CInt} */
function* searcher_C(L) {
    let name = ((yield* luaL_checklstring(L, 1, null)));
    let filename = (yield* findfile(L, name, __s_cpath, __s_slash));
    if (cptr.eq(filename, (null)))
        return 1;
    return (yield* checkload(L, ((yield* loadfunc(L, filename, name)) == 0), filename));
}

/** C ref: loadlib.c:579 — @param {CPtr<lua_State>} L @returns {CInt} */
function* searcher_Croot(L) {
    let filename;
    let name = ((yield* luaL_checklstring(L, 1, null)));
    let p = cptr.strchr(name, 46);
    let stat;
    if (cptr.eq(p, (null)))
        return 0;
    (yield* lua_pushlstring(L, name, BigInt.asUintN(64, cptr.diff(p, name))));
    filename = (yield* findfile(L, (yield* lua_tolstring(L, -1, null)), __s_cpath, __s_slash));
    if (cptr.eq(filename, (null)))
        return 1;
    if ((stat = (yield* loadfunc(L, filename, name))) != 0) {
        if (stat != 2)
            return (yield* checkload(L, 0, filename));
        else {
            (yield* lua_pushfstring(L, __s_no_module_s_in_file_s, name, filename));
            return 1;
        }
    }
    (yield* lua_pushstring(L, filename));
    return 2;
}

/** C ref: loadlib.c:601 — @param {CPtr<lua_State>} L @returns {CInt} */
function* searcher_preload(L) {
    let name = ((yield* luaL_checklstring(L, 1, null)));
    (yield* lua_getfield(L, -1001000, __s_preload));
    if ((yield* lua_getfield(L, -1, name)) == 0) {
        (yield* lua_pushfstring(L, __s_no_field_package_preload_s, name));
        return 1;
    } else {
        (yield* lua_pushstring(L, __s_preload__2));
        return 2;
    }
}

/** C ref: loadlib.c:615 — @param {CPtr<lua_State>} L @param {CPtr<char>} name */
function* findloader(L, name) {
    let i;
    let msg = cptr.alloc(1056);
    if ((__builtin_expect(BigInt((((yield* lua_getfield(L, -1001001, __s_searchers)) != 5) != 0)), 0n)))
        (yield* luaL_error(L, __s_package_searchers_must_be_a_table));
    (yield* luaL_buffinit(L, msg));
    for (i = 1; ; i++) {
        (yield* luaL_addstring(msg, __s_nl_tab));
        if ((__builtin_expect(BigInt((((yield* lua_rawgeti(L, 3, BigInt(i))) == 0) != 0)), 0n))) {
            (yield* lua_settop(L, -2));
            (cptr.stU64o((msg), $luaL_Buffer_n, cptr.ldU64o((msg), $luaL_Buffer_n) - 2n));
            (yield* luaL_pushresult(msg));
            (yield* luaL_error(L, __s_module_s_not_found_s, name, (yield* lua_tolstring(L, -1, null))));
        }
        (yield* lua_pushstring(L, name));
        (yield* lua_callk(L, 1, 2, 0n, null));
        if ((lua_type(L, -2) == 6))
            return;
        else if (lua_isstring(L, -2)) {
            (yield* lua_settop(L, -2));
            (yield* luaL_addvalue(msg));
        } else {
            (yield* lua_settop(L, -3));
            (cptr.stU64o((msg), $luaL_Buffer_n, cptr.ldU64o((msg), $luaL_Buffer_n) - 2n));
        }
    }
}

/** C ref: loadlib.c:648 — @param {CPtr<lua_State>} L @returns {CInt} */
function* ll_require(L) {
    let name = ((yield* luaL_checklstring(L, 1, null)));
    (yield* lua_settop(L, 1));
    (yield* lua_getfield(L, -1001000, __s_loaded));
    (yield* lua_getfield(L, 2, name));
    if (lua_toboolean(L, -1))
        return 1;
    (yield* lua_settop(L, -2));
    (yield* findloader(L, name));
    lua_rotate(L, -2, 1);
    (yield* lua_pushvalue(L, 1));
    (yield* lua_pushvalue(L, -3));
    (yield* lua_callk(L, 2, 1, 0n, null));
    if (!(lua_type(L, -1) == 0))
        (yield* lua_setfield(L, 2, name));
    else
        (yield* lua_settop(L, -2));
    if ((yield* lua_getfield(L, 2, name)) == 0) {
        (yield* lua_pushboolean(L, 1));
        lua_copy(L, -1, -2);
        (yield* lua_setfield(L, 2, name));
    }
    lua_rotate(L, -2, 1);
    return 2;
}

/** C ref: loadlib.c:682 — luaL_Reg[8] */
const pk_funcs = cptr.alloc(8 * $sizeof_luaL_Reg);
cptr.stPtro(pk_funcs, 0, __s_loadlib);
cptr.stPtro(pk_funcs, 0 + $luaL_Reg_func, ll_loadlib);
cptr.stPtro(pk_funcs, 16, __s_searchpath);
cptr.stPtro(pk_funcs, 16 + $luaL_Reg_func, ll_searchpath);
cptr.stPtro(pk_funcs, 32, __s_preload__3);
cptr.stPtro(pk_funcs, 32 + $luaL_Reg_func, null);
cptr.stPtro(pk_funcs, 48, __s_cpath);
cptr.stPtro(pk_funcs, 48 + $luaL_Reg_func, null);
cptr.stPtro(pk_funcs, 64, __s_path);
cptr.stPtro(pk_funcs, 64 + $luaL_Reg_func, null);
cptr.stPtro(pk_funcs, 80, __s_searchers);
cptr.stPtro(pk_funcs, 80 + $luaL_Reg_func, null);
cptr.stPtro(pk_funcs, 96, __s_loaded__2);
cptr.stPtro(pk_funcs, 96 + $luaL_Reg_func, null);
cptr.stPtro(pk_funcs, 112, null);
cptr.stPtro(pk_funcs, 112 + $luaL_Reg_func, null);

/** C ref: loadlib.c:695 — luaL_Reg[2] */
const ll_funcs = cptr.alloc(2 * $sizeof_luaL_Reg);
cptr.stPtro(ll_funcs, 0, __s_require);
cptr.stPtro(ll_funcs, 0 + $luaL_Reg_func, ll_require);
cptr.stPtro(ll_funcs, 16, null);
cptr.stPtro(ll_funcs, 16 + $luaL_Reg_func, null);

const __static_createsearcherstable_searchers = cptr.alloc(5 * 8);
cptr.stPtro(__static_createsearcherstable_searchers, 0, searcher_preload);
cptr.stPtro(__static_createsearcherstable_searchers, 8, searcher_Lua);
cptr.stPtro(__static_createsearcherstable_searchers, 16, searcher_C);
cptr.stPtro(__static_createsearcherstable_searchers, 24, searcher_Croot);
cptr.stPtro(__static_createsearcherstable_searchers, 32, null); /** C ref: loadlib.c:702 — void *[5] (function-static) */

/** C ref: loadlib.c:701 — @param {CPtr<lua_State>} L */
function* createsearcherstable(L) {
    let i;
    (yield* lua_createtable(L, Number(BigInt.asIntN(32, BigInt.asUintN(64, 40n / 8n - 1n))), 0));
    for (i = 0; cptr.ldPtro(__static_createsearcherstable_searchers, i, 8) !== (null); i++) {
        (yield* lua_pushvalue(L, -2));
        (yield* lua_pushcclosure(L, cptr.ldPtro(__static_createsearcherstable_searchers, i, 8), 1));
        (yield* lua_rawseti(L, -2, BigInt(((i + 1) | 0))));
    }
    (yield* lua_setfield(L, -2, __s_searchers));
}

/** C ref: loadlib.c:726 — @param {CPtr<lua_State>} L */
function* createclibstable(L) {
    (yield* luaL_getsubtable(L, -1001000, CLIBS));
    (yield* lua_createtable(L, 0, 1));
    (yield* lua_pushcclosure(L, (gctm), 0));
    (yield* lua_setfield(L, -2, __s_gc));
    (yield* lua_setmetatable(L, -2));
}

/** C ref: loadlib.c:735 — @param {CPtr<lua_State>} L @returns {CInt} */
export function* luaopen_package(L) {
    (yield* createclibstable(L));
    ((yield* luaL_checkversion_(L, 504, 136n)), (yield* lua_createtable(L, 0, Number(BigInt.asIntN(32, BigInt.asUintN(64, 128n / 16n - 1n))))), (yield* luaL_setfuncs(L, pk_funcs, 0)));
    (yield* createsearcherstable(L));
    (yield* setpath(L, __s_path, __s_lua_path, __s_usr_local_share_lua_5_4_lua_usr_local));
    (yield* setpath(L, __s_cpath, __s_lua_cpath, __s_usr_local_lib_lua_5_4_so_usr_local_lib));
    (yield* lua_pushstring(L, __s_slash_nl_semi_nl_query_nl_bang_nl_dash));
    (yield* lua_setfield(L, -2, __s_config));
    (yield* luaL_getsubtable(L, -1001000, __s_loaded));
    (yield* lua_setfield(L, -2, __s_loaded__2));
    (yield* luaL_getsubtable(L, -1001000, __s_preload));
    (yield* lua_setfield(L, -2, __s_preload__3));
    (void (yield* lua_rawgeti(L, -1001000, 2n)));
    (yield* lua_pushvalue(L, -2));
    (yield* luaL_setfuncs(L, ll_funcs, 1));
    (yield* lua_settop(L, -2));
    return 1;
}
