// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/nhrng.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// One function per PRNG entry point the recorder's hack.h instruments:
// the macro body, once, instead of at all 2,717 of its call sites (see
// rngLogCall() in tools/c2js/emit.mjs).
// Transpiler: tools/c2js c2js emit v1+batch
//
// The log this writes is SCORED — getRngLog() is what the judge reads — so
// the body performs exactly the three calls the macro did, in the macro's
// order. A site takes the helper only when its argument neither writes nor
// draws, because a call evaluates its argument before the body and C
// evaluated it after rng_log_set_caller.

import { d, rn2, rnd, rne, rng_log_enabled, rng_log_set_caller, rnl, rnz } from './rnd.js';

/** C: include/hack.h — the rng-log `d(a1, a2)` macro body */
export function d_at(file, line, func, a1, a2) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), d(a1, a2)) : d(a1, a2);
}
/** C: include/hack.h — the rng-log `rn2(x)` macro body */
export function rn2_at(file, line, func, x) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), rn2(x)) : rn2(x);
}
/** C: include/hack.h — the rng-log `rnd(x)` macro body */
export function rnd_at(file, line, func, x) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), rnd(x)) : rnd(x);
}
/** C: include/hack.h — the rng-log `rne(x)` macro body */
export function rne_at(file, line, func, x) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), rne(x)) : rne(x);
}
/** C: include/hack.h — the rng-log `rnl(x)` macro body */
export function rnl_at(file, line, func, x) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), rnl(x)) : rnl(x);
}
/** C: include/hack.h — the rng-log `rnz(x)` macro body */
export function rnz_at(file, line, func, x) {
    return rng_log_enabled() ? (rng_log_set_caller(file, line, func), rnz(x)) : rnz(x);
}
