// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/quest.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/quest.c
// Input sha256: 4c4257e20c62c27800381157d15e9e8e7205f075039f3ee3c39d99660f3ae50a
// Transpiler: tools/c2js c2js emit v1+batch

import { schar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import * as FLD from './nhfield.js';
import { helpless } from './nhmacrofn.js';
import { Deaf, quest_dnum, wizard } from './nhprop.js';
import { flags, gf, gi, svc, svd, svq, u } from './decl.js';
import { com_pager, find_quest_artifact, is_quest_artifact, qt_pager } from './questpgr.js';
import { Is_special, dungeon_branch, on_level, remdun_mapseen } from './dungeon.js';
import { observe_object } from './o_init.js';
import { adjalign, exercise } from './attrib.js';
import { You, impossible, livelog_printf, pline, verbalize } from './pline.js';
import { align_str } from './insight.js';
import { yn_function } from './cmd.js';
import { nomul } from './hack.js';
import { schedule_goto } from './do.js';
import { deltrap } from './trap.js';
import { carrying, fully_identify_obj, update_inventory } from './invent.js';
import { the, xname } from './objnam.js';
import { Monnam, mon_nam, noit_mon_nam } from './do_name.js';
import { rn2, rng_log_enabled, rng_log_set_caller } from './rnd.js';
import { create_gas_cloud } from './region.js';
import { mons } from './monst.js';
import { canseemon } from './display.js';
import { angry_guards, monnear, setmangry } from './mon.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $align_record = FLD.align_record, $branch_end1 = FLD.branch_end1, $branch_end2 = FLD.branch_end2,
    $context_info_mon_moving = FLD.context_info_mon_moving, $d_level_dlevel = FLD.d_level_dlevel,
    $dgn_topology_d_nemesis_level = FLD.dgn_topology_d_nemesis_level,
    $dgn_topology_d_qlocate_level = FLD.dgn_topology_d_qlocate_level,
    $dgn_topology_d_qstart_level = FLD.dgn_topology_d_qstart_level,
    $dgn_topology_d_quest_dnum = FLD.dgn_topology_d_quest_dnum, $flag_debug = FLD.flag_debug,
    $instance_globals_i_invent = FLD.instance_globals_i_invent,
    $instance_globals_saved_d_dungeon_topology = FLD.instance_globals_saved_d_dungeon_topology,
    $monst_data = FLD.monst_data, $monst_m_id = FLD.monst_m_id, $monst_mcanmove = FLD.monst_mcanmove,
    $monst_mpeaceful = FLD.monst_mpeaceful, $monst_msleeping = FLD.monst_msleeping,
    $monst_mstrategy = FLD.monst_mstrategy, $obj_otyp = FLD.obj_otyp, $permonst_msound = FLD.permonst_msound,
    $prop_intrinsic = FLD.prop_intrinsic, $q_score_cheater = FLD.q_score_cheater,
    $q_score_first_locate = FLD.q_score_first_locate, $q_score_got_quest = FLD.q_score_got_quest,
    $q_score_got_thanks = FLD.q_score_got_thanks, $q_score_in_battle = FLD.q_score_in_battle,
    $q_score_killed_leader = FLD.q_score_killed_leader, $q_score_killed_nemesis = FLD.q_score_killed_nemesis,
    $q_score_leader_m_id = FLD.q_score_leader_m_id, $q_score_made_goal = FLD.q_score_made_goal,
    $q_score_met_leader = FLD.q_score_met_leader, $q_score_met_nemesis = FLD.q_score_met_nemesis,
    $q_score_not_ready = FLD.q_score_not_ready, $q_score_pissed_off = FLD.q_score_pissed_off,
    $q_score_touched_artifact = FLD.q_score_touched_artifact, $sizeof_permonst = FLD.sizeof_permonst,
    $sizeof_prop = FLD.sizeof_prop, $trap_ttyp = FLD.trap_ttyp, $u_event_qcompleted = FLD.u_event_qcompleted,
    $u_event_qexpelled = FLD.u_event_qexpelled, $u_have_questart = FLD.u_have_questart,
    $u_roleplay_deaf = FLD.u_roleplay_deaf, $you_ualign = FLD.you_ualign,
    $you_ualignbase = FLD.you_ualignbase, $you_uevent = FLD.you_uevent, $you_uhave = FLD.you_uhave,
    $you_ulevel = FLD.you_ulevel, $you_uprops = FLD.you_uprops, $you_uroleplay = FLD.you_uroleplay,
    $you_uy = FLD.you_uy, $you_uz = FLD.you_uz, $you_uz0 = FLD.you_uz0;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_firsttime = cptr.lit("firsttime");
const __s_nexttime = cptr.lit("nexttime");
const __s_othertime = cptr.lit("othertime");
const __s_locate_first = cptr.lit("locate_first");
const __s_locate_next = cptr.lit("locate_next");
const __s_goal_first = cptr.lit("goal_first");
const __s_goal_next = cptr.lit("goal_next");
const __s_goal_alt = cptr.lit("goal_alt");
const __s_killed_nemesis = cptr.lit("killed_nemesis");
const __s_gotit = cptr.lit("gotit");
const __s_are_currently_s_instead_of_s = cptr.lit("are currently %s instead of %s.");
const __s_have_converted = cptr.lit("have converted.");
const __s_are_currently_d_and_require_d = cptr.lit("are currently %d and require %d.");
const __s_adjust = cptr.lit("adjust?");
const __s_the_quest = cptr.lit("The Quest");
const __s_quest_portal_already_gone = cptr.lit("quest portal already gone?");
const __s_hasamulet = cptr.lit("hasamulet");
const __s_sorry_to_say_this_is_a_mere_imitation = cptr.lit("Sorry to say, this is a mere imitation of the true Amulet of Yendor.");
const __s_ah_i_see_you_ve_found_s = cptr.lit("Ah, I see you've found %s.");
const __s_offeredit = cptr.lit("offeredit");
const __s_offeredit2 = cptr.lit("offeredit2");
const __s_quest_complete_no_bell = cptr.lit("quest_complete_no_bell");
const __s_posthanks = cptr.lit("posthanks");
const __s_encourage = cptr.lit("encourage");
const __s_leader_first = cptr.lit("leader_first");
const __s_leader_next = cptr.lit("leader_next");
const __s_badlevel = cptr.lit("badlevel");
const __s_banished = cptr.lit("banished");
const __s_s_has_expelled_you_from_the_quest = cptr.lit("%s has expelled you from the quest");
const __s_badalign = cptr.lit("badalign");
const __s_assignquest = cptr.lit("assignquest");
const __s_s_has_granted_access_to_proceed_deeper = cptr.lit("%s has granted access to proceed deeper into the quest");
const __s_leader_last = cptr.lit("leader_last");
const __s_discourage = cptr.lit("discourage");
const __s_nemesis_wantsit = cptr.lit("nemesis_wantsit");
const __s_nemesis_first = cptr.lit("nemesis_first");
const __s_nemesis_next = cptr.lit("nemesis_next");
const __s_nemesis_other = cptr.lit("nemesis_other");
const __s_quest_c = cptr.lit("quest.c");
const __s_nemesis_speaks = cptr.lit("nemesis_speaks");
const __s_guardtalk_after = cptr.lit("guardtalk_after");
const __s_guardtalk_before = cptr.lit("guardtalk_before");
const __s_s_speaks = cptr.lit("%s speaks:");
const __s_i_m_finally_free = cptr.lit("I'm finally free!");
const __s_quest_chat_unknown_quest_character_s = cptr.lit("quest_chat: Unknown quest character %s.");

/** C ref: quest.c:26 */
function* on_start() {
    if (!((cptr.ldI32(svq) & 1))) {
        (yield* qt_pager(__s_firsttime));
        cptr.stI32(svq, 1);
    } else if ((cptr.ldI16o(u, $you_uz0) != cptr.ldI16o(u, $you_uz)) || (cptr.ldI16o(u, $you_uz0 + $d_level_dlevel) < cptr.ldI16o(u, $you_uz + $d_level_dlevel))) {
        if ((((cptr.ldI32o(svq, $q_score_not_ready) & 7)) | 0) <= 2)
            (yield* qt_pager(__s_nexttime));
        else
            (yield* qt_pager(__s_othertime));
    }
}

/** C ref: quest.c:40 */
function* on_locate() {
    let from_above = schar((cptr.ldI16o(u, $you_uz0 + $d_level_dlevel) < cptr.ldI16o(u, $you_uz + $d_level_dlevel)));
    if (((cptr.ldI32o(svq, $q_score_killed_nemesis) & 1))) {
        return;
    } else if (!((cptr.ldI32o(svq, $q_score_first_locate) & 1))) {
        if (from_above)
            (yield* qt_pager(__s_locate_first));
        cptr.stI32o(svq, $q_score_first_locate, 1);
    } else {
        if (from_above)
            (yield* qt_pager(__s_locate_next));
    }
}

/** C ref: quest.c:62 */
function* on_goal() {
    if (((cptr.ldI32o(svq, $q_score_killed_nemesis) & 1))) {
        return;
    } else if (!((cptr.ldI32o(svq, $q_score_made_goal) & 7))) {
        (yield* qt_pager(__s_goal_first));
        cptr.stI32o(svq, $q_score_made_goal, 1);
    } else {
        let whichobjchains = 82;
        let qarti = find_quest_artifact(whichobjchains);
        (yield* qt_pager(qarti ? __s_goal_next : __s_goal_alt));
        if ((((cptr.ldI32o(svq, $q_score_made_goal) & 7)) | 0) < 7)
            (cptr.stI32o(svq, $q_score_made_goal, cptr.ldI32o(svq, $q_score_made_goal) + 1)) - (1);
    }
}

/** C ref: quest.c:90 */
export function* onquest() {
    if ((cptr.ldI32o(u, $you_uevent + $u_event_qcompleted) & 1) | 0 || (on_level(cptr.add(u, $you_uz0), cptr.add(u, $you_uz))))
        return;
    if (!Is_special(cptr.add(u, $you_uz)))
        return;
    if ((((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qstart_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qstart_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qstart_level)))))
        (yield* on_start());
    else if ((((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qlocate_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qlocate_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qlocate_level)))))
        (yield* on_locate());
    else if ((((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_nemesis_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_nemesis_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_nemesis_level)))))
        (yield* on_goal());
    return;
}

/** C ref: quest.c:107 */
export function* nemdead() {
    if (!((cptr.ldI32o(svq, $q_score_killed_nemesis) & 1))) {
        cptr.stI32o(svq, $q_score_killed_nemesis, 1);
        (yield* qt_pager(__s_killed_nemesis));
    }
}

/** C ref: quest.c:116 */
export function leaddead() {
    if (!((cptr.ldI32o(svq, $q_score_killed_leader) & 1))) {
        cptr.stI32o(svq, $q_score_killed_leader, 1);
    }
}

/** C ref: quest.c:125 — @param {CPtr<struct obj>} obj */
export function* artitouch(obj) {
    if (!((cptr.ldI32o(svq, $q_score_touched_artifact) & 1))) {
        (yield* observe_object(obj));
        cptr.stI32o(svq, $q_score_touched_artifact, 1);
        (yield* qt_pager(__s_gotit));
        (yield* exercise(NHC.A_WIS, 1));
    }
}

/** C ref: quest.c:140 @returns {CInt} */
export function* ok_to_quest() {
    return schar((((((cptr.ldI32o(svq, $q_score_got_quest) & 1)) | 0 || ((cptr.ldI32o(svq, $q_score_got_thanks) & 1)) | 0) && (yield* is_pure(0)) > 0) || ((cptr.ldI32o(svq, $q_score_killed_leader) & 1)) | 0 ? 1 : 0));
}

/** C ref: quest.c:147 @returns {CInt} */
function not_capable() {
    return schar((cptr.ldI32o(u, $you_ulevel) < NHM.MIN_QUEST_LEVEL));
}

/** C ref: quest.c:153 — @param {CInt} talk @returns {CInt} */
function* is_pure(talk) {
    let purity;
    let original_alignment = cptr.ld1so2(u, NHM.A_ORIGINAL, 1, $you_ualignbase);
    if (wizard() && talk) {
        if (cptr.ld1so(u, $you_ualign) != original_alignment) {
            (yield* You(__s_are_currently_s_instead_of_s, align_str(cptr.ld1so(u, $you_ualign)), align_str(original_alignment)));
        } else if (cptr.ld1so2(u, NHM.A_CURRENT, 1, $you_ualignbase) != original_alignment) {
            (yield* You(__s_have_converted));
        } else if (cptr.ldI32o(u, $you_ualign + $align_record) < NHM.MIN_QUEST_ALIGN) {
            (yield* You(__s_are_currently_d_and_require_d, cptr.ldI32o(u, $you_ualign + $align_record), NHM.MIN_QUEST_ALIGN));
            if ((yield* yn_function(__s_adjust, null, 121, 1)) == 121)
                cptr.stI32o(u, $you_ualign + $align_record, NHM.MIN_QUEST_ALIGN);
        }
    }
    purity = (cptr.ldI32o(u, $you_ualign + $align_record) >= NHM.MIN_QUEST_ALIGN && cptr.ld1so(u, $you_ualign) == original_alignment && cptr.ld1so2(u, NHM.A_CURRENT, 1, $you_ualignbase) == original_alignment) ? 1 : ((cptr.ld1so2(u, NHM.A_CURRENT, 1, $you_ualignbase) != original_alignment) ? -1 : 0);
    return purity;
}

/** C ref: quest.c:186 — @param {CInt} seal */
function* expulsion(seal) {
    let br;
    let dest;
    let t;
    let portal_flag = (cptr.ldI32o(u, $you_uevent + $u_event_qexpelled) & 1) | 0 ? NHC.UTOTYPE_NONE : NHC.UTOTYPE_PORTAL;
    br = (yield* dungeon_branch(__s_the_quest));
    dest = (cptr.ldI16o(br, $branch_end1) == cptr.ldI16o(u, $you_uz)) ? cptr.add(br, $branch_end2) : cptr.add(br, $branch_end1);
    if (seal)
        portal_flag |= NHC.UTOTYPE_RMPORTAL;
    nomul(0);
    (yield* schedule_goto(dest, portal_flag, null, null));
    if (seal) {
        let reexpelled = (cptr.ldI32o(u, $you_uevent + $u_event_qexpelled) & 1) | 0;
        cptr.stI32o(u, $you_uevent + $u_event_qexpelled, 1);
        remdun_mapseen(quest_dnum());
        for (t = cptr.ldPtr(gf); t; t = cptr.ldPtr(t))
            if (((cptr.ldI32o(t, $trap_ttyp) & 31) | 0) == NHC.MAGIC_PORTAL)
                break;
        if (t)
            (yield* deltrap(t));
        else if (!reexpelled)
            (yield* impossible(__s_quest_portal_already_gone));
    }
}

/** C ref: quest.c:226 — @param {CPtr<struct obj>} obj */
export function* finish_quest(obj) {
    let otmp;
    if (obj && !is_quest_artifact(obj)) {
        if (Deaf())
            return;
        (yield* fully_identify_obj(obj));
        if (cptr.ldI16o(obj, $obj_otyp) == NHC.AMULET_OF_YENDOR) {
            (yield* qt_pager(__s_hasamulet));
        } else if (cptr.ldI16o(obj, $obj_otyp) == NHC.FAKE_AMULET_OF_YENDOR) {
            (yield* verbalize(__s_sorry_to_say_this_is_a_mere_imitation));
        } else {
            (yield* verbalize(__s_ah_i_see_you_ve_found_s, (yield* the((yield* xname(obj))))));
        }
        return;
    }
    if ((cptr.ldI32o(u, $you_uhave) & 1)) {
        (yield* qt_pager(__s_hasamulet));
        if ((otmp = carrying(NHC.AMULET_OF_YENDOR)) !== null) {
            (yield* fully_identify_obj(otmp));
            (yield* update_inventory());
        }
    } else {
        (yield* qt_pager(!((cptr.ldI32o(svq, $q_score_got_thanks) & 1)) ? __s_offeredit : __s_offeredit2));
        if ((otmp = carrying(NHC.BELL_OF_OPENING)) === null)
            (yield* com_pager(__s_quest_complete_no_bell));
    }
    cptr.stI32o(svq, $q_score_got_thanks, 1);
    if (obj) {
        cptr.stI32o(u, $you_uevent + $u_event_qcompleted, 1);
        (yield* fully_identify_obj(obj));
        (yield* update_inventory());
    }
}

/** C ref: quest.c:282 — @param {CPtr<struct monst>} mtmp */
function* chat_with_leader(mtmp) {
    if (!(cptr.ldI32o(mtmp, $monst_mpeaceful) & 1) || ((cptr.ldI32o(svq, $q_score_pissed_off) & 1)) | 0)
        return;
    if ((cptr.ldI32o(u, $you_uhave + $u_have_questart) & 1) | 0 && !((cptr.ldI32o(svq, $q_score_met_nemesis) & 1)))
        cptr.stI32o(svq, $q_score_cheater, 1);
    if (((cptr.ldI32o(svq, $q_score_got_thanks) & 1))) {
        if ((cptr.ldI32o(u, $you_uhave) & 1))
            (yield* finish_quest(null));
        else
            (yield* qt_pager(__s_posthanks));
    } else if ((cptr.ldI32o(u, $you_uhave + $u_have_questart) & 1)) {
        let otmp;
        for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = cptr.ldPtr(otmp))
            if (is_quest_artifact(otmp))
                break;
        (yield* finish_quest(otmp));
    } else if (((cptr.ldI32o(svq, $q_score_got_quest) & 1))) {
        (yield* qt_pager(__s_encourage));
    } else {
        let purity = 0;
        if (!((cptr.ldI32o(svq, $q_score_met_leader) & 1))) {
            (yield* qt_pager(__s_leader_first));
            cptr.stI32o(svq, $q_score_met_leader, 1);
            cptr.stI32o(svq, $q_score_not_ready, 0);
        } else
            (yield* qt_pager(__s_leader_next));
        if (!on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qstart_level)))
            return;
        if (not_capable()) {
            (yield* qt_pager(__s_badlevel));
            (yield* exercise(NHC.A_WIS, 1));
            (yield* expulsion(0));
        } else if ((purity = (yield* is_pure(1))) < 0) {
            if (!((cptr.ldI32o(svq, $q_score_pissed_off) & 1))) {
                (yield* com_pager(__s_banished));
                cptr.stI32o(svq, $q_score_pissed_off, 1);
                (yield* expulsion(0));
                (yield* livelog_printf(2n, __s_s_has_expelled_you_from_the_quest, (yield* noit_mon_nam(mtmp))));
            }
        } else if (purity == 0) {
            (yield* qt_pager(__s_badalign));
            cptr.stI32o(svq, $q_score_not_ready, 1);
            (yield* exercise(NHC.A_WIS, 1));
            (yield* expulsion(0));
        } else {
            (yield* qt_pager(__s_assignquest));
            (yield* exercise(NHC.A_WIS, 1));
            cptr.stI32o(svq, $q_score_got_quest, 1);
            (yield* livelog_printf(2n, __s_s_has_granted_access_to_proceed_deeper, (yield* noit_mon_nam(mtmp))));
        }
    }
}

/** C ref: quest.c:371 — @param {CPtr<struct monst>} mtmp */
export function* leader_speaks(mtmp) {
    if (!(cptr.ldI32o(mtmp, $monst_mpeaceful) & 1)) {
        if (!((cptr.ldI32o(svq, $q_score_pissed_off) & 1))) {
            (yield* qt_pager(__s_leader_last));
        }
        cptr.stI32o(svq, $q_score_pissed_off, 1);
        cptr.stU64o(mtmp, $monst_mstrategy, cptr.ldU64o(mtmp, $monst_mstrategy) & 18446744072904245247n);
    }
    if (!on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_qstart_level)))
        return;
    if (!((cptr.ldI32o(svq, $q_score_pissed_off) & 1)))
        (yield* chat_with_leader(mtmp));
}

/** C ref: quest.c:394 */
function* chat_with_nemesis() {
    (yield* qt_pager(__s_discourage));
    if (!((cptr.ldI32o(svq, $q_score_met_nemesis) & 1)))
        ((cptr.stI32o(svq, $q_score_met_nemesis, cptr.ldI32o(svq, $q_score_met_nemesis) + 1)) - (1));
}

/** C ref: quest.c:403 */
export function* nemesis_speaks() {
    if (!((cptr.ldI32o(svq, $q_score_in_battle) & 1))) {
        if ((cptr.ldI32o(u, $you_uhave + $u_have_questart) & 1))
            (yield* qt_pager(__s_nemesis_wantsit));
        else if ((((cptr.ldI32o(svq, $q_score_made_goal) & 7)) | 0) == 1 || !((cptr.ldI32o(svq, $q_score_met_nemesis) & 1)))
            (yield* qt_pager(__s_nemesis_first));
        else if ((((cptr.ldI32o(svq, $q_score_made_goal) & 7)) | 0) < 4)
            (yield* qt_pager(__s_nemesis_next));
        else if ((((cptr.ldI32o(svq, $q_score_made_goal) & 7)) | 0) < 7)
            (yield* qt_pager(__s_nemesis_other));
        else if (!(rng_log_enabled() ? (rng_log_set_caller(__s_quest_c, 414, __s_nemesis_speaks), rn2(5)) : rn2(5)))
            (yield* qt_pager(__s_discourage));
        if ((((cptr.ldI32o(svq, $q_score_made_goal) & 7)) | 0) < 7)
            (cptr.stI32o(svq, $q_score_made_goal, cptr.ldI32o(svq, $q_score_made_goal) + 1)) - (1);
        cptr.stI32o(svq, $q_score_met_nemesis, 1);
    } else if (!(rng_log_enabled() ? (rng_log_set_caller(__s_quest_c, 420, __s_nemesis_speaks), rn2(5)) : rn2(5)))
        (yield* qt_pager(__s_discourage));
}

/** C ref: quest.c:426 — @param {CInt} mx @param {CInt} my */
export function* nemesis_stinks(mx, my) {
    let save_mon_moving = cptr.ld1so(svc, $context_info_mon_moving);
    cptr.st1o(svc, $context_info_mon_moving, 1);
    (yield* create_gas_cloud(mx, my, 5, 8));
    cptr.st1o(svc, $context_info_mon_moving, save_mon_moving);
}

/** C ref: quest.c:441 */
function* chat_with_guardian() {
    if ((cptr.ldI32o(u, $you_uhave + $u_have_questart) & 1) | 0 && ((cptr.ldI32o(svq, $q_score_killed_nemesis) & 1)) | 0)
        (yield* qt_pager(__s_guardtalk_after));
    else
        (yield* qt_pager(__s_guardtalk_before));
}

/** C ref: quest.c:451 — @param {CPtr<struct monst>} mtmp */
function* prisoner_speaks(mtmp) {
    if (cptr.eq(cptr.ldPtro(mtmp, $monst_data), cptr.add(mons, NHC.PM_PRISONER, $sizeof_permonst)) && (cptr.ldU64o(mtmp, $monst_mstrategy) & 805306368n)) {
        if (canseemon(mtmp))
            (yield* pline(__s_s_speaks, (yield* Monnam(mtmp))));
        ;
        (yield* verbalize(__s_i_m_finally_free));
        cptr.stU64o(mtmp, $monst_mstrategy, cptr.ldU64o(mtmp, $monst_mstrategy) & 18446744072904245247n);
        cptr.stI32o(mtmp, $monst_mpeaceful, 1);
        adjalign(3);
        void (yield* angry_guards(0));
    }
    return;
}

/** C ref: quest.c:473 — @param {CPtr<struct monst>} mtmp */
export function* quest_chat(mtmp) {
    if (cptr.ldI32o(mtmp, $monst_m_id) == (cptr.ldI32o(svq, $q_score_leader_m_id))) {
        (yield* chat_with_leader(mtmp));
        if (((cptr.ldI32o(svq, $q_score_pissed_off) & 1)))
            (yield* setmangry(mtmp, 0));
        return;
    }
    switch (cptr.ld1uo(cptr.ldPtro(mtmp, $monst_data), $permonst_msound)) {
        case NHC.MS_NEMESIS:
        (yield* chat_with_nemesis());
        break;
        case NHC.MS_GUARDIAN:
        (yield* chat_with_guardian());
        break;
        default:
        (yield* impossible(__s_quest_chat_unknown_quest_character_s, (yield* mon_nam(mtmp))));
    }
}

/** C ref: quest.c:495 — @param {CPtr<struct monst>} mtmp */
export function* quest_talk(mtmp) {
    if (cptr.ldI32o(mtmp, $monst_m_id) == (cptr.ldI32o(svq, $q_score_leader_m_id))) {
        (yield* leader_speaks(mtmp));
        return;
    }
    switch (cptr.ld1uo(cptr.ldPtro(mtmp, $monst_data), $permonst_msound)) {
        case NHC.MS_NEMESIS:
        (yield* nemesis_speaks());
        break;
        case NHC.MS_DJINNI:
        (yield* prisoner_speaks(mtmp));
        break;
        default:
        break;
    }
}

/** C ref: quest.c:514 — @param {CPtr<struct monst>} mtmp */
export function quest_stat_check(mtmp) {
    if (cptr.ld1uo(cptr.ldPtro(mtmp, $monst_data), $permonst_msound) == NHC.MS_NEMESIS)
        cptr.stI32o(svq, $q_score_in_battle, (!helpless(mtmp) && monnear(mtmp, cptr.ldI16(u), cptr.ldI16o(u, $you_uy)) ? 1 : 0) >>> 0);
}
