// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/steal.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/steal.c
// Input sha256: 0aa14e4a989d4869de9b9bd223231ac559f2d6641d9bfb949d0aaff29ca8a447
// Transpiler: tools/c2js c2js emit v1+batch

import { i16, schar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import * as FLD from './nhfield.js';
import { bimanual, canspotmon, min, touch_petrifies } from './nhmacrofn.js';
import { Adornment, Blind, Conflict, Flying, Levitation, Punished } from './nhprop.js';
import { rn2, rnd, rng_log_enabled, rng_log_set_caller } from './rnd.js';
import { carry_obj_effects, count_unpaid, freeinv, g_at, stackobj } from './invent.js';
import { disp, flags, ga, gi, gk, gm, gn, go, gs, gt, gv, gy, iflags, svl, u, uarm, uarmc, uarmf, uarmg, uarmh, uarms, uarmu, uball, uchain, uleft, uquiver, uright, uskin, uswapwep, uwep } from './decl.js';
import { add_to_minv, obj_extract_self, place_object, splitobj, unknow_object } from './mkobj.js';
import { canseemon, newsym, sensemon } from './display.js';
import { copynchars, dist2, s_suffix, strstri, strsubst, upstart } from './hacklib.js';
import { Adjmonnam, Mgender, Monnam, Some_Monnam, pmname, y_monnam } from './do_name.js';
import { Tobjnam, armor_simple_name, distant_name, doname, makeplural, otense, simpleonames, yname } from './objnam.js';
import { body_part, mbodypart, skinback } from './polyself.js';
import { You, Your, impossible, pline, pline_mon, urgent_pline } from './pline.js';
import { rloc, rloco, tele_restrict } from './teleport.js';
import { monflee } from './monmove.js';
import { objects } from './objects.js';
import { in_rooms, inv_cnt, money_cnt, nomul } from './hack.js';
import { extract_from_minvent, setnotworn, setworn, update_mon_extrinsics } from './worn.js';
import { minstapetrify, openholdingtrap, unconscious } from './trap.js';
import { is_fainted, maybe_finished_meal } from './eat.js';
import { attacktype, dmgtype } from './mondata.js';
import { costly_spot, find_objowner, obfree, shop_keeper, subfrombill } from './shk.js';
import { Amulet_off, Armor_off, Blindf_off, Boots_off, Cloak_off, Gloves_off, Helmet_off, Ring_gone, Shield_off, Shirt_off, cancel_don, doffing, donning, stop_donning } from './do_wear.js';
import { uqwepgone, uswapwepgone, uwepgone, welded } from './wield.js';
import { unpunish } from './read.js';
import { debugcore } from './files.js';
import { can_carry, monnear } from './mon.js';
import { o_unleash } from './apply.js';
import { stop_occupation } from './allmain.js';
import { encumber_msg } from './pickup.js';
import { mons } from './monst.js';
import { obj_sheds_light, snuff_light_source } from './light.js';
import { obj_resists } from './zap.js';
import { touch_artifact } from './artifact.js';
import { flooreffects } from './do.js';
import { is_quest_artifact } from './questpgr.js';
import { droppables } from './dogmove.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $dlevel_t_monlist = FLD.dlevel_t_monlist, $flag_female = FLD.flag_female,
    $flag_verbose = FLD.flag_verbose, $instance_flags_last_msg = FLD.instance_flags_last_msg,
    $instance_globals_i_invent = FLD.instance_globals_i_invent,
    $instance_globals_k_kickedobj = FLD.instance_globals_k_kickedobj,
    $instance_globals_m_multi = FLD.instance_globals_m_multi,
    $instance_globals_m_multi_reason = FLD.instance_globals_m_multi_reason,
    $instance_globals_n_nomovemsg = FLD.instance_globals_n_nomovemsg,
    $instance_globals_o_occupation = FLD.instance_globals_o_occupation,
    $instance_globals_s_stealmid = FLD.instance_globals_s_stealmid,
    $instance_globals_s_stealoid = FLD.instance_globals_s_stealoid,
    $instance_globals_saved_l_level = FLD.instance_globals_saved_l_level,
    $instance_globals_t_thrownobj = FLD.instance_globals_t_thrownobj,
    $instance_globals_v_viz_array = FLD.instance_globals_v_viz_array,
    $instance_globals_y_youmonst = FLD.instance_globals_y_youmonst, $monst_data = FLD.monst_data,
    $monst_isgd = FLD.monst_isgd, $monst_iswiz = FLD.monst_iswiz, $monst_m_id = FLD.monst_m_id,
    $monst_mavenge = FLD.monst_mavenge, $monst_mhp = FLD.monst_mhp, $monst_minvent = FLD.monst_minvent,
    $monst_misc_worn_check = FLD.monst_misc_worn_check, $monst_mtame = FLD.monst_mtame,
    $monst_mx = FLD.monst_mx, $monst_my = FLD.monst_my, $obj_cobj = FLD.obj_cobj,
    $obj_corpsenm = FLD.obj_corpsenm, $obj_cursed = FLD.obj_cursed, $obj_how_lost = FLD.obj_how_lost,
    $obj_in_use = FLD.obj_in_use, $obj_no_charge = FLD.obj_no_charge, $obj_o_id = FLD.obj_o_id,
    $obj_oartifact = FLD.obj_oartifact, $obj_oclass = FLD.obj_oclass, $obj_otyp = FLD.obj_otyp,
    $obj_owornmask = FLD.obj_owornmask, $obj_ox = FLD.obj_ox, $obj_oy = FLD.obj_oy, $obj_quan = FLD.obj_quan,
    $obj_unpaid = FLD.obj_unpaid, $obj_v = FLD.obj_v, $obj_where = FLD.obj_where,
    $objclass_oc_big = FLD.objclass_oc_big, $objclass_oc_cost = FLD.objclass_oc_cost,
    $objclass_oc_delay = FLD.objclass_oc_delay, $permonst_mflags1 = FLD.permonst_mflags1,
    $permonst_mflags2 = FLD.permonst_mflags2, $permonst_mlet = FLD.permonst_mlet,
    $prop_blocked = FLD.prop_blocked, $prop_intrinsic = FLD.prop_intrinsic, $rm_roomno = FLD.rm_roomno,
    $u_have_bell = FLD.u_have_bell, $u_have_book = FLD.u_have_book, $u_have_menorah = FLD.u_have_menorah,
    $you_twoweap = FLD.you_twoweap, $you_uhandedness = FLD.you_uhandedness, $you_uhave = FLD.you_uhave,
    $you_uprops = FLD.you_uprops, $you_ushops = FLD.you_ushops, $you_usteed = FLD.you_usteed,
    $you_ustuck = FLD.you_ustuck, $you_uswallow = FLD.you_uswallow, $you_utrap = FLD.you_utrap,
    $you_utraptype = FLD.you_utraptype, $you_uy = FLD.you_uy;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_steal_c = cptr.lit("steal.c");
const __s_somegold = cptr.lit("somegold");
const __s_stealgold = cptr.lit("stealgold");
const __s_your = cptr.lit("your");
const __s_coils = cptr.lit("coils");
const __s_rear = cptr.lit("rear ");
const __s_s_quickly_snatches_some_gold_from_s_s_s = cptr.lit("%s quickly snatches some gold from %s %s %s!");
const __s_beneath = cptr.lit("beneath");
const __s_between = cptr.lit("between");
const __s_purse_feels_lighter = cptr.lit("purse feels lighter.");
const __s_frozen = cptr.lit("frozen");
const __s_paralyzed = cptr.lit("paralyzed");
const __s_finish_taking_off_your_s = cptr.lit("finish taking off your %s.");
const __s_stealarm_dead_monster_stealing = cptr.lit("stealarm(): dead monster stealing");
const __s_s_steals_s = cptr.lit("%s steals %s!");
const __s_removing_embedded_scales = cptr.lit("Removing embedded scales?");
const __s_remove_worn_item_s_deleted = cptr.lit("remove_worn_item() \"%s\" deleted!");
const __s_the = cptr.lit("the ");
const __s_an = cptr.lit("an ");
const __s_a_sp = cptr.lit("a ");
const __s_your__2 = cptr.lit("your ");
const __s_being_worn = cptr.lit(" (being worn)");
const __s_empty = cptr.lit("");
const __s_alternate_weapon_not_wielded = cptr.lit(" (alternate weapon; not wielded)");
const __s_on = cptr.lit(" (on ");
const __s_left = cptr.lit("left ");
const __s_right = cptr.lit("right ");
const __s_on__2 = cptr.lit("on");
const __s_from = cptr.lit("from");
const __s_disarms = cptr.lit("disarms");
const __s_removes = cptr.lit("removes");
const __s_takes_off = cptr.lit("takes off");
const __s_s_s_s = cptr.lit("%s %s %s.");
const __s_steal = cptr.lit("steal");
const __s_uball_null_uball_where_obj_floor = cptr.lit("uball != NULL && uball->where == OBJ_FLOOR");
const __s_s_takes_off_your_unseen_chain = cptr.lit("%s takes off your unseen chain.");
const __s_somebody_tries_to_rob_you_but_finds = cptr.lit("Somebody tries to rob you, but finds nothing to steal.");
const __s_s_tries_to_rob_you_but_isn_t_interested = cptr.lit("%s tries to rob you, but isn't interested in gold.");
const __s_s_tries_to_rob_you_but_there_is_nothing = cptr.lit("%s tries to rob you, but there is nothing to steal!");
const __s_steal_fails = cptr.lit("Steal fails!");
const __s_s_tries_to_s_s_s_but_gives_up = cptr.lit("%s tries to %s %s%s but gives up.");
const __s_s_charms_you_you_gladly_s_your_s = cptr.lit("%s charms you.  You gladly %s your %s.");
const __s_she = cptr.lit("She");
const __s_let_her_take = cptr.lit("let her take");
const __s_hand_over = cptr.lit("hand over");
const __s_continue_removing = cptr.lit("continue removing");
const __s_start_removing = cptr.lit("start removing");
const __s_s_seduces_you_and_s_off_your_s = cptr.lit("%s seduces you and %s off your %s.");
const __s_beautiful = cptr.lit("beautiful");
const __s_helps_you_to_take = cptr.lit("helps you to take");
const __s_you_take = cptr.lit("you take");
const __s_you_continue_taking = cptr.lit("you continue taking");
const __s_you_start_taking = cptr.lit("you start taking");
const __s_taking_off_clothes = cptr.lit("taking off clothes");
const __s_tried_to_steal_a_strange_worn_thing_d = cptr.lit("Tried to steal a strange worn thing. [%d]");
const __s_s_stole_s = cptr.lit("%s stole %s.");
const __s_snatch = cptr.lit("snatch");
const __s_grab = cptr.lit("grab");
const __s_take = cptr.lit("take");
const __s_monster_s_taking_or_picking_up_nothing = cptr.lit("monster (%s) taking or picking up nothing?");
const __s_monster_s_taking_or_picking_up_attached = cptr.lit("monster (%s) taking or picking up attached %s (%s)?");
const __s_chain = cptr.lit("chain");
const __s_ball = cptr.lit("ball");
const __s_s_out = cptr.lit("%s out.");
const __s_go = cptr.lit("go");
const __s_stealamulet = cptr.lit("stealamulet");
const __s_s_pulls_s_away_from_you_and_absorbs_s = cptr.lit("%s pulls %s away from you and absorbs %s!");
const __s_them = cptr.lit("them");
const __s_it = cptr.lit("it");
const __s_s_s_pulled_from_your_s = cptr.lit("%s %s pulled from your %s!");
const __s_are = cptr.lit("are");
const __s_s_absorbs_s = cptr.lit("%s absorbs %s!");
const __s_s_drops_s = cptr.lit("%s drops %s.");
const __s_fall = cptr.lit("fall");
const __s_s_gold_s = cptr.lit("%s gold %s.");
const __s_vanishes = cptr.lit("vanishes");
const __s_seems_to_vanish = cptr.lit("seems to vanish");

/** C ref: steal.c:14 — @param {CLongLong} lmoney @returns {CLongLong} */
export function somegold(lmoney) {
    let igold = (lmoney >= 32767n) ? NHM.LARGEST_INT : Number(BigInt.asIntN(32, lmoney));
    if (igold < 50)
        ;
    else if (igold < 100)
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 21, __s_somegold), rn2((((igold - 25) | 0) + 1) | 0)) : rn2((((igold - 25) | 0) + 1) | 0)) + 25) | 0);
    else if (igold < 500)
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 23, __s_somegold), rn2((((igold - 50) | 0) + 1) | 0)) : rn2((((igold - 50) | 0) + 1) | 0)) + 50) | 0);
    else if (igold < 1000)
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 25, __s_somegold), rn2((((igold - 100) | 0) + 1) | 0)) : rn2((((igold - 100) | 0) + 1) | 0)) + 100) | 0);
    else if (igold < 5000)
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 27, __s_somegold), rn2((((igold - 500) | 0) + 1) | 0)) : rn2((((igold - 500) | 0) + 1) | 0)) + 500) | 0);
    else if (igold < 10000)
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 29, __s_somegold), rn2((((igold - 1000) | 0) + 1) | 0)) : rn2((((igold - 1000) | 0) + 1) | 0)) + 1000) | 0);
    else
        igold = (((rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 31, __s_somegold), rn2((((igold - 5000) | 0) + 1) | 0)) : rn2((((igold - 5000) | 0) + 1) | 0)) + 5000) | 0);
    return BigInt(igold);
}

/** C ref: steal.c:45 — @param {CPtr<struct obj>} argchain @returns {CPtr<struct obj>} */
export function findgold(argchain) {
    let chain = argchain;
    while (chain && cptr.ldI16o(chain, $obj_otyp) != NHC.GOLD_PIECE)
        chain = cptr.ldPtr(chain);
    return chain;
}

/** C ref: steal.c:58 — @param {CPtr<struct monst>} mtmp */
export function* stealgold(mtmp) {
    let fgold = g_at(cptr.ldI16(u), cptr.ldI16o(u, $you_uy));
    let ygold;
    let tmp;
    let who;
    let whose;
    let what;
    while (fgold && cptr.ldI16o(fgold, $obj_otyp) != NHC.GOLD_PIECE)
        fgold = cptr.ldPtro(fgold, $obj_v);
    ygold = findgold(cptr.ldPtro(gi, $instance_globals_i_invent));
    if (fgold && (!ygold || cptr.ldI64o(fgold, $obj_quan) > cptr.ldI64o(ygold, $obj_quan) || !(rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 73, __s_stealgold), rn2(5)) : rn2(5)))) {
        (yield* obj_extract_self(fgold));
        (yield* add_to_minv(mtmp, fgold));
        (yield* newsym(cptr.ldI16(u), cptr.ldI16o(u, $you_uy)));
        if (cptr.ldPtro(u, $you_usteed)) {
            who = cptr.ldPtro(u, $you_usteed);
            whose = (yield* s_suffix((yield* y_monnam(who))));
            what = (yield* makeplural((yield* mbodypart(who, NHC.FOOT))));
        } else {
            who = cptr.add(gy, $instance_globals_y_youmonst);
            whose = __s_your;
            what = (yield* makeplural((yield* body_part(NHC.FOOT))));
        }
        if (((cptr.ldU64o((cptr.ldPtro(who, $monst_data)), $permonst_mflags1) & 524288n) != 0n))
            what = __s_coils;
        if (!cptr.strncmp(what, __s_rear, 5n))
            what = cptr.add(what, 5);
        (yield* pline(__s_s_quickly_snatches_some_gold_from_s_s_s, (yield* Monnam(mtmp)), (Levitation() || Flying()) ? __s_beneath : __s_between, whose, what));
        if (!ygold || !(rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 94, __s_stealgold), rn2(5)) : rn2(5))) {
            if (!(yield* tele_restrict(mtmp)))
                void (yield* rloc(mtmp, NHM.RLOC_MSG));
            (yield* monflee(mtmp, 0, 0, 0));
        }
    } else if (ygold) {
        let gold_price = cptr.ldI16o2(objects, NHC.GOLD_PIECE, 120, $objclass_oc_cost);
        tmp = (BigInt.asIntN(64, BigInt.asIntN(64, somegold(money_cnt(cptr.ldPtro(gi, $instance_globals_i_invent))) + BigInt(gold_price)) - 1n)) / BigInt(gold_price);
        tmp = min(tmp, cptr.ldI64o(ygold, $obj_quan));
        if (tmp < cptr.ldI64o(ygold, $obj_quan))
            ygold = (yield* splitobj(ygold, tmp));
        else
            (yield* setnotworn(ygold));
        (yield* freeinv(ygold));
        (yield* add_to_minv(mtmp, ygold));
        (yield* Your(__s_purse_feels_lighter));
        if (!(yield* tele_restrict(mtmp)))
            void (yield* rloc(mtmp, NHM.RLOC_MSG));
        (yield* monflee(mtmp, 0, 0, 0));
        cptr.st1(disp, 1);
    }
}

/** C ref: steal.c:120 */
export function thiefdead() {
    cptr.stI32o(gs, $instance_globals_s_stealmid, 0);
    if (cptr.ldPtr(ga) === stealarm) {
        cptr.stPtr(ga, unstolenarm);
        cptr.stPtro(gn, $instance_globals_n_nomovemsg, null);
    }
}

/** C ref: steal.c:133 @returns {CInt} */
export function unresponsive() {
    if (cptr.ldI64o(gm, $instance_globals_m_multi) >= 0n)
        return 0;
    return schar((unconscious() || is_fainted() || (cptr.ldPtro(gm, $instance_globals_m_multi_reason) && (!cptr.strncmp(cptr.ldPtro(gm, $instance_globals_m_multi_reason), __s_frozen, 6n) || !cptr.strncmp(cptr.ldPtro(gm, $instance_globals_m_multi_reason), __s_paralyzed, 9n))) ? 1 : 0));
}

/** C ref: steal.c:147 @returns {CInt} */
function* unstolenarm() {
    let obj;
    for (obj = cptr.ldPtro(gi, $instance_globals_i_invent); obj; obj = cptr.ldPtr(obj))
        if (cptr.ldI32o(obj, $obj_o_id) == cptr.ldI32o(gs, $instance_globals_s_stealoid))
            break;
    cptr.stI32o(gs, $instance_globals_s_stealoid, 0);
    if (obj) {
        (yield* You(__s_finish_taking_off_your_s, (yield* armor_simple_name(obj))));
    }
    return 0;
}

/** C ref: steal.c:165 @returns {CInt} */
function* stealarm() {
    let mtmp;
    let otmp;
    let nextobj;
    __lbl_botm: {
        if (!cptr.ldI32o(gs, $instance_globals_s_stealoid) || !cptr.ldI32o(gs, $instance_globals_s_stealmid))
            break __lbl_botm;
        for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = nextobj) {
            nextobj = cptr.ldPtr(otmp);
            if (cptr.ldI32o(otmp, $obj_o_id) == cptr.ldI32o(gs, $instance_globals_s_stealoid)) {
                for (mtmp = cptr.ldPtro(svl, $instance_globals_saved_l_level + $dlevel_t_monlist); mtmp; mtmp = cptr.ldPtr(mtmp)) {
                    if (cptr.ldI32o(mtmp, $monst_m_id) == cptr.ldI32o(gs, $instance_globals_s_stealmid)) {
                        if ((cptr.ldI32o((mtmp), $monst_mhp) < 1)) {
                            (yield* impossible(__s_stealarm_dead_monster_stealing));
                            break __lbl_botm;
                        }
                        if (!dmgtype(cptr.ldPtro(mtmp, $monst_data), NHM.AD_SITM) || dist2((cptr.ldI16o(mtmp, $monst_mx)), (cptr.ldI16o(mtmp, $monst_my)), cptr.ldI16(u), cptr.ldI16o(u, $you_uy)) > 2)
                            break __lbl_botm;
                        if ((cptr.ldI32o(otmp, $obj_unpaid) & 1))
                            (yield* subfrombill(otmp, (yield* shop_keeper(cptr.ld1so(u, $you_ushops)))));
                        (yield* freeinv(otmp));
                        (yield* pline(__s_s_steals_s, (yield* Monnam(mtmp)), (yield* doname(otmp))));
                        void (yield* mpickobj(mtmp, otmp));
                        (yield* monflee(mtmp, 0, 0, 0));
                        if (!(yield* tele_restrict(mtmp)))
                            void (yield* rloc(mtmp, NHM.RLOC_MSG));
                        break;
                    }
                }
                break;
            }
        }
    }
    cptr.stI32o(gs, $instance_globals_s_stealoid, cptr.stI32o(gs, $instance_globals_s_stealmid, 0));
    return 0;
}

/** C ref: steal.c:213 — @param {CPtr<struct obj>} obj @param {CInt} unchain_ball */
export function* remove_worn_item(obj, unchain_ball) {
    let oldinuse;
    if (donning(obj))
        cancel_don();
    if (!cptr.ldI64o(obj, $obj_owornmask))
        return;
    oldinuse = (cptr.ldI32o(obj, $obj_in_use) & 1);
    cptr.stI32o(obj, $obj_in_use, 1);
    if (cptr.ldI64o(obj, $obj_owornmask) & 127n) {
        if (cptr.eq(obj, uskin.v)) {
            (yield* impossible(__s_removing_embedded_scales));
            (yield* skinback(1));
        }
        if (cptr.eq(obj, uarm.v))
            void (yield* Armor_off());
        else if (cptr.eq(obj, uarmc.v))
            void (yield* Cloak_off());
        else if (cptr.eq(obj, uarmf.v))
            void (yield* Boots_off());
        else if (cptr.eq(obj, uarmg.v))
            void (yield* Gloves_off());
        else if (cptr.eq(obj, uarmh.v))
            void (yield* Helmet_off());
        else if (cptr.eq(obj, uarms.v))
            void (yield* Shield_off());
        else if (cptr.eq(obj, uarmu.v))
            void (yield* Shirt_off());
        else
            (yield* setworn(null, cptr.ldI64o(obj, $obj_owornmask) & 127n));
    } else if (cptr.ldI64o(obj, $obj_owornmask) & 65536n) {
        (yield* Amulet_off());
    } else if (cptr.ldI64o(obj, $obj_owornmask) & 393216n) {
        (yield* Ring_gone(obj));
    } else if (cptr.ldI64o(obj, $obj_owornmask) & 524288n) {
        (yield* Blindf_off(obj));
    } else if (cptr.ldI64o(obj, $obj_owornmask) & 1792n) {
        if (cptr.eq(obj, uwep.v))
            (yield* uwepgone());
        if (cptr.eq(obj, uswapwep.v))
            (yield* uswapwepgone());
        if (cptr.eq(obj, uquiver.v))
            (yield* uqwepgone());
    }
    if (cptr.ldI64o(obj, $obj_owornmask) & 6291456n) {
        if (unchain_ball)
            (yield* unpunish());
    } else if (cptr.ldI64o(obj, $obj_owornmask)) {
        (yield* setnotworn(obj));
    }
    if (cptr.ld1so(obj, $obj_where) == NHM.OBJ_DELETED)
        {
            if ((yield* debugcore(__s_steal_c, 1))) {
                let save_plnmsg = cptr.ldI32o(iflags, $instance_flags_last_msg);
                (yield* pline(__s_remove_worn_item_s_deleted, (yield* simpleonames(obj))));
                cptr.stI32o(iflags, $instance_flags_last_msg, save_plnmsg);
            }
        }
    cptr.stI32o(obj, $obj_in_use, oldinuse);
}

/** C ref: steal.c:294 — @param {CPtr<struct monst>} mon @param {CPtr<struct obj>} obj */
function* worn_item_removal(mon, obj) {
    let objbuf = new Uint8Array(256);
    let article = new Uint8Array(20);
    let p;
    let verb;
    let strip_art;
    void cptr.strcpy(cptr.decay(objbuf), (yield* doname(obj)));
    strip_art = !cptr.strncmp(cptr.decay(objbuf), __s_the, 4n) ? 4 : (!cptr.strncmp(cptr.decay(objbuf), __s_an, 3n) ? 3 : (!cptr.strncmp(cptr.decay(objbuf), __s_a_sp, 2n) ? 2 : 0));
    if (strip_art) {
        (yield* copynchars(cptr.decay(article), cptr.decay(objbuf), strip_art));
        void strsubst(cptr.decay(objbuf), cptr.decay(article), (cptr.eq(obj, uchain.v)) ? __s_the : __s_your__2);
    }
    void strsubst(cptr.decay(objbuf), __s_being_worn, __s_empty);
    void strsubst(cptr.decay(objbuf), __s_alternate_weapon_not_wielded, __s_empty);
    if ((p = (yield* strstri(cptr.decay(objbuf), __s_on))) && (!cptr.strncmp(cptr.add(p, 5), __s_left, 5n) || !cptr.strncmp(cptr.add(p, 5), __s_right, 6n)))
        void strsubst(cptr.add(p, 2), __s_on__2, __s_from);
    verb = ((cptr.ldI64o(obj, $obj_owornmask) & 1792n) != 0n) ? __s_disarms : (((cptr.ldI64o(obj, $obj_owornmask) & 983040n) != 0n) ? __s_removes : __s_takes_off);
    (yield* pline(__s_s_s_s, (yield* Some_Monnam(mon)), verb, cptr.decay(objbuf)));
    cptr.stI32o(iflags, $instance_flags_last_msg, NHC.PLNMSG_MON_TAKES_OFF_ITEM);
    (yield* remove_worn_item(obj, 1));
}

const __static_steal_how = cptr.alloc(4 * 8);
cptr.stPtro(__static_steal_how, 0, __s_steal);
cptr.stPtro(__static_steal_how, 8, __s_snatch);
cptr.stPtro(__static_steal_how, 16, __s_grab);
cptr.stPtro(__static_steal_how, 24, __s_take); /** C ref: steal.c:476 — char *[4] (function-static) */

/** C ref: steal.c:343 — @param {CPtr<struct monst>} mtmp @param {CPtr<char>} objnambuf @returns {CInt} */
export function* steal(mtmp, objnambuf) {
    let otmp, Monnambuf, tmp, could_petrify, armordelay, olddelay, icnt, named, retrycnt, monkey_business, seen, was_doffing, was_punished, dummy = cptr.box(0), ostuck, curssv, slowly, item;
    let __pc = 0;
    __dispatch: while (true) {
        switch (__pc) {
        case 0: {
        Monnambuf = new Uint8Array(256);
        named = 0;
        retrycnt = 0;
        monkey_business = schar(((cptr.ldU64o((cptr.ldPtro(mtmp, $monst_data)), $permonst_mflags1) & 262144n) != 0n));
        seen = schar(canspotmon(mtmp));
        was_punished = schar((uball.v !== null));
        if (objnambuf)
            cptr.st1(objnambuf, 0);
        if (!monnear(mtmp, cptr.ldI16(u), cptr.ldI16o(u, $you_uy)))
            return 0;
        void cptr.strcpy(cptr.decay(Monnambuf), (yield* Some_Monnam(mtmp)));
        if (cptr.ldPtro(go, $instance_globals_o_occupation))
            void (yield* maybe_finished_meal(0));
        icnt = inv_cnt(0);
        if (!icnt || (icnt == 1 && uskin.v)) { __pc = 6; continue; }
        __pc = 5; continue;
        }
        case 6: {
        __pc = 1;
        continue;
        }
        case 1 /* nothing_to_steal: */: {
        if (Punished() && !monkey_business && (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 379, __s_steal), rn2(4)) : rn2(4))) {
            (__builtin_expect(BigInt((!(!cptr.eq(uball.v, (null)) && cptr.ld1so(uball.v, $obj_where) == NHM.OBJ_FLOOR))), 0n) ? __assert_rtn(__s_steal, __s_steal_c, 381, __s_uball_null_uball_where_obj_floor) : void 0);
            (yield* worn_item_removal(mtmp, uchain.v));
        } else if (cptr.ldI32o(u, $you_utrap) && cptr.ldI32o(u, $you_utraptype) == NHC.TT_BURIEDBALL && !monkey_business && !(rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 384, __s_steal), rn2(4)) : rn2(4))) {
            (yield* pline(__s_s_takes_off_your_unseen_chain, cptr.decay(Monnambuf)));
            void (yield* openholdingtrap(cptr.add(gy, $instance_globals_y_youmonst), dummy));
        } else if (Blind()) {
            (yield* pline(__s_somebody_tries_to_rob_you_but_finds));
        } else if (inv_cnt(1) > inv_cnt(0)) {
            (yield* pline(__s_s_tries_to_rob_you_but_isn_t_interested, cptr.decay(Monnambuf)));
        } else {
            (yield* pline(__s_s_tries_to_rob_you_but_there_is_nothing, cptr.decay(Monnambuf)));
        }
        return 1;
        }
        case 5: {
        if (monkey_business || uarmg.v) { __pc = 8; continue; }
        __pc = 9; continue;
        }
        case 8: {
        ;
        __pc = 7;
        continue;
        }
        case 9: {
        if (Adornment() & 131072n) { __pc = 11; continue; }
        __pc = 12; continue;
        }
        case 11: {
        otmp = uleft.v;
        { __pc = 3; continue; }
        }
        case 12: {
        if (Adornment() & 262144n) { __pc = 14; continue; }
        __pc = 13; continue;
        }
        case 14: {
        otmp = uright.v;
        { __pc = 3; continue; }
        }
        case 13: {
        __pc = 10;
        continue;
        }
        case 10: {
        __pc = 7;
        continue;
        }
        case 7: {
        __pc = 2;
        continue;
        }
        case 2 /* retry: */: {
        tmp = 0;
        for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = cptr.ldPtr(otmp))
            if ((!uarm.v || !cptr.eq(otmp, uarmc.v)) && !cptr.eq(otmp, uskin.v) && cptr.ld1so(otmp, $obj_oclass) != NHC.COIN_CLASS)
                tmp = (tmp + ((cptr.ldI64o(otmp, $obj_owornmask) & 983167n) ? 5 : 1)) | 0;
        if (!tmp) { __pc = 16; continue; }
        __pc = 15; continue;
        }
        case 16: {
        { __pc = 1; continue; }
        }
        case 15: {
        tmp = (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 421, __s_steal), rn2(tmp)) : rn2(tmp));
        for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = cptr.ldPtr(otmp))
            if ((!uarm.v || !cptr.eq(otmp, uarmc.v)) && !cptr.eq(otmp, uskin.v) && cptr.ld1so(otmp, $obj_oclass) != NHC.COIN_CLASS) {
                tmp = (tmp - ((cptr.ldI64o(otmp, $obj_owornmask) & 983167n) ? 5 : 1)) | 0;
                if (tmp < 0)
                    break;
            }
        if (!otmp) {
            (yield* impossible(__s_steal_fails));
            return 0;
        }
        if ((cptr.eq(otmp, uleft.v) || cptr.eq(otmp, uright.v)) && uarmg.v)
            otmp = uarmg.v;
        if (cptr.eq(otmp, uarmg.v) && uwep.v)
            otmp = uwep.v;
        else if (cptr.eq(otmp, uarm.v) && uarmc.v)
            otmp = uarmc.v;
        else if (cptr.eq(otmp, uarmu.v) && uarmc.v)
            otmp = uarmc.v;
        else if (cptr.eq(otmp, uarmu.v) && uarm.v)
            otmp = uarm.v;
        __pc = 3;
        continue;
        }
        case 3 /* gotobj: */: {
        if (cptr.ldI32o(otmp, $obj_o_id) == cptr.ldI32o(gs, $instance_globals_s_stealoid))
            return 0;
        if (cptr.ldI16o(otmp, $obj_otyp) == NHC.BOULDER && !((cptr.ldU64o((cptr.ldPtro(mtmp, $monst_data)), $permonst_mflags2) & 134217728n) != 0n)) { __pc = 18; continue; }
        __pc = 17; continue;
        }
        case 18: {
        if (!retrycnt++) { __pc = 20; continue; }
        __pc = 19; continue;
        }
        case 20: {
        { __pc = 2; continue; }
        }
        case 19: {
        { __pc = 4; continue; }
        }
        case 17: {
        if (monkey_business) { __pc = 22; continue; }
        __pc = 21; continue;
        }
        case 22: {
        if (cptr.eq(otmp, uball.v))
            ostuck = 1;
        else if (cptr.eq(otmp, uquiver.v) || (cptr.eq(otmp, uswapwep.v) && !cptr.ld1so(u, $you_twoweap)))
            ostuck = 0;
        else
            ostuck = schar((((cptr.ldI32o(otmp, $obj_cursed) & 1) | 0 && cptr.ldI64o(otmp, $obj_owornmask)) || (cptr.eq(otmp, ((((cptr.ldI32o(u, $you_uhandedness) & 1) | 0) == NHM.LEFT_HANDED) ? uleft.v : uright.v)) && (yield* welded(uwep.v))) || (cptr.eq(otmp, ((((cptr.ldI32o(u, $you_uhandedness) & 1) | 0) == NHM.LEFT_HANDED) ? uright.v : uleft.v)) && (yield* welded(uwep.v)) && bimanual(uwep.v)) ? 1 : 0));
        if (ostuck || (yield* can_carry(mtmp, otmp)) == 0) { __pc = 24; continue; }
        __pc = 23; continue;
        }
        case 24: {
        __pc = 4;
        continue;
        }
        case 4 /* cant_take: */: {
        (yield* pline(__s_s_tries_to_s_s_s_but_gives_up, cptr.decay(Monnambuf), cptr.ldPtro(__static_steal_how, (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 481, __s_steal), rn2(4)) : rn2(4)), 8), (cptr.ldI64o(otmp, $obj_owornmask) & 127n) ? __s_your__2 : __s_empty, (cptr.ldI64o(otmp, $obj_owornmask) & 127n) ? (yield* armor_simple_name(otmp)) : (yield* yname(otmp))));
        return !(rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 488, __s_steal), rn2((((inv_cnt(0) / 5) | 0) + 2) | 0)) : rn2((((inv_cnt(0) / 5) | 0) + 2) | 0));
        }
        case 23: {
        __pc = 21;
        continue;
        }
        case 21: {
        if (cptr.ldI16o(otmp, $obj_otyp) == NHC.LEASH && cptr.ldI32o(otmp, $obj_corpsenm)) { __pc = 26; continue; }
        __pc = 25; continue;
        }
        case 26: {
        if (monkey_business && (cptr.ldI32o(otmp, $obj_cursed) & 1) | 0) { __pc = 28; continue; }
        __pc = 27; continue;
        }
        case 28: {
        { __pc = 4; continue; }
        }
        case 27: {
        (yield* o_unleash(otmp));
        __pc = 25;
        continue;
        }
        case 25: {
        was_doffing = doffing(otmp);
        olddelay = (yield* stop_donning(otmp));
        (yield* stop_occupation());
        if (cptr.ldI64o(otmp, $obj_owornmask) & 983167n) { __pc = 30; continue; }
        __pc = 31; continue;
        }
        case 30: {
        let __sw33 = cptr.ld1so(otmp, $obj_oclass);
        if (__sw33 === (NHC.TOOL_CLASS)) { __pc = 34; continue; }
        if (__sw33 === (NHC.AMULET_CLASS)) { __pc = 35; continue; }
        if (__sw33 === (NHC.RING_CLASS)) { __pc = 36; continue; }
        if (__sw33 === (NHC.FOOD_CLASS)) { __pc = 37; continue; }
        if (__sw33 === (NHC.ARMOR_CLASS)) { __pc = 38; continue; }
        __pc = 39; continue;
        }
        case 34: {
        __pc = 35;
        continue;
        }
        case 35: {
        __pc = 36;
        continue;
        }
        case 36: {
        __pc = 37;
        continue;
        }
        case 37: {
        (yield* worn_item_removal(mtmp, otmp));
        { __pc = 32; continue; }
        }
        case 38: {
        armordelay = cptr.ld1so2(objects, cptr.ldI16o(otmp, $obj_otyp), 120, $objclass_oc_delay);
        if (olddelay > 0 && olddelay < armordelay)
            armordelay = olddelay;
        if (monkey_business || unresponsive()) { __pc = 41; continue; }
        __pc = 42; continue;
        }
        case 41: {
        if (armordelay >= 1 && !olddelay && (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 521, __s_steal), rn2(10)) : rn2(10))) { __pc = 44; continue; }
        __pc = 43; continue;
        }
        case 44: {
        { __pc = 4; continue; }
        }
        case 43: {
        (yield* worn_item_removal(mtmp, otmp));
        { __pc = 32; continue; }
        }
        case 42: {
        curssv = (cptr.ldI32o(otmp, $obj_cursed) & 1) | 0;
        cptr.stI32o(otmp, $obj_cursed, 0);
        slowly = (armordelay >= 1 || cptr.ldI64o(gm, $instance_globals_m_multi) < 0n ? 1 : 0);
        if (cptr.ld1so(flags, $flag_female))
            (yield* urgent_pline(__s_s_charms_you_you_gladly_s_your_s, !seen ? __s_she : cptr.decay(Monnambuf), curssv ? __s_let_her_take : (!slowly ? __s_hand_over : (was_doffing ? __s_continue_removing : __s_start_removing)), (yield* armor_simple_name(otmp))));
        else
            (yield* urgent_pline(__s_s_seduces_you_and_s_off_your_s, !seen ? __s_she : (yield* Adjmonnam(mtmp, __s_beautiful)), curssv ? __s_helps_you_to_take : (!slowly ? __s_you_take : (was_doffing ? __s_you_continue_taking : __s_you_start_taking)), (yield* armor_simple_name(otmp))));
        named++;
        nomul(-armordelay);
        cptr.stPtro(gm, $instance_globals_m_multi_reason, __s_taking_off_clothes);
        cptr.stPtro(gn, $instance_globals_n_nomovemsg, null);
        (yield* remove_worn_item(otmp, 1));
        cptr.stI32o(otmp, $obj_cursed, curssv >>> 0);
        if (cptr.ldI64o(gm, $instance_globals_m_multi) < 0n) {
            cptr.stI32o(gs, $instance_globals_s_stealoid, cptr.ldI32o(otmp, $obj_o_id));
            cptr.stI32o(gs, $instance_globals_s_stealmid, cptr.ldI32o(mtmp, $monst_m_id));
            cptr.stPtr(ga, stealarm);
            return 0;
        }
        __pc = 40;
        continue;
        }
        case 40: {
        { __pc = 32; continue; }
        }
        case 39: {
        (yield* impossible(__s_tried_to_steal_a_strange_worn_thing_d, cptr.ld1so(otmp, $obj_oclass)));
        __pc = 32;
        continue;
        }
        case 32: {
        if (!seen && canspotmon(mtmp))
            void cptr.strcpy(cptr.decay(Monnambuf), (yield* Monnam(mtmp)));
        __pc = 29;
        continue;
        }
        case 31: {
        if (cptr.ldI64o(otmp, $obj_owornmask)) {
            item = otmp;
            if (cptr.eq(otmp, uball.v))
                item = uchain.v;
            (yield* worn_item_removal(mtmp, item));
            if ((cptr.ldI64o(otmp, $obj_owornmask) & 1792n) != 0n)
                (yield* remove_worn_item(otmp, 0));
        }
        __pc = 29;
        continue;
        }
        case 29: {
        if (objnambuf)
            void cptr.strcpy(objnambuf, (yield* yname(otmp)));
        if (!Conflict() && !(was_punished && !Punished()))
            cptr.stI32o(mtmp, $monst_mavenge, 1);
        if ((cptr.ldI32o(otmp, $obj_unpaid) & 1))
            (yield* subfrombill(otmp, (yield* shop_keeper(cptr.ld1so(u, $you_ushops)))));
        (yield* freeinv(otmp));
        if (cptr.ldI32o(iflags, $instance_flags_last_msg) == NHC.PLNMSG_MON_TAKES_OFF_ITEM && cptr.ld1so(cptr.ldPtro(mtmp, $monst_data), $permonst_mlet) == NHC.S_NYMPH)
            ++named;
        (yield* urgent_pline(__s_s_stole_s, named ? __s_she : cptr.decay(Monnambuf), (yield* doname(otmp))));
        (yield* encumber_msg());
        could_petrify = (cptr.ldI16o(otmp, $obj_otyp) == NHC.CORPSE && touch_petrifies(cptr.add(mons, cptr.ldI32o(otmp, $obj_corpsenm), 96)) ? 1 : 0);
        cptr.stI32o(otmp, $obj_how_lost, NHM.LOST_STOLEN);
        void (yield* mpickobj(mtmp, otmp));
        if (could_petrify && !(cptr.ldI64o(mtmp, $monst_misc_worn_check) & 16n)) {
            (yield* minstapetrify(mtmp, 1));
            return -1;
        }
        return (cptr.ldI64o(gm, $instance_globals_m_multi) < 0n) ? 0 : 1;
        }
        }
        if (__pc === -1) break __dispatch;
    }
}

/** C ref: steal.c:618 — @param {CPtr<struct monst>} mtmp @param {CPtr<struct obj>} otmp @returns {CInt} */
export function* mpickobj(mtmp, otmp) {
    let freed_otmp;
    let snuff_otmp = 0;
    if (!otmp) {
        (yield* impossible(__s_monster_s_taking_or_picking_up_nothing, pmname(cptr.ldPtro(mtmp, $monst_data), Mgender(mtmp))));
        return 1;
    } else if (cptr.eq(otmp, uball.v) || cptr.eq(otmp, uchain.v)) {
        (yield* impossible(__s_monster_s_taking_or_picking_up_attached, pmname(cptr.ldPtro(mtmp, $monst_data), Mgender(mtmp)), (cptr.eq(otmp, uchain.v)) ? __s_chain : __s_ball, (yield* simpleonames(otmp))));
        return 0;
    }
    if (cptr.eq(otmp, cptr.ldPtro(gt, $instance_globals_t_thrownobj)))
        cptr.stPtro(gt, $instance_globals_t_thrownobj, null);
    else if (cptr.eq(otmp, cptr.ldPtro(gk, $instance_globals_k_kickedobj)))
        cptr.stPtro(gk, $instance_globals_k_kickedobj, null);
    if ((cptr.ldI32o(otmp, $obj_unpaid) & 1) | 0 || ((cptr.ldPtro((otmp), $obj_cobj) !== null) && count_unpaid(cptr.ldPtro(otmp, $obj_cobj)))) {
        (yield* subfrombill(otmp, (yield* find_objowner(otmp, cptr.ldI16o(otmp, $obj_ox), cptr.ldI16o(otmp, $obj_oy)))));
    }
    if (obj_sheds_light(otmp) && attacktype(cptr.ldPtro(mtmp, $monst_data), NHM.AT_ENGL)) {
        if (((cptr.ldI32o(u, $you_uswallow) & 1) | 0 && (cptr.eq(cptr.ldPtro(u, $you_ustuck), (mtmp)))) && !Blind())
            (yield* pline(__s_s_out, (yield* Tobjnam(otmp, __s_go))));
        snuff_otmp = 1;
    }
    cptr.stI32o(otmp, $obj_no_charge, 0);
    if (!cptr.ld1so(mtmp, $monst_mtame)) {
        if (!canseemon(mtmp) && !cptr.eq(mtmp, cptr.ldPtro(u, $you_ustuck)))
            unknow_object(otmp);
        if (((cptr.ldI32o(otmp, $obj_how_lost) & 7) | 0) == NHM.LOST_THROWN)
            cptr.stI32o(otmp, $obj_how_lost, NHM.LOST_STOLEN);
        else if (((cptr.ldI32o(otmp, $obj_how_lost) & 7) | 0) == NHM.LOST_DROPPED)
            cptr.stI32o(otmp, $obj_how_lost, NHM.LOST_NONE);
    }
    (yield* carry_obj_effects(otmp));
    freed_otmp = (yield* add_to_minv(mtmp, otmp));
    if (snuff_otmp)
        (yield* snuff_light_source(cptr.ldI16o(mtmp, $monst_mx), cptr.ldI16o(mtmp, $monst_my)));
    return freed_otmp;
}

/** C ref: steal.c:689 — @param {CPtr<struct monst>} mtmp */
export function* stealamulet(mtmp) {
    let buf = new Uint8Array(256);
    let otmp = null;
    let obj = null;
    let real = 0;
    let fake = 0;
    let n;
    for (n = 0, obj = cptr.ldPtro(gi, $instance_globals_i_invent); obj; obj = cptr.ldPtr(obj))
        if ((cptr.ld1so((obj), $obj_oartifact) >= NHC.ART_ORB_OF_DETECTION))
            ++n, otmp = obj;
    if (n > 1) {
        n = (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 702, __s_stealamulet), rnd(n)) : rnd(n));
        for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = cptr.ldPtr(otmp))
            if ((cptr.ld1so((otmp), $obj_oartifact) >= NHC.ART_ORB_OF_DETECTION) && !--n)
                break;
    }
    if (!otmp) {
        if ((cptr.ldI32o(u, $you_uhave) & 1)) {
            real = NHC.AMULET_OF_YENDOR;
            fake = NHC.FAKE_AMULET_OF_YENDOR;
        } else if ((cptr.ldI32o(u, $you_uhave + $u_have_bell) & 1)) {
            real = NHC.BELL_OF_OPENING;
            fake = NHC.BELL;
        } else if ((cptr.ldI32o(u, $you_uhave + $u_have_book) & 1)) {
            real = NHC.SPE_BOOK_OF_THE_DEAD;
        } else if ((cptr.ldI32o(u, $you_uhave + $u_have_menorah) & 1)) {
            real = NHC.CANDELABRUM_OF_INVOCATION;
        } else
            return;
        for (n = 0, obj = cptr.ldPtro(gi, $instance_globals_i_invent); obj; obj = cptr.ldPtr(obj))
            if (cptr.ldI16o(obj, $obj_otyp) == real || (cptr.ldI16o(obj, $obj_otyp) == fake && !(cptr.ldI32o(mtmp, $monst_iswiz) & 1)))
                ++n, otmp = obj;
        if (n > 1) {
            n = (rng_log_enabled() ? (rng_log_set_caller(__s_steal_c, 728, __s_stealamulet), rnd(n)) : rnd(n));
            for (otmp = cptr.ldPtro(gi, $instance_globals_i_invent); otmp; otmp = cptr.ldPtr(otmp))
                if ((cptr.ldI16o(otmp, $obj_otyp) == real || (cptr.ldI16o(otmp, $obj_otyp) == fake && !(cptr.ldI32o(mtmp, $monst_iswiz) & 1))) && !--n)
                    break;
        }
    }
    if (otmp) {
        if ((cptr.eq(otmp, uarm.v) || cptr.eq(otmp, uarmu.v)) && uarmc.v)
            (yield* worn_item_removal(mtmp, uarmc.v));
        if (cptr.eq(otmp, uarmu.v) && uarm.v)
            (yield* worn_item_removal(mtmp, uarm.v));
        if ((cptr.eq(otmp, uarmg.v) || ((cptr.eq(otmp, uright.v) || cptr.eq(otmp, uleft.v)) && uarmg.v)) && uwep.v) {
            if (cptr.ld1so(u, $you_twoweap))
                (yield* worn_item_removal(mtmp, uswapwep.v));
            (yield* worn_item_removal(mtmp, uwep.v));
        }
        if ((cptr.eq(otmp, uright.v) || cptr.eq(otmp, uleft.v)) && uarmg.v)
            (yield* worn_item_removal(mtmp, uarmg.v));
        if (cptr.ldI64o(otmp, $obj_owornmask))
            (yield* worn_item_removal(mtmp, otmp));
        if ((cptr.ldI32o(otmp, $obj_unpaid) & 1))
            (yield* subfrombill(otmp, (yield* shop_keeper(cptr.ld1so(u, $you_ushops)))));
        (yield* freeinv(otmp));
        void cptr.strcpy(cptr.decay(buf), (yield* doname(otmp)));
        void (yield* mpickobj(mtmp, otmp));
        (yield* pline(__s_s_steals_s, (yield* Some_Monnam(mtmp)), cptr.decay(buf)));
        if (((cptr.ldU64o((cptr.ldPtro(mtmp, $monst_data)), $permonst_mflags1) & 33554432n) != 0n) && !(yield* tele_restrict(mtmp)))
            void (yield* rloc(mtmp, NHM.RLOC_MSG));
        (yield* encumber_msg());
    }
}

/** C ref: steal.c:772 — @param {CPtr<struct monst>} mon @param {CPtr<struct obj>} obj @param {CInt} ochance @param {CInt} achance */
export function* maybe_absorb_item(mon, obj, ochance, achance) {
    if (cptr.eq(obj, uball.v) || cptr.eq(obj, uchain.v) || cptr.ld1so(obj, $obj_oclass) == NHC.ROCK_CLASS || obj_resists(obj, (100 - ochance) | 0, (100 - achance) | 0) || !(yield* touch_artifact(obj, mon)))
        return;
    if ((cptr.ld1so((obj), $obj_where) == NHM.OBJ_INVENT)) {
        if (cptr.ldI64o(obj, $obj_owornmask))
            (yield* remove_worn_item(obj, 1));
        if ((cptr.ldI32o(obj, $obj_unpaid) & 1))
            (yield* subfrombill(obj, (yield* shop_keeper(cptr.ld1so(u, $you_ushops)))));
        if (((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), cptr.ldI16o(mon, $monst_my), 8), cptr.ldI16o(mon, $monst_mx)) & NHM.IN_SIGHT) != 0)) {
            (yield* pline(__s_s_pulls_s_away_from_you_and_absorbs_s, (yield* Some_Monnam(mon)), (yield* yname(obj)), (cptr.ldI64o(obj, $obj_quan) > 1n) ? __s_them : __s_it));
        } else {
            let hand_s = (yield* body_part(NHC.HAND));
            if (bimanual(obj))
                hand_s = (yield* makeplural(hand_s));
            (yield* pline(__s_s_s_pulled_from_your_s, upstart((yield* yname(obj))), (yield* otense(obj, __s_are)), hand_s));
        }
        (yield* freeinv(obj));
        (yield* encumber_msg());
    } else {
        if (canspotmon(mon))
            (yield* pline(__s_s_absorbs_s, (yield* Monnam(mon)), (yield* yname(obj))));
    }
    void (yield* mpickobj(mon, obj));
}

/** C ref: steal.c:814 — @param {CPtr<struct monst>} mon @param {CPtr<struct obj>} obj @param {CInt} verbosely */
export function* mdrop_obj(mon, obj, verbosely) {
    let omx = cptr.ldI16o(mon, $monst_mx);
    let omy = cptr.ldI16o(mon, $monst_my);
    let unwornmask = cptr.ldI64o(obj, $obj_owornmask);
    let obj_name = (yield* distant_name(obj, doname));
    (yield* extract_from_minvent(mon, obj, 0, 1));
    if (unwornmask && cptr.ld1so(mon, $monst_mtame) && (unwornmask & 1048576n) != 0n && !(cptr.ldI32o(obj, $obj_unpaid) & 1) && (yield* costly_spot(omx, omy)) && cptr.strchr((yield* in_rooms(cptr.ldI16(u), cptr.ldI16o(u, $you_uy), NHC.SHOPBASE)), (cptr.ldI32o3(svl, omx, 756, omy, 36, $instance_globals_saved_l_level + $rm_roomno) & 63) | 0)) {
        cptr.stI32o(obj, $obj_no_charge, 1);
    }
    if (verbosely && ((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), omy, 8), omx) & NHM.IN_SIGHT) != 0))
        (yield* pline_mon(mon, __s_s_drops_s, (yield* Monnam(mon)), obj_name));
    if (!(yield* flooreffects(obj, omx, omy, __s_fall))) {
        (yield* place_object(obj, omx, omy));
        (yield* stackobj(obj));
    }
    if (!(cptr.ldI32o((mon), $monst_mhp) < 1) && unwornmask)
        (yield* update_mon_extrinsics(mon, obj, 0, 1));
}

/** C ref: steal.c:852 — @param {CPtr<struct monst>} mon */
export function* mdrop_special_objs(mon) {
    let obj;
    let otmp;
    for (obj = cptr.ldPtro(mon, $monst_minvent); obj; obj = otmp) {
        otmp = cptr.ldPtr(obj);
        if (obj_resists(obj, 0, 0) || is_quest_artifact(obj)) {
            if (cptr.ldI16o(mon, $monst_mx)) {
                (yield* mdrop_obj(mon, obj, 0));
            } else {
                (yield* extract_from_minvent(mon, obj, 1, 1));
                (yield* rloco(obj));
            }
        }
    }
}

/** C ref: steal.c:875 — @param {CPtr<struct monst>} mtmp @param {CInt} show @param {CInt} is_pet */
export function* relobj(mtmp, show, is_pet) {
    let otmp;
    let omx = cptr.ldI16o(mtmp, $monst_mx);
    let omy = cptr.ldI16o(mtmp, $monst_my);
    if ((cptr.ldI32o(mtmp, $monst_isgd) & 1) | 0 && (otmp = findgold(cptr.ldPtro(mtmp, $monst_minvent))) !== null) {
        if (canspotmon(mtmp))
            (yield* pline(__s_s_gold_s, (yield* s_suffix((yield* Monnam(mtmp)))), canseemon(mtmp) ? __s_vanishes : __s_seems_to_vanish));
        (yield* obj_extract_self(otmp));
        (yield* obfree(otmp, null));
    }
    while ((otmp = (is_pet ? (yield* droppables(mtmp)) : cptr.ldPtro(mtmp, $monst_minvent))) !== null) {
        (yield* mdrop_obj(mtmp, otmp, schar((is_pet && cptr.ld1so(flags, $flag_verbose) ? 1 : 0))));
    }
    if (show && ((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), omy, 8), omx) & NHM.IN_SIGHT) != 0))
        (yield* newsym(i16(omx), i16(omy)));
}

// --- BEGIN c2js reset block (tools/c2js/resetify.mjs) — do not edit ---
// 1 bindings: 0 rebound+refilled, 0 rebound, 1 refilled.
// S/P are supplied by js/generated-y/__reset.js so this module needs no new import.
let __c2js_rs = null;
export function __captureState(S) { __c2js_rs = [S(__static_steal_how)]; }
export function __resetState(P) {
    const r = __c2js_rs;
    if (r === null) throw new Error("steal.js: __resetState before __captureState");
    P(r[0]);
}
// --- END c2js reset block ---
